### ISSUE TITLE
bugs in the newest code

### ISSUE THREAD

**Issue by xixixi2000** [linweiyuan/go-chatgpt-api#101]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8c74aa]

goroutine 13 [running]:
github.com/linweiyuan/go-chatgpt-api/api.init.0.func1()
        /root/go-chatgpt-api/api/common.go:106 +0x4a
created by github.com/linweiyuan/go-chatgpt-api/api.init.0
        /root/go-chatgpt-api/api/common.go:100 +0x26c

**Comment by linweiyuan** [comment]
shoule be fixed

**Comment by xixixi2000** [comment]
why i use the old heartbeatcheck version got the stable running, but the new healthcheck sometimes got 403?

**Comment by linweiyuan** [comment]
not sure the root cause, need to test

**Comment by xixixi2000** [comment]
ok, I will report it later, the 403 error might be cause by the expiration of the _cf_bm cookie and refreshing in error

**Comment by linweiyuan** [comment]
403 should be fixed

**Comment by xixixi2000** [comment]
yes, the old code yesterday will hung the connection, but after the update of the sse, it seems gone
