### ISSUE TITLE
404 error,

### ISSUE THREAD

**Issue by justincnn** [linweiyuan/go-chatgpt-api#102]
my vps can access openai via warp,

dock yml:

services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - GO_CHATGPT_API_PROXY=
    restart: unless-stopped

go-chatgpt-api  | [GIN] 2023/05/05 - 09:27:25 | 404 |       2.304µs |       10.0.0.87 | POST     "/conversation"
go-chatgpt-api  | [GIN] 2023/05/05 - 09:27:27 | 404 |       2.254µs |       10.0.0.87 | POST     "/conversation"
go-chatgpt-api  | [GIN] 2023/05/05 - 09:27:27 | 404 |       2.755µs |       10.0.0.87 | POST     "/conversation"
go-chatgpt-api  | [GIN] 2023/05/05 - 09:27:28 | 404 |       2.565µs |       10.0.0.87 | POST     "/conversation"
go-chatgpt-api  | [GIN] 2023/05/05 - 09:27:29 | 404 |       2.585µs |       10.0.0.87 | POST     "/conversation"
go-chatgpt-api  | [GIN] 2023/05/05 - 09:27:29 | 404 |       2.224µs |       10.0.0.87 | POST     "/conversation"
go-chatgpt-api  | [GIN] 2023/05/05 - 09:27:30 | 404 |       2.605µs |       10.0.0.87 | POST     "/conversation"

**Comment by dwdcth** [comment]
![image](https://user-images.githubusercontent.com/1883728/236361237-5c242ed1-ee63-4de1-b750-fa481453eeb6.png)
是不是路由变了

**Comment by linweiyuan** [comment]
不是它变了，我这边变了，昨晚改了所有 API 链接，方便管理，`/chatgpt/conversation`

**Comment by dwdcth** [comment]
好的

**Comment by justincnn** [comment]
> 不是它变了，我这边变了，昨晚改了所有 API 链接，方便管理，`/chatgpt/conversation`

thanks for your help

**Comment by Peterpig** [comment]
一键部署的可以修改这里

![image](https://github.com/linweiyuan/go-chatgpt-api/assets/7956973/32349594-7876-4500-a45e-53b182d3af27)

**Comment by itcuihao** [comment]
> 一键部署的可以修改这里
> 
> ![image](https://user-images.githubusercontent.com/7956973/238231990-32349594-7876-4500-a45e-53b182d3af27.png)
```
ConnectionRefusedError: [Errno 111] Connect call failed ('172.26.0.3', 8080)

```
改了还是不行，config.yaml 需要改么？

**Comment by linweiyuan** [comment]
`go-chatgpt-api` 没起来，看下它的日志
