### ISSUE TITLE
go-chatgpt-api 启动失败

### ISSUE THREAD

**Issue by didiplus** [linweiyuan/go-chatgpt-api#104]
`
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
`
go-chatgpt-api 启动失败报如下错误

![image](https://user-images.githubusercontent.com/20027156/236373901-3e446b29-32de-4bfd-9ee9-1fb447f50e33.png)

**Comment by linweiyuan** [comment]
是不是国内服务器

**Comment by EvanDbg** [comment]
docker 权限不够，增加 privileged: true
