### ISSUE TITLE
/chatgpt/login 失效

### ISSUE THREAD

**Issue by OverKit** [linweiyuan/go-chatgpt-api#105]
昨天还可以使用的。
```bash
curl -X POST "http://localhost:8080/chatgpt/login" \
 -H "Content-Type: application/json" \
 -d '{"username": "xxxxxxx@qq.com", "password": "************"}'
```
返回
```
{"errorMessage":"Email or password is not correct."}
```
<https://github.com/linweiyuan/go-chatgpt-api/blob/main/api/chatgpt/access_token.go#L70>

**Comment by linweiyuan** [comment]
似乎和节点有关，这个刚试到 403，但是换个节点就 200 了

**Comment by JustZiya** [comment]
我这里有时候403、有时候429。但是用另一台服务器上的chatgpt-web访问又是正常的，很奇怪

![CleanShot 2023-05-05 at 15 29 28@2x](https://user-images.githubusercontent.com/721479/236400086-10f4f1ee-7720-4b52-afc9-58ff1d5a2f9c.png)

**Comment by linweiyuan** [comment]
部分节点直连可以 `200`，部分节点 `403` 要注入 `__cf_bm`，相同的节点一天内分时段 `200` 或者 `403`，不是很清楚具体验证的逻辑

**Comment by linweiyuan** [comment]
这个不宜登录太多，会 429，然后进入官方页面也会 429，导致页面空白

**Comment by superen7527** [comment]
原来如此，话说这种能不能套wrap？我的意思是，每次登录都走不同的wrap节点ip，还是每次docker run一次固定一个ip？

**Comment by linweiyuan** [comment]
目前是固定的，所有请求都走 `GO_CHATGPT_API_PROXY`，如果设置了的话

**Comment by superen7527** [comment]
我的意思是，走wrap以后是一个固定的wrap ip节点，还是每次请求用的wrap节点都会不同？

**Comment by linweiyuan** [comment]
IP 不干净，连拿静态文件都会 403（一时一时）

![2023-05-05_21-44](https://user-images.githubusercontent.com/49076004/236474785-56c217b0-bd33-41c8-8ea5-e87e39f3595d.png)

**Comment by superen7527** [comment]
对 我没电脑 用的vps。不过没有明确429，我输入token能用对话，但是login提示就是 Failed to get CSRF token，这是429?还不懂怎么看高级日志

**Comment by linweiyuan** [comment]
登录 403 已修复

**Comment by xixixi2000** [comment]
login fixed, what's wrong with it? it works before yesterday

**Comment by boygoboy** [comment]
经过测试有的ip会触发cloudflare的人机验证报403，目前可以通过设置代理解决，或者使用类似这种服务https://anti-captcha.com/zh/apidoc/task-types/TurnstileTask， 但是需要网站的site-key目前没找到。

**Comment by linweiyuan** [comment]
昨天那个错误原因在最后一步的重定向，有两个域名，auth0 开头的无需注入 cookie，chat 开头的则要，最后一步时它会从 auth0 重定向到 chat，导致 cookie 丢失

改成了手动处理重定向，再最后一步重新注入 cookie，就没了 403

**Comment by linweiyuan** [comment]
> 经过测试有的ip会触发cloudflare的人机验证报403，目前可以通过设置代理解决，或者使用类似这种服务[https://anti-captcha.com/zh/apidoc/task-types/TurnstileTask，](https://anti-captcha.com/zh/apidoc/task-types/TurnstileTask%EF%BC%8C) 但是需要网站的site-key目前没找到。

这种服务感觉是收费的

**Comment by boygoboy** [comment]
> > 经过测试有的ip会触发cloudflare的人机验证报403，目前可以通过设置代理解决，或者使用类似这种服务[https://anti-captcha.com/zh/apidoc/task-types/TurnstileTask，](https://anti-captcha.com/zh/apidoc/task-types/TurnstileTask%EF%BC%8C) 但是需要网站的site-key目前没找到。
> 
> 这种服务感觉是收费的

是要收费的，不过比家宽要便宜多，或者直接用家宽代理一定程度也能绕过403

**Comment by xixixi2000** [comment]
for my test, not only the IP, but also the browser , user-agent ? I use a chrome 109 in win8.1 (the highest version ) always got 403 and a chrome 112 in win11 no 403, they use the same proxy

**Comment by xixixi2000** [comment]
> 昨天那个错误原因在最后一步的重定向，有两个域名，auth0 开头的无需注入 cookie，chat 开头的则要，最后一步时它会从 auth0 重定向到 chat，导致 cookie 丢失
> 
> 改成了手动处理重定向，再最后一步重新注入 cookie，就没了 403

oic, it means we can login without cookie the day before yesterday?

**Comment by linweiyuan** [comment]
相同的节点，如果浏览器无痕模式打开 ChatGPT 官网需要手动点验证码，就需要 cookie，直接进入登录页面就无需

**Comment by linweiyuan** [comment]
如果在一段时间内，每次打开都点，点多几次后，这个节点就可能不再需要验证码，保持一段时间，具体多久不知

这个时候打开 `go-chatgpt-api` 就会是直接 200，不再接 cookie 服务拿 cookie
