### ISSUE TITLE
got 403 continiously from 19:00 and cannot recover itself

### ISSUE THREAD

**Issue by xixixi2000** [linweiyuan/go-chatgpt-api#108]
[GIN] 2023/05/06 - 19:15:58 | 403 |   87.230883ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:15:59 | 403 |   12.123725ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:16:07 | 403 |    14.58511ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:16:07 | 403 |   14.736533ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:16:24 | 403 |   53.753087ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:16:24 | 403 |   11.575308ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:16:51 | 403 |   13.516782ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:16:51 | 403 |   14.021227ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:17:10 | 403 |   17.129814ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:17:10 | 403 |   11.063182ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:17:32 | 403 |   53.244969ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:17:32 | 403 |   66.529894ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:17:40 | 403 |   19.539085ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:17:40 | 403 |   11.225317ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:17:46 | 403 |   12.222895ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:17:47 | 403 |   12.055892ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:17:56 | 403 |   55.479849ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:17:57 | 403 |   52.634018ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:21:41 | 403 |   83.446487ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:21:42 | 403 |   15.774219ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:23:02 | 403 |    59.25698ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:23:03 | 403 |   53.890821ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:23:49 | 403 |   59.268246ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:23:50 | 403 |   12.789189ms |     127.0.0.1 | POST     "/chatgpt/conversation"

the network to the sse link is ok
need a restart of the application

**Comment by linweiyuan** [comment]
please restart `go-chatgpt-api` to see if 403 is gone

**Comment by xixixi2000** [comment]
> please restart `go-chatgpt-api` to see if 403 is gone

yes, need a restart

**Comment by xixixi2000** [comment]
[GIN] 2023/05/06 - 19:40:54 | 403 |   14.136824ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:41:22 | 403 |   25.871114ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:41:22 | 403 |   15.235523ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:41:31 | 403 |   14.267282ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:41:32 | 403 |   14.430715ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:41:48 | 403 |    63.91871ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /chatgpt/login            --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.Login (4 handlers)
[GIN-debug] GET    /chatgpt/conversations    --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.GetConversations (4 handlers)
[GIN-debug] PATCH  /chatgpt/conversations    --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.ClearConversations (4 handlers)
[GIN-debug] POST   /chatgpt/conversations    --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.ClearConversations (4 handlers)
[GIN-debug] POST   /chatgpt/conversation     --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.CreateConversation (4 handlers)
[GIN-debug] POST   /chatgpt/conversation/gen_title/:id --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.GenerateTitle (4 handlers)
[GIN-debug] GET    /chatgpt/conversation/:id --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.GetConversation (4 handlers)
[GIN-debug] PATCH  /chatgpt/conversation/:id --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.UpdateConversation (4 handlers)
[GIN-debug] POST   /chatgpt/conversation/:id --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.UpdateConversation (4 handlers)
[GIN-debug] POST   /chatgpt/conversation/message_feedback --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.FeedbackMessage (4 handlers)
[GIN-debug] GET    /chatgpt/models           --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.GetModels (4 handlers)
[GIN-debug] GET    /chatgpt/accounts/check   --> github.com/linweiyuan/go-chatgpt-api/api/chatgpt.GetAccountCheck (4 handlers)
[GIN-debug] POST   /platform/login           --> github.com/linweiyuan/go-chatgpt-api/api/platform.Login (4 handlers)
[GIN-debug] GET    /platform/v1/models       --> github.com/linweiyuan/go-chatgpt-api/api/platform.ListModels (4 handlers)
[GIN-debug] GET    /platform/v1/models/:model --> github.com/linweiyuan/go-chatgpt-api/api/platform.RetrieveModel (4 handlers)
[GIN-debug] POST   /platform/v1/completions  --> github.com/linweiyuan/go-chatgpt-api/api/platform.CreateCompletions (4 handlers)
[GIN-debug] POST   /platform/v1/chat/completions --> github.com/linweiyuan/go-chatgpt-api/api/platform.CreateChatCompletions (4 handlers)
[GIN-debug] POST   /platform/v1/edits        --> github.com/linweiyuan/go-chatgpt-api/api/platform.CreateEdit (4 handlers)
[GIN-debug] POST   /platform/v1/images/generations --> github.com/linweiyuan/go-chatgpt-api/api/platform.CreateImage (4 handlers)
[GIN-debug] POST   /platform/v1/embeddings   --> github.com/linweiyuan/go-chatgpt-api/api/platform.CreateEmbeddings (4 handlers)
[GIN-debug] GET    /platform/v1/files        --> github.com/linweiyuan/go-chatgpt-api/api/platform.ListFiles (4 handlers)
[GIN-debug] GET    /platform/dashboard/billing/credit_grants --> github.com/linweiyuan/go-chatgpt-api/api/platform.GetCreditGrants (4 handlers)
[GIN-debug] GET    /platform/dashboard/billing/subscription --> github.com/linweiyuan/go-chatgpt-api/api/platform.GetSubscription (4 handlers)
[GIN-debug] GET    /platform/dashboard/user/api_keys --> github.com/linweiyuan/go-chatgpt-api/api/platform.GetApiKeys (4 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8081
INFO[0000] [2023-05-06 19:41:49] Welcome to ChatGPT
[GIN] 2023/05/06 - 19:41:49 | 429 |  571.687683ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:42:13 | 429 |  127.318712ms |     127.0.0.1 | POST     "/chatgpt/conversation"
[GIN] 2023/05/06 - 19:42:17 | 200 |  1.195800257s |     127.0.0.1 | POST     "/chatgpt/conversation"

**Comment by xixixi2000** [comment]
the 429 error is coz on the busy of the gpt-4 model

**Comment by phoniwell** [comment]
I had the same issue since 6:00 pm. However, after restarting the container, those 403 error messages disappeared and did not reoccur.

**Comment by xixixi2000** [comment]
func getCookiesSSE() {
        req, _ := http.NewRequest(http.MethodGet, getCookiesSSEUrl, nil)
        resp, err := Client.Do(req)
        if err != nil {
                time.Sleep(time.Second)
                getCookiesSSE()
                return
        }

        defer resp.Body.Close()
        reader := bufio.NewReader(resp.Body)
        for {
                line, err := reader.ReadString('\n')
                if err != nil { // if error occurs here, in the dead loop, a time sleep should be better ?
                        break
                }

                line = strings.TrimSpace(line)
                if strings.HasPrefix(line, "event") || line == "" {
                        continue
                }

                responseMap := make(map[string]string)
                json.Unmarshal([]byte(line[6:]), &responseMap)
                __cf_bm = responseMap["__cf_bm"]

                if firstTime {
                        logger.Info(welcomeText)
                        firstTime = false
                }
        }

        getCookiesSSE()
}

I think the error might be here in the ReadString returned EOF error, and recall itself and recall and recall .... A time sleep should be better ? or read the cookie from file as a backup to avoid the read error from network ?

**Comment by linweiyuan** [comment]
not related

**Comment by xixixi2000** [comment]
no __cf_bm ?
curl https://get-chatgpt-cookies.linweiyuan.com/sse

event: cookies
data: {"__Host-next-auth.csrf-token":"370477406ce891ac7bfda65d510722a2ac0f4d3e49820971eba5ce353a7ed0de%7Cfbf7c90a0816f757093ec672b3fbe0ee986efdec256b9a7749d206166cff46af","__Secure-next-auth.callback-url":"https%3A%2F%2Fchat.openai.com","_cfuvid":"KO2wDYNMADCzvP5TVzKa4yyzCVkqS1izyYEKBXnQIl0-1683388602944-0-604800000"}

**Comment by linweiyuan** [comment]
1. this cookie information is visible to everyone and does not need to be redacted
2. how do I know if you manually deleted it? any key in the cookies could potentially be empty, but the key `__cf_bm` must be present
3. I see in the logs that there are always client connections coming in and disconnecting shortly after, and it turns out it's you

**Comment by xixixi2000** [comment]
I got a 403 error and then check the sse link and found that no __cf_bm in it, I don't know why connect and disconnect, I just run the program?

**Comment by xixixi2000** [comment]
I found that __cf_bm is not always needed now, but after a period of time, I got 403 and need a restart, and from 8 hours ago, I got no __cf_bm from the server, including restart

**Comment by linweiyuan** [comment]
when api starts, it will do a health check:
- if 200, do not connect to cookies api to reduce the server load, until 403 -> restart api -> health check -> 403 -> connect to cookies api
- if 403, connect to cookies api to get cookies

normally is should be keeping a long connection, not like connect for seconds and disconnect, if not you, I don't know who is doing some wired testing

maybe I need to change a new endpoint name

![2023-05-07_09-10](https://user-images.githubusercontent.com/49076004/236652791-9f867294-022c-465f-a3de-0d53aaedf813.png)

![2023-05-07_09-11](https://user-images.githubusercontent.com/49076004/236652796-3a350a65-8c1f-40e6-a738-fab40329aaee.png)

**Comment by linweiyuan** [comment]
if you `curl https://chat.openai.com` in `warp`, at least `__cf_bm` will be returned, even if it is invalid

![2023-05-07_09-20](https://user-images.githubusercontent.com/49076004/236652942-14669c04-decd-44d5-9988-7024718f0b56.png)

if you see cookies endpoint does not return `__cf_bm` next time, report it ASAP, I will do a testing

**Comment by phoniwell** [comment]
403 messages came back, and this time restart doesn't work at all.

**Comment by xixixi2000** [comment]
> when api starts, it will do a health check:
> 
> * if 200, do not connect to cookies api to reduce the server load, until 403 -> restart api -> health check -> 403 -> connect to cookies api
> * if 403, connect to cookies api to get cookies
> 
> normally is should be keeping a long connection, not like connect for seconds and disconnect, if not you, I don't know who is doing some wired testing
> 
> maybe I need to change a new endpoint name
> 
> ![2023-05-07_09-10](https://user-images.githubusercontent.com/49076004/236652791-9f867294-022c-465f-a3de-0d53aaedf813.png)
> 
> ![2023-05-07_09-11](https://user-images.githubusercontent.com/49076004/236652796-3a350a65-8c1f-40e6-a738-fab40329aaee.png)

404 is coursing by the old code of getting the old link, the old link is a short connection and get cookie while getting 403 error

yes, I found that a __cf_bm is always returned when getting the page, and sometimes returned when doing the auth/session

**Comment by xixixi2000** [comment]
but I don't know why the long connection only last for 20 seconds ？

**Comment by xixixi2000** [comment]
> 403 messages came back, and this time restart doesn't work at all.

I can fix the 403 error when doing a restart

**Comment by linweiyuan** [comment]
> but I don't know why the long connection only last for 20 seconds ？

this is because it is maded by something like curl instead of api

**Comment by xixixi2000** [comment]
> > but I don't know why the long connection only last for 20 seconds ？
> 
> this is because it is maded by something like curl instead of api

then it's not me, I seldom use curl to get the sse, I use it just for finding the reason of why I got 403

**Comment by fsyllkn** [comment]
yes，yesterday，I got 404 error

**Comment by linweiyuan** [comment]
403: debugging

404: update image will fix

**Comment by linweiyuan** [comment]
is there any 403 after today 15:00?

**Comment by xixixi2000** [comment]
after 13:00

**Comment by linweiyuan** [comment]
403 was fixed at 15:00

**Comment by phoniwell** [comment]
I'm afraid the problem is still there. Just updated to the latest version and restart, 403 came back again.
![Uploading Screenshot_2023-05-07-20-02-50-491_com.sonelli.juicessh.jpg…]()

**Comment by linweiyuan** [comment]
403 will not be fixed, because server is being attacked, I will not provide public cookies api anymore. If you has 403 issue, deploy your own cookies api or use legacy version.

https://user-images.githubusercontent.com/49076004/236680165-7c5c28d4-b7ca-4f3c-8f56-0430257a526c.mp4

**Comment by xixixi2000** [comment]
the host can not be resolved by the dns

**Comment by linweiyuan** [comment]
@phoniwell pull new latest image, if still not work, use legacy version or swtich to other alternatives first

**Comment by phoniwell** [comment]
I have retrieved the most recent images, and this time I didn't encounter a 403 error. Hopefully, this issue has been resolved.

By the way, I donated RMB20 at 08:31 AM on May 6 to show my appreciation for your hard work.

**Comment by linweiyuan** [comment]
Thanks for support.
