### ISSUE TITLE
重命名对话标题  `PATCH /chatgpt/conversation/{conversationID}` 404了

### ISSUE THREAD

**Issue by yinque** [linweiyuan/go-chatgpt-api#109]
api文档里`/chatgpt/conversation/*`类的地址404了。
抓官网的包分析了下，可能官方换成`/conversation/*`了。
例如重命名对话标题这个接口，
使用`PATCH /chatgpt/conversation/{conversationID}`，后台404，无法更改标题
使用`PATCH /conversation/{conversationID}`，后台200，成功更改标题
后台截图：
![image](https://user-images.githubusercontent.com/45099564/236643665-0bc3a588-cb7c-42e6-8f73-330a6504e1de.png)

**Comment by linweiyuan** [comment]
虽然文档更新了，但是你用的镜像却没有同步更新

这个日志时区显示也是好多天前就改了，比如正确显示应该是 `05/07 03:06:15`

拉新镜像可解决

**Comment by yinque** [comment]
好的。感谢
