### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by ysben** [linweiyuan/go-chatgpt-api#110]
我看代码里面好像需要访问 https://get-chatgpt-cookies.linweiyuan.com/sse ，这个是获取什么的呢？如果我去掉了会影响哪些功能呢？

**Comment by linweiyuan** [comment]
去掉了可能 403，这个只是获取 cookie，不会上传你的敏感数据

**Comment by ysben** [comment]
这个有开源代码吗？

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/tree/cookies

今天晚点会删掉这个分支

**Comment by ysben** [comment]
这个就是解决cookie问题的源代码？

**Comment by linweiyuan** [comment]
对

**Comment by ysben** [comment]
那删除了分支，还能访问到 https://get-chatgpt-cookies.linweiyuan.com/sse 这个来获取cookie吗？

**Comment by linweiyuan** [comment]
域名会改个新的，后面的具体实现细节不公开

**Comment by ysben** [comment]
闭源？

**Comment by linweiyuan** [comment]
因为后面获取 cookie 的实现要用到我自己的账号或者 token

**Comment by ysben** [comment]
这样别人不就用了你的信息？

**Comment by linweiyuan** [comment]
Cloudflare 说只有它能解密 cookie

**Comment by ysben** [comment]
如果我对接了你以后闭源的接口，这样不就是在用着你的账号？

**Comment by linweiyuan** [comment]
不看 cookie，看 token

**Comment by ysben** [comment]
这个cookie不是openai那边吧？

**Comment by linweiyuan** [comment]
https://developers.cloudflare.com/fundamentals/get-started/reference/cloudflare-cookies/

如果你觉得闭源的不安全，那么你可以自己删掉这些代码打包

**Comment by ysben** [comment]
我是想多学习参考一下哈，而且也会担心项目在运行过程中对接接口的话掉了不知道

**Comment by linweiyuan** [comment]
运行过程中断开会尝试重连

现在就有人不知道在测试什么连上来固定每分钟，每几分钟断开一次

所以我要改域名

**Comment by linweiyuan** [comment]
每 20 秒

**Comment by linweiyuan** [comment]
并且要加验证防止滥用，加验证细节不能公开，不然又滥用

**Comment by ysben** [comment]
期待新版，打算什么时候换呢？

**Comment by linweiyuan** [comment]
新版只是改链接，其他功能没有变化，现在的链接指向的就是新版 cookie api

**Comment by ysben** [comment]
到时候可以分享一下本地可以搭建的代码吗？

**Comment by linweiyuan** [comment]
不明白你说的分享什么

如果本地搭 cookie 服务，那么 cookie 分支就是

本地搭拿到的 cookie 无效

**Comment by ysben** [comment]
那需要部署到哪里可以呢？

**Comment by linweiyuan** [comment]
既然如此，那为什么不直接用旧版基于浏览器的版本呢

这个 cookie 服务要跑浏览器在后台

不是闲的吗

**Comment by linweiyuan** [comment]
说白了这个 cookie 服务就是在旧版基于浏览器的基础上，加了个获取当前浏览器 cookie 的接口

**Comment by ysben** [comment]
你新的接口也是这方式？

**Comment by linweiyuan** [comment]
对

**Comment by ysben** [comment]
浏览器上面的cookie是用你自己的openai账号获取到，当其他人访问 https://get-chatgpt-cookies.linweiyuan.com/sse 这个接口就会获取到你返回的cookie，但是openai不会去识别cookie只会识别token，可以这样理解吗？

**Comment by linweiyuan** [comment]
目前拿到的的 cookie，并没有登录，后面不能用了，再考虑登录获取

cookie 不对会 403，token 不对会 401

**Comment by ysben** [comment]
我很好奇，如果登录用的cookie，那这个登录是登录哪里的呢？是openai的接口？

**Comment by linweiyuan** [comment]
登录 ChatGPT

这只是一个构想

你可以带着你的疑问去把代码跑一遍，应该会解答很多

**Comment by ysben** [comment]
好的，感谢大佬指点
