### ISSUE TITLE
新版问题

### ISSUE THREAD

**Issue by hncboy** [linweiyuan/go-chatgpt-api#111]
我先试了新版，好像不支持流式输出，数据都是一起返回的。
旧版的部署方式在 README 里好像没有了，我在以往 issue 里找到了部署成功了，旧版支持流式输出。

**Comment by linweiyuan** [comment]
感觉是配置不对，是支持的

**Comment by xiaoguaishou92** [comment]
新版的403，用旧版的正常。。
