### ISSUE TITLE
新版的直接403，老版本的反而没问题

### ISSUE THREAD

**Issue by xiaoguaishou92** [linweiyuan/go-chatgpt-api#114]
![image](https://user-images.githubusercontent.com/20310407/236747743-db5f0674-43fd-49ef-b49f-7bcd64e8d6c1.png)

**Comment by meixiaofei** [comment]
should add prefix ```/chatgpt```

**Comment by linweiyuan** [comment]
重新拉镜像，如果还不行，用回旧版或者换其他替代品

**Comment by linweiyuan** [comment]
一般不用看 warp 的日志，国内服务器不行

**Comment by xiaoguaishou92** [comment]
哈哈，又重新了拉了两个小时的前的版本。。暂时可以了。看到大佬些的红色提示了。我自己关了吧

**Comment by linweiyuan** [comment]
你加我微信远程看或者发服务器信息给我登录进去看，我不会乱搞
