### ISSUE TITLE
这个项目可以代理官方api吗

### ISSUE THREAD

**Issue by Passerby1011** [linweiyuan/go-chatgpt-api#116]
如题这个项目可以代理官方api达到国内直连的效果吗？服务器可以访问chatgpt，无网络问题，国内可以直连服务器

**Comment by linweiyuan** [comment]
官方 API 指的是用 apiKey？

**Comment by Passerby1011** [comment]
是的

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/blob/main/README_zh.md#platform-apis
