### ISSUE TITLE
我在家宽部署这个项目chatgpt提示 reason: socket hang up

### ISSUE THREAD

**Issue by maxage** [linweiyuan/go-chatgpt-api#120]
1、家宽，openclash设置了策略分流，能够正常访问chat.openai.com
2、部署  go-chatgpt-api日志提示
INFO[0000] GO_CHATGPT_API_PROXY: http://10.0.0.10:1080 
INFO[0000] Welcome to ChatGPT  

3、
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api:latest
    ports:
      - 3080:8080
    environment:
      - GO_CHATGPT_API_PROXY=http://10.0.0.10:1080（代理能够正常访问chat.openai.com）
  
4、反代配置
![](https://oss.blog.nasvip.net/blog/20230511174517.png)

5、提示错误

![](https://oss.blog.nasvip.net/blog/20230511174558.png)

6、chat.openai.com能够正常访问
![](https://oss.blog.nasvip.net/blog/20230511174639.png)

**Comment by linweiyuan** [comment]
两个 docker 服务不在同一个网络，换成 IP+3080
