### ISSUE TITLE
id的作用

### ISSUE THREAD

**Issue by 233zq** [linweiyuan/go-chatgpt-api#121]
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/113227651/ba2951fd-85b5-4a9c-b6bb-3d4ed90b7e4d)
这三个id分别是什么，我如果把access_token当api需要知道这个三个id，不然无法请求

**Comment by 233zq** [comment]
如何获取第二个id

**Comment by 233zq** [comment]
第一个是随机生成，第二和第三一直不变可以吗？

**Comment by linweiyuan** [comment]
第三个是一直不变的，第二个在响应中，每条 `SSE` 数据都会返回

（官网是这样处理，至于你问可不可以，没试过，就算可以，也会有奇怪的问题）
