### ISSUE TITLE
why the cookie got from undetected driver can not be used in the project?

### ISSUE THREAD

**Issue by xixixi2000** [linweiyuan/go-chatgpt-api#122]
for the sse link sometimes did not return a useful __cf_bm id, so I want to get one from the undetected driver, but I found that the __cf_bm cookie I got from undetected drvier can only be used in legacy mode, if I used it in main mode, the server returns 403, can u try me why ? is it the problem of browser version or finger print ? I saw that the browser version is both 112

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/discussions/115

**Comment by xixixi2000** [comment]
the __cf_bm i got from undetected driver can be used normally, but only in legacy mode, not main mode :( and I also tried to get the __cf_bm cookie from the real working browser and use it in main mode, failed and get 403 :(

INFO[198025] [2023-05-13 08:16:47] Refresh Cookie: __cf_bm=PgJeGE.i9z7Wl_qdOQyuZE80SRC43HeSz7SQ8_DucTs-1683937007-0-AezYYzFa8q8mOYgDoRi4z8m41wVD97fXJNoZUyoWm1nP84/KSmk6Ujx+FaFkOiwp3v8TXWhWj3Cg9VzT1V+2m3zR422H9wEZ8BBy9FnPV5NDt1kiATKCLZlasolvanH93T6oKQqKoFIir9YdmWzKmaw=
[GIN] 2023/05/13 - 08:28:55 | 200 |  353.709723ms |       127.0.0.1 | GET      "/models"
[GIN] 2023/05/13 - 08:30:37 | 200 |  244.435245ms |       127.0.0.1 | GET      "/models"

and the cookie u supplied can be used in main mode, any difference between them?

**Comment by linweiyuan** [comment]
There's some fine-tuning in my cookies api to make sure the cookie is valid, but I will not show detail unless it is not working anymore, to avoid being detected.

**Comment by xixixi2000** [comment]
ok, but the cookie from legacy mode or from a real browser is invalid ? And I also found that you didn't need to offer the __cf_bm cookie all the time, the client can get it's own cookie via the Set-Cookie tag every 15 mins

**Comment by linweiyuan** [comment]
The __cf_bm will be sent to go-chatgpt-api every 25 minutes, other time only the ping event is sent to keep a long connection.

**Comment by xixixi2000** [comment]
yes, I mean that a user only need to get once when the daemon starts

**Comment by linweiyuan** [comment]
Have you tried?

The cookie will be expired after 30 minutes, if this works, why do I need to keep sending latest cookies.

- Cookie is expired: 403.
- Cookie is not set: 403.

**Comment by xixixi2000** [comment]
> Have you tried?
> 
> The cookie will be expired after 30 minutes, if this works, why do I need to keep sending latest cookies.
> 
> * Cookie is expired: 403.
> * Cookie is not set: 403.

yes，i make a loop to open the session page or check page to get the cookie reset

**Comment by linweiyuan** [comment]
Don't get it.

**Comment by xixixi2000** [comment]
> Don't get it.

wait a moment, I show you ...

**Comment by xixixi2000** [comment]
__cf_bm=GQz_igKREWx1dXow985pmY1m6rgeLADQ_4ZkRcNaGGo-1683985550-0-Ab6krXtAxYeP4g6H6V5G0yIzXP9RmaATgF7y5NIBT1abA93m0cvSmAF9AMSe83THyp9x4Hx2rnqf11WY19z2AuPleXgZj/Teyi63PW3PtR7s4ptympV9aXfANmSPAwl6duSSnyuOn381TCkE6vvegis=
INFO[0000] [2023-05-13 21:46:11] Welcome to ChatGPT
INFO[0001] [2023-05-13 21:46:12] Set-cookie: _cfuvid=vlxg5UVSKjlR04MJz4Z1dqTmo2ayvp0c3_liVUukY.w-1683985572123-0-604800000
[GIN] 2023/05/13 - 21:47:34 | 200 |   191.15749ms |       127.0.0.1 | GET      "/chatgpt/models"
INFO[0902] [2023-05-13 22:01:13] Renew: __cf_bm=vfjezdKI4a_UsybyMrPw_m_HR6rfqiBeLpC8rg_dm9o-1683986473-0-AfUssgUP0toqeHTBq103aDhnWguFC6uI53zaJM90QviY/PnE6l7TfXoapTKuALSSpThTtFu4YlezQTt/bNN7WRI/yuLZS4mO/AbiA9zWqRLysWR3m25zhjz6rH/KAPNCqULSymhHu3biR7/yF5tXd6o=

**Comment by linweiyuan** [comment]
If you run this code, will enter `if` or `else`?

https://github.com/linweiyuan/go-chatgpt-api/blob/main/api/common.go#L143-L155

**Comment by xixixi2000** [comment]
> If you run this code, will enter `if` or `else`?
> 
> https://github.com/linweiyuan/go-chatgpt-api/blob/main/api/common.go#L143-L155

I need SSE once at the start and then use the cookie to get the renew, I show u the code

**Comment by xixixi2000** [comment]
u can try the __cf_bm cookie below after renew, it works, but the code above contains bugs, sometimes hung in the Client.do, I just show the way

INFO[0902] [2023-05-13 22:01:13] Renew: __cf_bm=vfjezdKI4a_UsybyMrPw_m_HR6rfqiBeLpC8rg_dm9o-1683986473-0-AfUssgUP0toqeHTBq103aDhnWguFC6uI53zaJM90QviY/PnE6l7TfXoapTKuALSSpThTtFu4YlezQTt/bNN7WRI/yuLZS4mO/AbiA9zWqRLysWR3m25zhjz6rH/KAPNCqULSymhHu3biR7/yF5tXd6o=
[GIN] 2023/05/13 - 22:14:17 | 200 |  260.975859ms |       127.0.0.1 | GET      "/chatgpt/models"
INFO[1803] [2023-05-13 22:16:14] Renew: __cf_bm=w_SU8QG_BvDoEAapWr7jpanVfCYQb9tXQX8zA.OQejU-1683987374-0-AfXNuuH8I2vOZ7Y8EC/Dxp6rV3cOsvEwiLWAXvCGZ+DDL0MX+1WPjU08DdfU8ABtPtCnMUX4OYMEOVmmDAsoJzasIaJoDzR9T9314Ti2A9TWOB8ivGxjR/slQTbLW4/AvPWu13ZgUYfGyiRiYTph+JU=
INFO[2705] [2023-05-13 22:31:16] Renew: __cf_bm=12JF6wpsc4dQDgv9Iutg6H.sa9O6O.VztZ2rAa96A0A-1683988276-0-AdpGwmve5/OHkSxw/OIZkG7iAjIAL3BNiBTVIIAJf7M/LIRxDcYiCMP6M6XJJO61P456nXCu0rDDtpvyQ++27QbKyB8NTImxaqi8cHcWB6nNvjHg3QTBAq+g7FSzj5C5LO1NFzTbq0lINLipohVhxzw=
INFO[3606] [2023-05-13 22:46:17] Renew: __cf_bm=JoFXUP5XzdRFuqtr.x7uST3qJj0RxWQwnqWccKfo2Ro-1683989177-0-AVAbZXPo9ZVGcm56E9UUTnyK4b4vGNZVHyquIAhKh4et7/WTUTokQLTqXv14SMyuVbY2mGZjrjC63VmRKr+NRap10uzR2p0RkFcaSW5KoXJafR9/9OUlCHbMygwu+cmwp4UM0YDN322Q0KVm2l0ZTcg=
INFO[4508] [2023-05-13 23:01:19] Renew: __cf_bm=viAWNQCB92h6gt21DeEVtyZn5nU0ZIiqRGHO_.9.Smc-1683990079-0-AVk4UXlYbnVeTFDqIUI4/CCwOFU3byRam7lCIpkhDhtNgrgHQzfC5Qslu/G1teoh76ZKYQ3KjNdbc4ZxLEdK+RbqEnppzkgeCcqnKb0GZzUaC3UGZqXzyvFXmfO0YGNsdCU3RmfY/4y32TzFpVhEDG0=
[GIN] 2023/05/13 - 23:05:15 | 200 |  182.617023ms |       127.0.0.1 | GET      "/chatgpt/models"

**Comment by linweiyuan** [comment]
Looks like it actually works.

**Comment by xixixi2000** [comment]
> Looks like it actually works.

yes, but I don't know why the process hung on the client.do after running a period of time

**Comment by linweiyuan** [comment]
How did you find out 15 minutes?

**Comment by xixixi2000** [comment]
> How did you find out 15 minutes?

after 15 min, the cookie will regen and return ... so, from 15 - 30 min, we can use the old cookie to gen a new one
