### ISSUE TITLE
/conversation能正常使用，/login就是403

### ISSUE THREAD

**Issue by Jxells** [linweiyuan/go-chatgpt-api#123]
如题,可能是什么原因引起了呢。

**Comment by linweiyuan** [comment]
什么版本

程序启动时输出什么

**Comment by Jxells** [comment]
> 什么版本
> 
> 程序启动时输出什么

![image](https://github.com/linweiyuan/go-chatgpt-api/assets/94813798/ee293261-cc6f-4dbe-881f-9b97dc9f8d84)

**Comment by linweiyuan** [comment]
403 返回什么错误信息，`Failed to get CFRS token.` ?

**Comment by Jxells** [comment]
> 403 返回什么错误信息，`Failed to get CFRS token.` ?

![image](https://github.com/linweiyuan/go-chatgpt-api/assets/94813798/0331fbba-5dfd-4db6-86b8-4dac566be284)

**Comment by linweiyuan** [comment]
重启一下 API，再不行的话，如果有其他节点可用换个节点

或者方便的话提供你的节点给我测试下，我这边无法复现

`linweiyuan/go-chatgpt-api         latest    b6f563f25fd6   3 days ago      18.7MB`

![2023-05-13_11-13](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/771030f4-f45c-48ef-bd20-2fc83a21e07d)
