### ISSUE TITLE
response with invalid json format

### ISSUE THREAD

**Issue by waltcow** [linweiyuan/go-chatgpt-api#126]
chatgpt/conversation post api response with invalid json format

![image](https://github.com/linweiyuan/go-chatgpt-api/assets/3941174/fc75dd65-8f7f-4a99-b452-b5436cbeb70a)

![image](https://github.com/linweiyuan/go-chatgpt-api/assets/3941174/53d6e6ad-d485-40e6-a08e-db4d09fdb63a)

**Comment by linweiyuan** [comment]
Google SSE (Server Sent Events)

**Comment by waltcow** [comment]
en, it seems that you forget to set response type 

```go
	c.Header("Content-Type", "text/event-stream")
```

**Comment by waltcow** [comment]
My current usage is use it as backend server for https://github.com/pengzhile/pandora-cloud

Content-Type header missing will lead to the official frontend not working properly
