### ISSUE TITLE
429 error - Rate limited by IP

### ISSUE THREAD

**Issue by acheong08** [linweiyuan/go-chatgpt-api#127]
How do you resolve this? I have 300 accounts but the proxy itself gets rate limited at some point.

**Comment by linweiyuan** [comment]
If we want to resolve this issue, the first step is to set up a functional proxy pool.

**Comment by acheong08** [comment]
That's what I'm doing at the moment. Is there no way to get around this issue? Someone mentioned that there is a cookie used by cloudflare to differentiate between multiple people using the same IP but idk if OpenAI applies it

**Comment by linweiyuan** [comment]
Looks like this one? Not sure, need to test, but I only have one account.

https://developers.cloudflare.com/fundamentals/get-started/reference/cloudflare-cookies/#_cfuvid-for-rate-limiting-rules

**Comment by acheong08** [comment]
It seems to be pure IP rate limits. afaik @pengzhile uses an alternative endpoint similar to chat.apps.openai.com that was used previously

**Comment by acheong08** [comment]
@linweiyuan The trick is PUID again. It bypasses the Cloudflare rate limits

**Comment by linweiyuan** [comment]
Plus user only?

**Comment by Jxells** [comment]
有相同的问题

**Comment by Passerby1011** [comment]
请问该如何解决

**Comment by linweiyuan** [comment]
参考项目 compose 配置文件，设置 plus 账号密码

**Comment by Passerby1011** [comment]
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/63802758/bfd38573-c071-436f-9566-b86b1582355a)
只需要，添加一个plus账户就可以了？

**Comment by linweiyuan** [comment]
其实你试试不就知道了
