### ISSUE TITLE
关于teams-enroll-token

### ISSUE THREAD

**Issue by nbMars1980** [linweiyuan/go-chatgpt-api#128]
大佬，如果想使用自己的teams-enroll-token，环境变量TEAMS_ENROLL_TOKEN的值是怎样的格式可以给个说明吗？

**Comment by linweiyuan** [comment]
全部，需要在一分钟内复制，粘贴，启动程序，不然会过期

据我测试，说是无限流量，但是超过 1G 后，经常连不上（不知道是不是我用法不对），所以最新的 `warp` 镜像我改成了超过 1G 流量重新注册，这个变量似乎没用了

![2023-05-17_11-44](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/b8b582d8-281a-4ebb-aeb4-be709cfa2243)

**Comment by nbMars1980** [comment]
前面的com.cloudflare.warp://nbmars.cloudflareaccess.com/auth?token= 也要一起复制过去吗？我在界面按钮文本变为Authentication Expired之前docker已启动完成，但是仍然是连不上，logs里全部显示
2023/05/17 04:12:57 socat[138] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused

**Comment by nbMars1980** [comment]
cloudflare后台Devices显示设备已登录成功，但是链接状态是Disconnected

**Comment by linweiyuan** [comment]
前面的也要，全部

刚才有 bug，修复了，拉下新镜像试试

**Comment by linweiyuan** [comment]
`docker-compose exec chatgpt-proxy-server-warp warp-cli --accept-tos account | awk 'NR==1'`

**Comment by nbMars1980** [comment]
> `docker-compose exec chatgpt-proxy-server-warp warp-cli --accept-tos account | awk 'NR==1'`
返回 Account type: Team，这说明注册成功了。但是仍然无法连接socks
docker-compose logs 全部是
socat[375] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused

**Comment by linweiyuan** [comment]
- `docker-compose exec chatgpt-proxy-server-warp warp-cli --accept-tos status`

- `docker-compose exec chatgpt-proxy-server-warp warp-cli --accept-tos warp-stats`

- `docker-compose exec chatgpt-proxy-server-warp curl -x socks5://127.0.0.1:40000 ipinfo.io`

**Comment by linweiyuan** [comment]
如果不设置，能正常返回 `Free` 账号吗？

**Comment by nbMars1980** [comment]
docker-compose exec chatgpt-proxy-server-warp warp-cli --accept-tos status
返回Success

docker-compose exec chatgpt-proxy-server-warp warp-cli --accept-tos warp-stats
返回Error: WARP is not connected.

docker-compose exec chatgpt-proxy-server-warp curl -x socks5://127.0.0.1:40000 ipinfo.io
返回curl: (7) Failed to connect to 127.0.0.1 port 40000 after 0 ms: Couldn't connect to server

今天上午开始如果不设置，也是连不上，同样是socat[375] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused，而且CPU占用100%

**Comment by nbMars1980** [comment]
> 如果不设置，能正常返回 `Free` 账号吗？

现在不设置可以正常使用，返回的是free

**Comment by linweiyuan** [comment]
连不上因为免费 1G 流量超了

是不是没有更新镜像？

用的是浏览器老版本？

**Comment by nbMars1980** [comment]
> 连不上因为免费 1G 流量超了
> 
> 是不是没有更新镜像？
> 
> 用的是浏览器老版本？

是的，更新了之后免费的就可以了。

**Comment by linweiyuan** [comment]
`ced254380b8c` 这个镜像 ID 是最新的，我测试 `Team` 账号也正常

如果设置 `LOG_LEVEL=DEBUG` 或者 `LOG_LEVEL=INFO` 返回什么错误？

不能 `restart`，要先 `down` 再 `up`
