### ISSUE TITLE
some bugs found in health_check

### ISSUE THREAD

**Issue by xixixi2000** [linweiyuan/go-chatgpt-api#133]
1. If not set timeout, sometimes the connection hungs, ( after 1 or 2 days run, and will got timeout after setting the timeout )
   2. the connection of healthCheck lacks of close , and the err should be deal with
   3. sometimes the connection from the connection pool of healthCheck is bad (after 2 or 3 days run), and cannot connect to the server, the pool should be reset?  will get [ net/http: request canceled (Client.Timeout exceeded while awaiting headers) ...... continiously if setting timeout, will get hung if not set timeout]

``
        Client, _ = tls_client.NewHttpClient(tls_client.NewNoopLogger(), []tls_client.HttpClientOption{
                tls_client.WithCookieJar(tls_client.NewCookieJar()),
                tls_client.WithTimeoutSeconds(0),
        }...)

                                        go func() {
                                                for {
                                                        time.Sleep(time.Minute * 25)
                                                        resp, _ := healthCheck()
                                                        for _, cookie := range resp.Cookies() {
                                                                if cookie.Name == cookieName {
                                                                        cfbm = &Cookie{
                                                                                Name:  cookie.Name,
                                                                                Value: cookie.Value,
                                                                        }
                                                                }
                                                        }
                                                }
                                        }()

``

**Comment by linweiyuan** [comment]
PR is welcomed.

**Comment by xixixi2000** [comment]
Already up to date?
