### ISSUE TITLE
You have been blocked to use cookies api because your IP is detected by Cloudflare WAF. 

### ISSUE THREAD

**Issue by Corson011** [linweiyuan/go-chatgpt-api#134]
美国阿里云服务器，换了十个ip，
一直都是提示You have been blocked to use cookies api because your IP is detected by Cloudflare WAF. 
应该怎么处理

**Comment by linweiyuan** [comment]
这个是自动挡掉的，可能套路云全部被挡了

最新的 IP 是多少，我给你加个白名单

如果发这里敏感那单独发我邮箱：`root@linweiyuan.com`

---

同价格不是国外 VPS 更香？

**Comment by lvmingliang** [comment]
20.78.235.36

**Comment by lvmingliang** [comment]
已发送邮箱，谢谢

**Comment by superen7527** [comment]
你的邮箱是自己搭建的吗。不会被拦截？

**Comment by linweiyuan** [comment]
使用多年至今正常

**Comment by superen7527** [comment]
> 使用多年至今正常

能给指个路吗？用的哪个项目？我用Outlook有一些还是拦截

**Comment by linweiyuan** [comment]
基本有点规模的云服务商都有提供域名邮箱服务

他们有规则可以配置用来过滤垃圾邮件

至于你说 Outlook，如果你说客户端我用 Thunderbird

![Uploading Screenshot_2023-05-24-18-24-52-196_mark.via.jpg …]()

**Comment by superen7527** [comment]
我指的是smtp那些，用gmail或者Outlook很容易进垃圾箱，你是送信是怎么哪家的？

**Comment by linweiyuan** [comment]
Yandex

进垃圾箱和 Gmail 或 Outlok 有什么关系？

有时 GitHub 发的 issue 或 action 邮件也会进垃圾箱

**Comment by superen7527** [comment]
和这个还是有关系的，我还不知道具体在哪。同一个邮箱html体 有的gmail发送会拦截 Outlook发的不会拦截 有一些反过来 。而且不同账号发送同一个邮件也有不同结果有的账号拦截有的不拦截 都是新号注册来实验的。可能不同账号安全权重也不同

**Comment by Cloudy-Kumori** [comment]
你好，想问一下这个blocked提示的原理是什么？我自己用那个IP代理后访问chat.openai.com是不会弹验证码和blocked的，只能发邮件告知IP解ban吗

**Comment by linweiyuan** [comment]
@Cloudy-Kumori 

原理就是我这个域名解析也是配置在 `Cloudflare` 并且开了 `Bot Fight Mode`，那么某些请求就会自动被 `WAF` 挡掉（这个是 `Cloudflare` 挡，此时请求不会去到我的服务器，而白名单优先级高）

如果你怕告知我 `IP` 后有风险，那么我告诉你，被挡住的 `IP` 也会有记录，就是我可以从后台看到什么 `IP` 被挡了，同时配置白名单后我可以看到什么 `IP` 什么时候调用了接口，但是，我不会主动去扫描它，也就是说，发生风险自负，但是总是与我无关

这个 `block`，和不能直接访问 `ChatGPT`，要通过 `go-chatgpt-api` 或者其他绕过程序，某种程度上来说差不多

- 通过 `go-chatgpt-api` 才能访问，不然 403
- 通过白名单才能拿到 `cookie`，不然 403

再次强调，这个是 `Cloudflare` 自动挡掉某些云服务器和不干净的 `IP`，并不是我有意为之，我只是开启了反爬虫

**Comment by superen7527** [comment]
你们在讨论什么？这不是自己搭建的吗？为什么会经过作者的cf，你们说的是warp模式?

**Comment by Cloudy-Kumori** [comment]
@linweiyuan 感谢回答，也就是说为了防止不干净的IP访问ChatGPT API导致直接封号，您的程序在正式建立连接到OpenAI的服务器之前，预先使用了自建的cloudflare防护墙检测了一下IP是否有问题是吗？如果有问题则直接放弃连接ChatGPT的api服务并报错blocked，如果没问题再进行下一步连接。这个是否会存在预判的风险呢，也就是像我现在这样直接用服务器IP进行代理访问不会弹验证码和blocked，但是在上面部署服务会提示blocked，这种情况能不能通过发送IP给您加白名单然后解锁访问权限？

**Comment by linweiyuan** [comment]
不是，这个不是用来防封号的，是用来绕过 403 的

首先，一开始我这个公益的 `cookie` 服务在互联网上裸奔，然后被别人攻击了，因为这个是基于浏览器的，就算访问一次内存和 `CPU` 占用都会不低，那么一秒几百个请求，我的服务器就挂了，所以后面为了防止别人滥用或者攻击我的服务器，加了 `Cloudflare` 的防护：https://linweiyuan.github.io/2023/05/03/%E6%96%B0%E7%89%88%E6%9C%AC-go-chatgpt-api.html

然后，部分节点启动 `go-chatgpt-api` 会直接提示绿字（多是住宅节点，不全是），意味着 `ChatGPT` 认为这种 `IP` 是干净的，这种不会经过我服务器，因为 `go-chatgpt-api` 拿到的 `cookie` 已经是合法的了；部分节点启动后会提示红字（多是服务器节点，不全是），意味着 `ChatGPT` 认为这种 `IP` 有风险，那么 `go-chatgpt-api` 拿到的 `cookie` 就会不合法，这个时候就会调用一次我的 `cookie` 服务，这个服务就会提供合法的的 `cookie`，不然的话，`ChatGPT` 会返回 403：https://github.com/linweiyuan/go-chatgpt-api/blob/main/api/chatgpt/health_check.go#L69-L85

最后，会误判，据我所知阿里云、`Azure` 和部分 `Oracle` 节点，默认就会被挡，所以有白名单机制

你的情况发一下 `IP` 就好了

**Comment by Cloudy-Kumori** [comment]
@linweiyuan 好的，我还以为这是什么防封保护机制然后研究了好久，谢谢解答☺️

**Comment by itcuihao** [comment]
> 不是，这个不是用来防封号的，是用来绕过 403 的
> 
> 首先，一开始我这个公益的 `cookie` 服务在互联网上裸奔，然后被别人攻击了，因为这个是基于浏览器的，就算访问一次内存和 `CPU` 占用都会不低，那么一秒几百个请求，我的服务器就挂了，所以后面为了防止别人滥用或者攻击我的服务器，加了 `Cloudflare` 的防护：https://linweiyuan.github.io/2023/05/03/%E6%96%B0%E7%89%88%E6%9C%AC-go-chatgpt-api.html
> 
> 然后，部分节点启动 `go-chatgpt-api` 会直接提示绿字（多是住宅节点，不全是），意味着 `ChatGPT` 认为这种 `IP` 是干净的，这种不会经过我服务器，因为 `go-chatgpt-api` 拿到的 `cookie` 已经是合法的了；部分节点启动后会提示红字（多是服务器节点，不全是），意味着 `ChatGPT` 认为这种 `IP` 有风险，那么 `go-chatgpt-api` 拿到的 `cookie` 就会不合法，这个时候就会调用一次我的 `cookie` 服务，这个服务就会提供合法的的 `cookie`，不然的话，`ChatGPT` 会返回 403：https://github.com/linweiyuan/go-chatgpt-api/blob/main/api/chatgpt/health_check.go#L69-L85
> 
> 最后，会误判，据我所知阿里云、`Azure` 和部分 `Oracle` 节点，默认就会被挡，所以有白名单机制
> 
> 你的情况发一下 `IP` 就好了

今天发现服务内403 了，看 log 有错误信息

```
INFO[0000] GO_CHATGPT_API_PROXY: socks5://chatgpt-proxy-server-warp:65535
ERRO[0000] Failed to get cookies, please try again later.
```
是否是因为我的 ip问题，而且我看账号中 api-key 恰好今天过期，不知道是否有联系

**Comment by linweiyuan** [comment]
更新
