### ISSUE TITLE
被ban

### ISSUE THREAD

**Issue by lvmingliang** [linweiyuan/go-chatgpt-api#136]
You have been blocked to use cookies api because your IP is detected by Cloudflare WAF
这个是什么情况？

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/issues/134

**Comment by linweiyuan** [comment]
已加

**Comment by lvmingliang** [comment]
谢谢兄


在 2023年5月19日 ***@***.***> 写道：


已加
