### ISSUE TITLE
这两次get请求正常吗？是不是被扫了

### ISSUE THREAD

**Issue by 1715819** [linweiyuan/go-chatgpt-api#14]
![photo_〉〇〉《-〇》-〈〇_〈〉-〉〉-》〉](https://user-images.githubusercontent.com/75056973/230825668-1d840a52-a0ef-44e4-aa5c-f3177d0c40c5.jpg)

**Comment by linweiyuan** [comment]
参考这个：https://github.com/linweiyuan/go-chatgpt-api/issues/10
