### ISSUE TITLE
Sorry, you have been blocked by OpenAI

### ISSUE THREAD

**Issue by thugbobby** [linweiyuan/go-chatgpt-api#140]
运行新版的docker容器哦时，报这个错误Sorry, you have been blocked by OpenAI
请问是什么问题，VPS是美服

**Comment by linweiyuan** [comment]
简单来说

![2023-05-30_22-17](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/51e0bd6d-2513-4e7e-9442-4a0e131acc2c)
