### ISSUE TITLE
docker运行， 每隔一分钟就报错退出

### ISSUE THREAD

**Issue by zzt888** [linweiyuan/go-chatgpt-api#142]
<img width="555" alt="image" src="https://github.com/linweiyuan/go-chatgpt-api/assets/12008066/c73e492a-6612-45f1-ac58-fccadd4b812c">

**Comment by zzt888** [comment]
版本是最新的。 刚好一分钟这个容器就自动报错重启

**Comment by linweiyuan** [comment]
最新的是 `latest` 镜像，请参考中文文档

`legacy` 不再更新和修复

**Comment by zzt888** [comment]
是的， 刚弄的yaml， version: '3'

services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GO_CHATGPT_API_PROXY=
    restart: unless-stopped
    
    
    
    加了wrap也是这个问题。   所以才有点不懂， 请教下。

**Comment by linweiyuan** [comment]
`docker pull linweiyuan/go-chatgpt-api`

**Comment by linweiyuan** [comment]
或者删除这个本地镜像，然后重新启动

为什么一眼看出问题，因为在现在的代码里，这个报错 `refresh.go`，根本就没有这个文件，N 年前已经删掉了

**Comment by zzt888** [comment]
现在没问题了 ， You have been blocked to use cookies api because your IP is detected by Cloudflare WAF.   IP已经没救了 ，谢谢🙏

**Comment by zzt888** [comment]
已发送， 万分感谢🙏
