### ISSUE TITLE
docker运行加了一个warp，报如下错误

### ISSUE THREAD

**Issue by thugbobby** [linweiyuan/go-chatgpt-api#143]
<img width="1489" alt="image" src="https://github.com/linweiyuan/go-chatgpt-api/assets/68416779/4aa3bee3-4a86-4d83-9068-df8ae3401c58">
如图

**Comment by linweiyuan** [comment]
供参考：https://github.com/linweiyuan/go-chatgpt-api/issues/31

哪里来的镜像，没见过这个 `Rust` 的报错

**Comment by thugbobby** [comment]
镜像是linweiyuan/chatgpt-proxy-server，问题已解决，端口配置问题。
