### ISSUE TITLE
打不开页面，提示[DEBUG]: DevTools WebSocket Event: Log.entryAdded

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [linweiyuan/go-chatgpt-api#153]
yml文件如下

version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      OPENAI_API_KEY:
      # 二选一
      OPENAI_ACCESS_TOKEN: "我的TOKEN"
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL:
      # API模型，可选，设置 OPENAI_API_KEY 时可用，https://platform.openai.com/docs/models
      # gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, code-davinci-002
      OPENAI_API_MODEL:
      # 反向代理，可选
      API_REVERSE_PROXY: "http://go-chatgpt-api:8080/conversation"
      # 访问权限密钥，可选
      AUTH_SECRET_KEY:
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      SOCKS_PROXY_HOST:
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      SOCKS_PROXY_PORT:
      # HTTPS 代理，可选，支持 http，https，socks5
      HTTPS_PROXY:
    depends_on:
      - go-chatgpt-api

  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
#      - NETWORK_PROXY_SERVER=http://host:port
#      - NETWORK_PROXY_SERVER=socks5://host:port
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

docker创建正常，但是访问我美国VPS的IP：3002却直接打不开网页。查看日志，在linweiyuan/chatgpt-proxy-server镜像生成的容器中，有提示[DEBUG]: DevTools WebSocket Event: Log.entryAdded (session_id=2F3B1E2F3E63B343B13FBC0FEA251D0B) FF33431F166A9B26A8757A82E0F8948D {
   "entry": {
      "level": "error",
      "networkRequestId": "81.327",
      "source": "network",
      "text": "Failed to load resource: the server responded with a status of 429 ()",
      "timestamp": 1.685933163268604e+12,
      "url": "https://o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.50.0"
   }
}
不明所以，望指正~~

**Comment by linweiyuan** [comment]
看文档用最新的配置

**Comment by GitHubChrisChen8035** [comment]
查看代码中的compose.yml文件，最新的配置是这样的吗：

go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
      - GO_CHATGPT_API_PROXY=http://chatgpt-proxy-server:9515
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped


chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

另外，直接pull最新的linweiyuan/chatgpt-proxy-server:lastest，提示Error response from daemon: pull access denied for linweiyuan/chatgpt-proxy-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/blob/main/README.md

是看这个？
