### ISSUE TITLE
本项目是正向还是反向代理？

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [linweiyuan/go-chatgpt-api#158]
作者README中写着“正向代理”，但其他chatgpt-web项目将本项目作为proxy后，就成了“反向代理”？
我的粗浅理解：chatgpt-web项目为避免IP被封或其他原因，配置proxy访问openai，对于chatgpt-web本身来说，属于正向代理。但对于访问chatgpt-web项目的客户端来讲，原本是通过vps.ip:port进行会话，但因为端口监听，实质上是通过proxy进行会话，从这个角度来看，chatgpt-web项目确实起到了“反代”作用。不知道理解是否正确？？

另外，YML文件中，GO_CHATGPT_API_PROXY是什么作用，代理的代理？

**Comment by linweiyuan** [comment]
第一个问题，通过代理出去，正向，通过代理进来，反向，不要纠结这个

第二个问题，就像你本身访问官网需要魔法一样------------------------------------------------------------------
***@***.***>
日　期：2023年06月07日 09:56:36
***@***.***>
***@***.***>
主　题：[linweiyuan/go-chatgpt-api] 本项目是正向还是反向代理？ (Issue #158)

作者README中写着“正向代理”，但其他chatgpt-web项目将本项目作为proxy后，就成了“反向代理”？
 我的粗浅理解：chatgpt-web项目为避免IP被封或其他原因，配置proxy访问openai，对于chatgpt-web本身来说，属于正向代理。但对于访问chatgpt-web项目的客户端来讲，原本是通过vps.ip:port进行会话，但因为端口监听，实质上是通过proxy进行会话，从这个角度来看，chatgpt-web项目确实起到了“反代”作用。不知道理解是否正确？？
另外，YML文件中，GO_CHATGPT_API_PROXY是什么作用，代理的代理？

**Comment by GitHubChrisChen8035** [comment]
哈哈，作者回复真快！！
第一个问题已不纠结，第二个如果我本身是在境外VPS（可直接访问openai）上启用您的项目，那么不需要再设置GO_CHATGPT_API_PROXY，对吧？

**Comment by linweiyuan** [comment]
境外 VPS 大多已被封，如果不设置不会报错，完全不用设置

**Comment by GitHubChrisChen8035** [comment]
最后一个问题：如果VPS上即有chatgpt-web项目，也有go-chatgpt-api项目，好像无法规避将IP暴露给openai吧？不太懂为什么反向代理可以保护IP，既然通过某个IP与openai进行会话，那么这个IP就是高危IP，不知道这样理解对不对？

**Comment by linweiyuan** [comment]
老实说好多事情其实我自己的博客或者文档从来没说过，包括反向代理的叫法和保护 IP

OpenAI 封禁了一堆 VPS，这个 WARP 的作用是把 VPS 的 IP 某种程度上模拟成 Cloudflare 的 IP，起到伪装效果，住宅 IP 一般就不会封

**Comment by SimFG** [comment]
可以试试在huggingface部署这个项目

**Comment by GitHubChrisChen8035** [comment]
> 老实说好多事情其实我自己的博客或者文档从来没说过，包括反向代理的叫法和保护 IP
> 
> OpenAI 封禁了一堆 VPS，这个 WARP 的作用是把 VPS 的 IP 某种程度上模拟成 Cloudflare 的 IP，起到伪装效果，住宅 IP 一般就不会封

感谢详细解答，已经大致明白了！
