### ISSUE TITLE
想请教下是不是每次请求的时候都要加上accesstoken呀？一直报错这个错误

### ISSUE THREAD

**Issue by linxin6** [linweiyuan/go-chatgpt-api#162]
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/122243370/19cc7c19-3d41-494e-a063-3de64a7b5ce0)

**Comment by linweiyuan** [comment]
除了登录不用，其他接口都要

如果不理解你可以把它想象成回家要不要每次带钥匙

**Comment by linxin6** [comment]
明白了，感谢大佬，刚刚看到示例。

**Comment by linxin6** [comment]
刚刚又遇到一个问题。
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/122243370/6e6c3c5c-74a7-457c-a6b9-db9128caf92b)

**Comment by linxin6** [comment]
如果strem=false就会出现下面这个错误
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/122243370/fbc7faf2-13e2-426b-904d-8545eccf4ce0)

**Comment by linweiyuan** [comment]
ChatGPT 用 accessToken

官方 api 用apiKey

**Comment by linxin6** [comment]
ok
