### ISSUE TITLE
请教大佬原理！

### ISSUE THREAD

**Issue by dvc890** [linweiyuan/go-chatgpt-api#165]
我最近关注到贵项目已经升级成摆脱浏览器的束缚，直接api调用的形式，但是看了一下代码不是很理解是怎么绕过cf的，看着好像没有相关的处理呀？

**Comment by linweiyuan** [comment]
其实现在来说 go-chatgpt-api 已经没什么技术含量了，因为绕过是用的这个库：https://github.com/bogdanfinn/tls-client，详细的原理老实说我并不不懂，我只是负责调用，你可以谷歌一下 tls 欺骗或者 ja3 指纹的相关文章

简单来说就是把自己伪装成一个浏览器
