### ISSUE TITLE
Hi bro, the /platform/login hasn't worked as expectation

### ISSUE THREAD

**Issue by HuaTrung** [linweiyuan/go-chatgpt-api#166]
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/19803951/15826638-3915-45c4-9ecc-809966635713)
Hi, hope you're doing well. I'm running into this error.
Here is the log: 
{
    "errorMessage": "Failed to get authorized url."
}

Can you have a look at that? Thanks in advance.

**Comment by linweiyuan** [comment]
Works fine with my account.

The 429 looks like you have tried to login too many times?

Can you login successfully with this url? https://platform.openai.com/playground

![2023-06-16_00-34](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/00bb584b-5223-4a3e-acaf-e13b1246d84c)

**Comment by HuaTrung** [comment]
I tried and It has worked :D. It looks like I called too many times. Thanks for your support. Just let you know that this service is really helpful.
