### ISSUE TITLE
{"errorMessage":"Missing accessToken."}

### ISSUE THREAD

**Issue by huangwb8** [linweiyuan/go-chatgpt-api#17]
我搭建好后，直接访问`http://ip:8080`时会出现：

```
{"errorMessage":"Missing accessToken."}
```

请问README.md中是否有遗漏什么？完全按第一个docker-compose配置部署的。求解答。

谢谢大佬 (ฅ´ω`ฅ)

**Comment by linweiyuan** [comment]
正常的，没有遗漏了

因为这个项目只是提供了服务，`accessToken` 的话则需要自己账号获取：https://chat.openai.com/api/auth/session

直接访问没有带 `token`，那当然就失败了

**Comment by huangwb8** [comment]
那么，请问我搭建好了，是直接使用`http://ip:8080`吗？ 只要这个效果类似 `https://bypass.churchless.tech/api/conversation` 就行，因为我以前是可以用后者的（最近被封了）

**Comment by linweiyuan** [comment]
把配置改为这个就可以了，`http:/ip:8080/conversation`，试一下

**Comment by wwlmm** [comment]
果然有效果

**Comment by huangwb8** [comment]
不知道是不是VPS的IP问题，我使用的时候总是不稳。就算用了warp也不行

但另外一个小伙伴成功并且稳定地建了反代。 羡慕 Σ( ° △ °|||)︴

**Comment by linweiyuan** [comment]
确实不稳，只是勉强能用的程度，但安全，`token` 不经别人服务器

**Comment by benngai123** [comment]
> 正常的，没有遗漏了
> 
> 因为这个项目只是提供了服务，`accessToken` 的话则需要自己账号获取：https://chat.openai.com/api/auth/session
> 
> 直接访问没有带 `token`，那当然就失败了

请问是在哪里设置 accessToken，我直接重写了 GetAccessToken() 也不行

**Comment by huangwb8** [comment]
@benngai123

我一般是自建chatGPT服务，它们往往包含一个关于反向代理的参数，你将代理地址提供给它即可。 

我的博客文章有一个方案，感兴趣可以尝试： https://blognas.hwb0307.com/linux/docker/4201

**Comment by yayaQAQ** [comment]
> @benngai123
> 
> 我一般是自建chatGPT服务，它们往往包含一个关于反向代理的参数，你将代理地址提供给它即可。
> 
> 我的博客文章有一个方案，感兴趣可以尝试： https://blognas.hwb0307.com/linux/docker/4201

我也没有太懂，具体是在go-chatgpt-api这个项目的哪个地方放accessToken呢？我尝试直接修改代码，貌似不太行。

**Comment by linweiyuan** [comment]
@yayaQAQ `accessToken` 放在前端项目，`go-chatgpt-api` 这个项目只是做一个转发

你用的前端项目是哪一款，如果是 `chatgpt-web`，那就是配置 `OPENAI_ACCESS_TOKEN`

**Comment by yayaQAQ** [comment]
> @yayaQAQ `accessToken` 放在前端项目，`go-chatgpt-api` 这个项目只是做一个转发
> 
> 你用的前端项目是哪一款，如果是 `chatgpt-web`，那就是配置 `OPENAI_ACCESS_TOKEN`

我在调用的时候确实加入了accessToken，但是这个项目编译运行了之后，好像过一段时间会挂掉，我以为是由于accessToken缺失导致的。
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/20497531/232432163-a3b67c8d-a323-47f1-83c3-d7f75047b161.png">

**Comment by linweiyuan** [comment]
这个好办，参考这个：https://github.com/linweiyuan/go-chatgpt-api/issues/22

**Comment by yayaQAQ** [comment]
> 这个好办，参考这个：#22

怎么让chromedriver一直在后台运行呢？我把代码里面的Close()函数都关掉了，还是过一段时间会挂掉。

**Comment by linweiyuan** [comment]
你是苹果系统？

看看你是怎么跑的 chromedriver，是否有误

**Comment by huangwb8** [comment]
> > @benngai123
> > 我一般是自建chatGPT服务，它们往往包含一个关于反向代理的参数，你将代理地址提供给它即可。
> > 我的博客文章有一个方案，感兴趣可以尝试： https://blognas.hwb0307.com/linux/docker/4201
> 
> 我也没有太懂，具体是在go-chatgpt-api这个项目的哪个地方放accessToken呢？我尝试直接修改代码，貌似不太行。

go-chatgpt-api 我一般只是获得一个地址： `http://ip:8080/conversation` 。

至于access token，是在其它chatGPT项目里填写的，比如 [Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)、[Kerwin1202/chatgpt-web](https://github.com/Kerwin1202/chatgpt-web)或[moeakwak/chatgpt-web-share](https://github.com/moeakwak/chatgpt-web-share)

**Comment by yayaQAQ** [comment]
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/20497531/232442335-1733777d-e2d1-4774-a3a6-43708fb63d18.png">
我是这样调用gpt4的，8090是go-chatgpt-api的接口，我直接使用 https://chat.gateway.do/api/ 当做base_url是可以的，但是用我自建的不太行。

**Comment by linweiyuan** [comment]
> > 你是苹果系统？
> > 看看你是怎么跑的 chromedriver，是否有误
> 
> 确实是苹果系统，我并没有特地的跑chromedriver，我是直接运行编译后的 go-chatgpt-api 二进制文件，也可以启动。但是过一段时间会挂掉。

没有跑 `chromedriver` 理论上起不来

我看你最上面的图是 `/api/conversation`，默认没有 `/api`

**Comment by huangwb8** [comment]
非常感谢大家的热心帮忙！ 

我已经成功地使用go-chatgpt-api进行自建代理了。 具体的经验我已经在博客里总结， 感兴趣的小伙伴可以去看看：  https://blognas.hwb0307.com/linux/docker/4201 

暂时关闭该issue喽！
