### ISSUE TITLE
422 error with the latest version

### ISSUE THREAD

**Issue by phoniwell** [linweiyuan/go-chatgpt-api#170]
After updated to the latest version, I got continuous 422 errors.

 docker image ls
REPOSITORY                             TAG       IMAGE ID       CREATED         SIZE
linweiyuan/go-chatgpt-api              latest    3de467ab0485   15 hours ago    19.3MB

![IMG_20230618_151553](https://github.com/linweiyuan/go-chatgpt-api/assets/35026094/0ea3f6bc-e3f9-4d79-9d29-c20f6a31a6bb)

Revert to an older version or public proxy will solve it.

**Comment by linweiyuan** [comment]
https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/chatgpt-unofficial-proxy-api.ts#L142-L156

https://github.com/linweiyuan/go-chatgpt-api/commit/1be0b6440f1e82d3a5c08c3b3b4d17a6be952e75#diff-37a7366804d788fa86357fe2565b3887a85a83e44568bb752ad364cc64310db2L41-L43

This issue exists for months.

**Comment by spldmanager** [comment]
我也遇到了，到底是啥问题？

**Comment by linweiyuan** [comment]
简单来说，就是 chatgpt-web 依赖的库存在一个问题，它的参数不适配 ChatGPT 官网最新接口，之前 go-chatgpt-api 有几行代码单独适配它，但是这个会和官网 "Continue generating" 功能有冲突，我昨天删了，没想到这个 bug 至今仍未修复，至少一个多月了

**Comment by spldmanager** [comment]
> 简单来说，就是 chatgpt-web 依赖的库存在一个问题，它的参数不适配 ChatGPT 官网最新接口，之前 go-chatgpt-api 有几行代码单独适配它，但是这个会和官网 "Continue generating" 功能有冲突，我昨天删了，没想到这个 bug 至今仍未修复，至少一个多月了

那个库说它以后只支持chatgpt的官方接口了，估计不会修复了。就那么简单一个接口逻辑都不肯修复不知道是啥想法。早知道我就直接请求官方的接口不用它了，现在搞得很烦

**Comment by linweiyuan** [comment]
那我加回去适配它吧

**Comment by spldmanager** [comment]
> 那我加回去适配它吧

不用改回去了，我已经把它那个源码给改了，几句话的东西。现在能够正常输出长对话了，很赞，感谢！

**Comment by linweiyuan** [comment]
已经改了

https://github.com/linweiyuan/go-chatgpt-api#2023-06-18-%E7%A0%B4%E5%9D%8F%E6%80%A7%E6%9B%B4%E6%96%B0

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/issues/164

现在 "auto_continue" 默认是关闭状态

**Comment by SiMPlerMeta** [comment]
升级了最新的版本，目前访问会报404
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/28827408/950aed22-b04b-4d23-9cb4-37655a5f1537)

**Comment by SiMPlerMeta** [comment]
没事了，看了修改记录，代理改成 http://go-chatgpt-api:8080/chatgpt/backend-api/conversation 就可以正常使用了，加了一个路径 /backend-api

**Comment by phoniwell** [comment]
Update again and change the interface to http://go-chatgpt-api:8080/chatgpt/backend-api/conversation, no more error output.

Thanks a lot!

**Comment by SiMPlerMeta** [comment]
发现一个新问题，新版本回复完了之后，会一直等待，直到报错才结束

![image](https://github.com/linweiyuan/go-chatgpt-api/assets/28827408/30216fe0-3f7f-43cb-bb87-70dd5f1e28be)

![image](https://github.com/linweiyuan/go-chatgpt-api/assets/28827408/12cfdd0d-e553-4c01-a404-2f914adf8226)

**Comment by linweiyuan** [comment]
这是偶尔出现还是有必现的 prompt 或者步骤

不知是否和 browsing 有关，还没用过这个

**Comment by SiMPlerMeta** [comment]
刚才测试了一下，发现如果是回复的结果很长，会出现这个问题，如果回复的结果很短，可以正常结束

**Comment by linweiyuan** [comment]
这是什么前端

**Comment by SiMPlerMeta** [comment]
是在Chanzhaoyu/chatgpt-web 的基础上改的一个项目，仓库代码如下：https://github.com/Kerwin1202/chatgpt-web

**Comment by SiMPlerMeta** [comment]
我测试了好多次，access token，只要回复内容过长，都会出现这个问题，回复完毕无法结束

**Comment by linweiyuan** [comment]
更新试试？不是很熟悉这些插件的用法

**Comment by SiMPlerMeta** [comment]
可以了，更新了最新的版本，现在长回复也能正常结束了，感谢大佬！
