### ISSUE TITLE
可以科学上网，api没有welcome

### ISSUE THREAD

**Issue by lsw1589034474** [linweiyuan/go-chatgpt-api#171]
curl可以请求到，api没有日志
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/54879658/cdd2444f-3d76-4721-84a7-60232a179842)

**Comment by lsw1589034474** [comment]
补充图片
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/54879658/e44e0566-630a-426d-849e-4f5687bba1ab)

**Comment by linweiyuan** [comment]
更新，参考文档

**Comment by lsw1589034474** [comment]
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/54879658/b88f66ac-8cdd-46a2-a37f-eb314cd4151e)
最新镜像无法拉取，search是有的

**Comment by linweiyuan** [comment]
如果有配置过 docker 源，那么有可能是那里的问题

我测试是可以拉取

**Comment by lsw1589034474** [comment]
api启动报错
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/54879658/05fe07b8-7572-4733-ad4d-4367d50c85b2)

**Comment by lsw1589034474** [comment]
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/54879658/ef6f6818-40d1-478c-89f9-e494aa3d3cfc)

**Comment by linweiyuan** [comment]
用这个 7890 代理访问官网会返回什么

**Comment by lsw1589034474** [comment]
curl就是走的7890代理访问的openai

**Comment by lsw1589034474** [comment]
curl回来的被屏蔽？

**Comment by linweiyuan** [comment]
打开官网你就会明白原因

**Comment by lsw1589034474** [comment]
您指的是打开页面，还是curl请求

**Comment by linweiyuan** [comment]
用这个 7890 代理打开网页版 ChatGPT

**Comment by lsw1589034474** [comment]
这个是部署在linux，本地网络不通，还有其他方式访问吗

**Comment by linweiyuan** [comment]
就是你的 IP 被 OpenAI 屏蔽了

换一个 IP

**Comment by lsw1589034474** [comment]
目前这个就是刚换的的服务器

**Comment by linweiyuan** [comment]
服务器加个 warp 配置伪装 IP

文档也有，其他人也有一键脚本

这个是整个 VPS 服务商封禁的，不只是针对单个 IP

但是你的代理配置 192.168 一眼本地局域网

**Comment by lsw1589034474** [comment]
warp拒绝连接
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/54879658/5710e180-c875-488f-add4-db0148f9d555)

**Comment by linweiyuan** [comment]
#31

**Comment by lsw1589034474** [comment]
还是拒绝连接
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/54879658/68339422-72c1-4ead-bb99-7623461f23bd)

**Comment by linweiyuan** [comment]
发下配置看看

或者服务器信息能发我登录看看？

或者我发个临时公钥来登录下？

**Comment by linweiyuan** [comment]
国内服务器不在讨论范围内

**Comment by lsw1589034474** [comment]
现在梯子也不能使用了吗？

**Comment by linweiyuan** [comment]
配置冲突，要手动处理下

先确保魔法生效，再设置 warp 镜像通过这个魔法出去连接到 Cloudflare，再设置 api 通过这个 warp 出去

![IMG_20230619_151010.jpg](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/82e2b783-ec45-48b0-a116-88cfd3825875)

**Comment by lsw1589034474** [comment]
这个要怎么设置，共一个GO_CHATGPT_API_PROXY不是冲突了吗

**Comment by linweiyuan** [comment]
就是冲突了，上面是解决思路，具体配置没试过

**Comment by lsw1589034474** [comment]
warp是http或者https请求的吗

**Comment by lsw1589034474** [comment]
目前全局代理设置的是http和https走梯子

**Comment by linweiyuan** [comment]
是不是本地起了一台虚拟机？

这个 warp 镜像只能作用于有公网 IP 的服务器上，不管是否有梯子

可以把日志级别改为 DEBUG 或 INFO，可以看到报错

**Comment by lsw1589034474** [comment]
不是本地，linux用docker部署的

**Comment by lsw1589034474** [comment]
看梯子日志也是走梯子了，刚才开了公网ip，还是拒绝连接，容器内curl也是通的
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/54879658/f6586b21-6d0e-40bf-9f91-1a96428d39eb)
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/54879658/e23a7b08-d2eb-4a20-a012-356223abbde5)

**Comment by lsw1589034474** [comment]
改为DEBUG 没有发现报错
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/54879658/1e65cf05-d051-41cb-a12f-db925cead8f1)

**Comment by linweiyuan** [comment]
这么多 failed 还说没报错？

这个 warp 我也只是负责打包，具体的工作原理不是很清楚

目前我知道的就是这么多了，再详细的错误原因就要靠你自己上网查了

---

国外 VPS，3.5 刀一个月，完美解决各种网络问题不香吗
