### ISSUE TITLE
最新的源码支持这个接口吗？

### ISSUE THREAD

**Issue by ludashi2020** [linweiyuan/go-chatgpt-api#174]
https://chat.openai.com/backend-api/aip/p?offset=0&limit=250&is_installed=true

**Comment by linweiyuan** [comment]
理论上支持

**Comment by ludashi2020** [comment]
> 理论上支持

GET请求，状态401,返回值：{"detail":"Unauthorized"}，普通账户测试的。这表示源码是支持这个API接口的吗？

**Comment by linweiyuan** [comment]
理论上，所有 /backend-api 的接口都支持

那你搞个合法 token 不就能试到了？

我没试过这个接口，只能说理论上支持

**Comment by ludashi2020** [comment]
> 。这表示源码是支持这个API接口的吗？

谢谢

**Comment by ludashi2020** [comment]
> 理论上，所有 /backend-api 的接口都支持
> 
> 那你搞个合法 token 不就能试到了？
> 
> 我没试过这个接口，只能说理论上支持

谢谢
