### ISSUE TITLE
使用gpt-4-browsing遇到一个问题，不知道大佬是否可以在代理层面解决

### ISSUE THREAD

**Issue by SiMPlerMeta** [linweiyuan/go-chatgpt-api#176]
这两天使用gpt-4-browsing模型，发现一个问题，如果回复的消息过长，发现只会回复后半部分的内容，前半部分的内容会被替换，如图：
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/28827408/3557aba5-b5dc-4e6a-a9e8-dda5ef4e30aa)

同时对比了gpt-4模型，gpt-4如果回复的消息过长，消息会截断，这样前半部分的内容可以正常显示，然后回复继续，可以显示后半部分的内容，但是现在由于有两个chat.id，前半部分内容直接就被替换了，gpt-4效果如图：

![image](https://github.com/linweiyuan/go-chatgpt-api/assets/28827408/c9c5e1be-6942-4724-a9fc-dc7d50007789)

通过对比发现，原来gpt-4-browsing的请求里面，如果一个请求消息过长，会同时有两个chat.id，这种情况希望大佬可以给个解决办法

**Comment by SiMPlerMeta** [comment]
官网gpt-4也是中断的，gpt-4-browsing不会中断，但是会显示全文，如图：
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/28827408/f2c8504a-d0a0-4d5e-b0fe-9c9eb44372d0)
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/28827408/bbd822a1-ca00-4eeb-82af-389ac8ed4a39)

**Comment by SiMPlerMeta** [comment]
截图中的文字可以忽略了，我最开始的时候以为是项目会限制，然后截断的，后来发现是id的原因，id变了，前端展示的时候就会认为是一个新的回复，所以直接给前面部分替换了

**Comment by spldmanager** [comment]
你这个问题需要客户端自己解决，因为它本身是一个stream流，所以它只是显示当前id得流数据，而长文是会有2个id，这个还是需要自己做id判断输出

**Comment by linweiyuan** [comment]
附议

前端之所以截断，因为完全就是显示 text 出来，需要像 apiKey 一段一段字吐出来那样拼接一下

后端实现起来就比较复杂了

**Comment by spldmanager** [comment]
> 附议
> 
> 前端之所以截断，因为完全就是显示 text 出来，需要像 apiKey 一段一段字吐出来那样拼接一下
> 
> 后端实现起来就比较复杂了

我研究了一下，官方得API的流是一个字一个字的出的，所以可以通过累加的方式出文字，例如第一次输出“你”，第二次输出“好”
楼主用的那个库应该是用的chat-gpt-api那个库，那个库是把官方的输出以累加的方式进行了封装，例如第一次输出“你”，第二次输出“你好”
这样返回给前端的时候，如果ID一致，第二种方式就比较简单，前端只要直接显示就可以了。但是如果出现长文，就比较麻烦了，最好的方法是后端做一下拼装，例如生成一个对象，对象的键值KEY是ID，值是文字，那样只要简单的把两个KEY的值相加给到前端，前端就不用改代码直接显示就可以了，多个ID也不会有问题

**Comment by linweiyuan** [comment]
如果有一个前端就好办，但是据我所知至少有三个前端用这个 api，一个 chatgpt-web，一个 chatgpt-web-share，一个是那个 QQ 机器人

一开始我也弄过比如单纯传个 prompt 参数后端补全其他不必要的参数这样，后来还是改成了官网一样的参数

为什么呢？因为单纯一个客户端还行，但是多个的话，那就要每个都单独适配一遍，如果换成对接其他 api，比如 proxy-v4 或者 fakeopen，那么就不兼容了，考虑到通用性，万一哪天官方取消 Cloudflare 了，那么无缝迁移可以直接连过去

（还有一点就是有点懒）

需要再看看怎么取一个折中的方法

**Comment by spldmanager** [comment]
> 

对，我也是刚开始有点小白，又懒才用了他那个chat-gpt-api，现在看来官方的接口返回也不复杂，完全用不着在他那个库走一遍，而且那个库还对NODEJS的版本有要求，还放弃了对非sessionToken方式的适配，真的是无语死了

**Comment by SiMPlerMeta** [comment]
客户端改的话，会不会引起上下文不连续，我看接口里面是有lastid的，万一客户端改了，和lastid不一致，就无法识别上一次的对话了

**Comment by SiMPlerMeta** [comment]
我用的是https://github.com/Kerwin1202/chatgpt-web这个项目，需要用access token才行，在key管理里面添加一个key就行了，部署过程可以参考https://blognas.hwb0307.com/linux/docker/4201这篇文档，里面写的比较详细

**Comment by linweiyuan** [comment]
我跑了个假项目

不配置邮件注册发送验证可以吗，我只是想有个账号可以进去测试到 `gpt-4-browsing`，应该怎么做？

我这个是直接把这个账号数据库改为 `status: 0`

![2023-06-22_11-48](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/fc28e0a8-8eff-4af4-8359-0fe0e44a15b2)

**Comment by SiMPlerMeta** [comment]
可以的，你把邮件注册关了就可以访问了的，其实主邮箱是不需要进邮箱激活的，直接注册就通过了

**Comment by linweiyuan** [comment]
还是倾向于前端解决

**Comment by SiMPlerMeta** [comment]
我想到一个办法，大佬是否可以在代理请求的参数里面增加maxResponseTokens的判断，目前的请求体我看是不包含这个参数的，如果请求token大于自定义的设置，消息就截断，这样就不会产生两个id了，这个参数可以根据个人自定义，目前项目里面是设置了这个全局变量，但是我看并没有用到，如果能在代理层面做到，其实我感觉也是可以的
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/28827408/55f9bca9-553f-4f80-9abf-f74bfae68a72)

![image](https://github.com/linweiyuan/go-chatgpt-api/assets/28827408/6e661b10-fac0-489a-9ad6-c783b292ac78)

**Comment by SiMPlerMeta** [comment]
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/28827408/1a61a861-72c8-4061-9fc6-af1bc5e942d5)
我看原项目有人这么处理的

**Comment by linweiyuan** [comment]
去给 chatgpt-web 提 issue
