### ISSUE TITLE
model3.5没问题，换4就403了

### ISSUE THREAD

**Issue by OceanNg529** [linweiyuan/go-chatgpt-api#178]
账号已经Plus。
/chatgpt/backend-api/conversation
请求
{
  "action": "next",
  "messages": [
    {
      "id": "d06f6cfb-aba4-432b-920b-00bcbf4c8031",
      "author": {
        "role": "user"
      },
      "content": {
        "content_type": "text",
        "parts": [
          "你可以干什么"
        ]
      },
      "metadata": {}
    }
  ],
  "model": "gpt-4",
  "timezone_offset_min": -480,
  "history_and_training_disabled": false
}
返回
{
	"detail": "Our systems have detected unusual activity from your system. Please try again later."
}

**Comment by linweiyuan** [comment]
和 #175 重复了，先关了这个，那边更新进度
