### ISSUE TITLE
问题：在docker容器运行正常，但在vscode调试时不能正常连接gpt

### ISSUE THREAD

**Issue by yuejunzhang** [linweiyuan/go-chatgpt-api#183]
问题：在docker容器运行正常，但在vscode调试时不能正常连接gpt,返回的内容是：
{"errorMessage":"Post \"[https://chat.openai.com/backend-api/conversation\](https://chat.openai.com/backend-api/conversation/)": dial tcp 31.13.95.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
请问什么原因？

**Comment by linweiyuan** [comment]
魔法失效

**Comment by yuejunzhang** [comment]
魔法在电脑上网（包括访问gpt官网）和在docker容器运行本项目时是有效的，也正常返回对话内容。但就是在vscode中调试本项目时连不上目标。

**Comment by linweiyuan** [comment]
这就奇怪了

玄学问题可以试下重启，路由器，电脑，api

**Comment by yuejunzhang** [comment]
项目的环境变量如下：
# API server port
GO_CHATGPT_API_PORT=8080
# Network proxy server address 
# GO_CHATGPT_API_PROXY 
没有使用任何代理

**Comment by linweiyuan** [comment]
人在国内？裸连能连上？日志有没有 Service is ready

**Comment by yuejunzhang** [comment]
在国内通过魔法上网。是不是也得给这个项目的env 设置代理服务器才行？如何设置呢？

**Comment by linweiyuan** [comment]
文档写得很清楚了

那你又说容器内运行正常，还能返回对话？

**Comment by yuejunzhang** [comment]
是的，在容器内运行正常返回对话。在vscode中其它代码用官方API+key访问官网也能正常返回，说明环境的网络是没有问题的，问题可能出在本项目的网络设置。😣

**Comment by yuejunzhang** [comment]
我是用python代码测试本项目，部分代码如下：

url = "http://127.0.0.1:8080/chatgpt/backend-api/conversation"

params = {
  "action": "next",
  "messages": [
    {
      "id": guid,
      "author": {
        "role": "user"
      },
      "content": {
        "content_type": "text",
        "parts": [
          "who are you?"
        ]
      },
      "metadata": {}
    }
  ],
  "model": "text-davinci-002-render-sha",
  "timezone_offset_min": -480
   
}

# Send the API request with the prompt and parameters
headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer "  + APIKEY,
    #"Accept": "application/json"# "text/event-stream"
}
 
response = requests.post(url, headers=headers, json=params) 
print(response.text)

**Comment by linweiyuan** [comment]
怎么又变 python 了，不是正在说 vscode  吗？思维太发散了，我没跟上

**Comment by linweiyuan** [comment]
贴出所有配置

**Comment by yuejunzhang** [comment]
也没有其它配置，基本是项目自带的

环境文件：.env:   //////////////////////////////////////
 ####API server port
GO_CHATGPT_API_PORT=8080
####Network proxy server address 
####GO_CHATGPT_API_PROXY 

dockerfile:   /////////////////////////////////////////////
FROM golang:alpine AS builder
WORKDIR /app
COPY . .
RUN go build -ldflags="-w -s" -o go-chatgpt-api main.go

FROM alpine
WORKDIR /app
COPY --from=builder /app/go-chatgpt-api .
RUN apk add --no-cache tzdata
ENV TZ=Asia/Shanghai
EXPOSE 8080
CMD ["/app/go-chatgpt-api"]

compose.yaml:   //////////////////////////////////////////////
services:
  go-chatgpt-api:
    build: .
    container_name: go-chatgpt-api
    image:  go-chatgpt-api
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Shanghai
      - GO_CHATGPT_API_PROXY=
    restart: unless-stopped

**Comment by linweiyuan** [comment]
所以容器正常返回对话是怎么回事

![IMG_20230623_172113.jpg](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/e4438527-1016-470c-9613-230fd68e1aea)

**Comment by yuejunzhang** [comment]
我重新拉取代码试试

**Comment by yuejunzhang** [comment]
原因找到，是无法读取环境变量，也就无法设置代理服务器，所以调试时外部网络不通。

func NewHttpClient() tls_client.HttpClient {
	client, _ := tls_client.NewHttpClient(tls_client.NewNoopLogger(), []tls_client.HttpClientOption{
		tls_client.WithCookieJar(tls_client.NewCookieJar()),
		tls_client.WithClientProfile(tls_client.Okhttp4Android13),
	}...)

	// proxyUrl := os.Getenv("GO_CHATGPT_API_PROXY")在这里无法读取环境变量和设置代理服务器。
	// if proxyUrl != "" {
	// 	client.SetProxy(proxyUrl)
	// }
	return client
}
