### ISSUE TITLE
服务器访问ip:8080跳转你的项目地址

### ISSUE THREAD

**Issue by 2367314406** [linweiyuan/go-chatgpt-api#185]
一访问这个api就跳转到你的项目地址

**Comment by linweiyuan** [comment]
故意的，有什么问题

**Comment by 2367314406** [comment]
项目本身问题？，我其他服务器也没事啊，就今天这一台跳

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/blob/main/middleware/check_header.go#L18
