### ISSUE TITLE
使用了最新的docker镜像后，所有的http请求不是404就是500

### ISSUE THREAD

**Issue by nsnake** [linweiyuan/go-chatgpt-api#191]
日志里面的信息如下
go-chatgpt-api    | INFO[0000] Service go-chatgpt-api is ready.
go-chatgpt-api    | [GIN] 2023/06/25 - 14:28:24 | 500 |     438.439µs |      172.18.0.1 | GET      "/healthCheck"
go-chatgpt-api    | [GIN] 2023/06/25 - 14:47:54 | 500 |     191.839µs |       127.0.0.1 | GET      "/healthCheck"
go-chatgpt-api    | [GIN] 2023/06/25 - 14:48:06 | 500 |     216.878µs |       127.0.0.1 | GET      "/healthCheck"
go-chatgpt-api    | [GIN] 2023/06/25 - 14:49:51 | 404 |  594.411097ms |      172.18.0.1 | POST     "/chatgpt/conversation"

**Comment by linweiyuan** [comment]
其实可以看下文档

https://github.com/linweiyuan/go-chatgpt-api#%E5%A6%82%E4%BD%95%E9%9B%86%E6%88%90%E5%85%B6%E4%BB%96%E7%AC%AC%E4%B8%89%E6%96%B9%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by linweiyuan** [comment]
404 因为接口加了个 backend-api

500 可能不在容器里跑或者没有挂载 docker.sock，不影响使用

**Comment by nsnake** [comment]
跟换路径口正常了
