### ISSUE TITLE
请问大神，什么时候需要更新docker

### ISSUE THREAD

**Issue by justincnn** [linweiyuan/go-chatgpt-api#192]
刚才看日志，你又更新了，update health check，

我们docker需要同步更新docker么？

**Comment by linweiyuan** [comment]
不用也可以，不影响功能，如果想不管它自动更新，可以配合 watchtower 使用

**Comment by justincnn** [comment]
> 不用也可以，不影响功能，如果想不管它自动更新，可以配合 watchtower 使用

刚开始学docker，上次用了watchtower发现所有docker都自动更新了，有几个想保留原版本，不做更新。

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/issues/99

有参数可以设置哪些容器保留
