### ISSUE TITLE
请求这个接口 /api/conversation 报错了

### ISSUE THREAD

**Issue by ocswor** [linweiyuan/go-chatgpt-api#193]
使用的是accessToken 模式 gpt-4
报错：'{"errorMessage":"Post \\"/api/conversation\\": invalid URL scheme: []"}'

我的配置如下：
version: "3" 
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080         # 容器端口映射到宿主机8080端口；宿主机监听端口可按需改为其它端口
    environment:
      - GO_CHATGPT_API_PROXY=    # GO_CHATGPT_API_PROXY=：科学上网代理地址，例如：http://10.0.5.10:7890
      - GO_CHATGPT_API_ARKOSE_TOKEN_URL=https://arkose-token.linweiyuan.com
    restart: unless-stopped

**Comment by linweiyuan** [comment]
潘多拉？看文档加个环境变量参数

**Comment by ocswor** [comment]
> 潘多拉？看文档加个环境变量参数

嗯 是在潘多拉里面调的，加上了，现在返回 b'{"errorMessage":"Failed to parse json request body."}' 这个异常  

这个能看下返回的是什么错误么？

**Comment by linweiyuan** [comment]
要看下你的请求参数

**Comment by ocswor** [comment]
> 要看下你的请求参数
conversation_id 这个id 是我随机生成的
{'action': 'next', 'messages': [{'id': 'd18dd81c-1347-11ee-8fbd-509a4c1feda4', 'role': 'user', 'author': {'role': 'user'}, 'content': {'content_type': 'text', 'parts': ['我的生日是1990年2月22号']}}], 'model': 'gpt-4', 'parent_message_id': '', 'conversation_id': 'd37382ac-1337-11ee-855f-509a4c1feda4'}

**Comment by linweiyuan** [comment]
不清楚 Python 里怎么处理的，但是这个单引号，在好多地方都不是合法 JSON

**Comment by ocswor** [comment]
> 不清楚 Python 里怎么处理的，但是这个单引号，在好多地方都不是合法 JSON

不好意思，我重新发你一个 麻烦看下
{"action": "next", "messages": [{"id": "d18dd81c-1347-11ee-8fbd-509a4c1feda4", "role": "user", "author": {"role": "user"}, "content": {"content_type": "text", "parts": ["我的生日是1990年2月22号"]}}], "model": "gpt-4", "parent_message_id": "", "conversation_id": "d37382ac-1337-11ee-855f-509a4c1feda4"}

**Comment by linweiyuan** [comment]
这个没问题，这个会 400？

**Comment by ocswor** [comment]
> 这个没问题，这个会 400？

是啊 我也都蒙了，不知道咋办，返回是这个 '{"errorMessage":"Failed to parse json request body."}'

**Comment by linweiyuan** [comment]
没问题啊，是不是魔改了潘多拉？

我这个是下载的当前最新代码，非常正常

![2023-06-25_19-31](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/c50169d5-da74-40a6-8986-7e266b5fd07b)
