### ISSUE TITLE
希望加个超时判断

### ISSUE THREAD

**Issue by ahwdy98** [linweiyuan/go-chatgpt-api#20]
有的时候会出现卡死，调用api无反应。其中一个可以复现的情况是在使用过期的accesstoken连接后会直接卡死，之后用没过期的accesstoken调用就会504，只能重启docker容器。

**Comment by linweiyuan** [comment]
卡死要重启，是死锁了

过期 token 卡死的话，我要等我的 token 过期才好调试

**Comment by fjiabinc** [comment]
> 卡死要重启，是死锁了
> 
> 过期 token 卡死的话，我要等我的 token 过期才好调试

希望大佬开个tg频道共同讨论相关话题.最近两天大量代理服务被禁用.正在寻找新方法

**Comment by linweiyuan** [comment]
> > 卡死要重启，是死锁了
> > 过期 token 卡死的话，我要等我的 token 过期才好调试
> 
> 希望大佬开个tg频道共同讨论相关话题.最近两天大量代理服务被禁用.正在寻找新方法

这样通过 issue 或者邮件，其实也挺好的

**Comment by linweiyuan** [comment]
> 有的时候会出现卡死，调用api无反应。其中一个可以复现的情况是在使用过期的accesstoken连接后会直接卡死，之后用没过期的accesstoken调用就会504，只能重启docker容器。

过期 `token` 卡死的问题已修复
