### ISSUE TITLE
403问题

### ISSUE THREAD

**Issue by dktobeno1** [linweiyuan/go-chatgpt-api#200]
作者你好，请问https://go-chatgpt-api.linweiyuan.com/chatgpt/backend-api/这个是你提供的base_url反代吗，我挂这个发请求gpt4返回的都是OpenAI: {"detail":"Our systems have detected unusual activity from your system. Please try again later."} (code: 403)，是我使用不当还是当前版本受到openai风控了？

**Comment by linweiyuan** [comment]
#175

这条链接不行了，先下线，等行了再重新上
