### ISSUE TITLE
请问为什么Api 余额接口不能直接反代官方的？

### ISSUE THREAD

**Issue by spldmanager** [linweiyuan/go-chatgpt-api#201]
接口url格式和官方的不一样，而且不能用key来查询而是要用session ，这样在兼容官方和自建反代上就有问题了。
请问这个接口修改的出发点是啥？

**Comment by linweiyuan** [comment]
你看看官方这两个接口是不是也是 session key

正确应该用哪个接口查询余额？

**Comment by spldmanager** [comment]
我看官方的接口是
V1/dashboard/billing/subscriptions
和
V1/dashboard/billing/usage 
这两个接口，用Api key就可以查询

**Comment by linweiyuan** [comment]
刚试了下，是正常的，这两条接口可以用 `apiKey`

但是接口 url 格式和官方的不是一模一样吗，你是指多了个 `/platform`？

那么官方这两个接口哪来的 `/v1` 呢？

**Comment by spldmanager** [comment]
我是看到一个开源程序里面用了这个v1的，也可以执行成功。
我已经全部改成你这边的接口url了，没问题了

**Comment by mygit-2023** [comment]
官网路径是 /dashboard/billing/subscription 吧，subscriptions 404哦

**Comment by linweiyuan** [comment]
`/platform/dashboard/billing/subscription`
