### ISSUE TITLE
Please provide a valid access token or api key in 'Authorization' header. 

### ISSUE THREAD

**Issue by online2311** [linweiyuan/go-chatgpt-api#214]
使用潘多拉 如何解决 Please provide a valid access token or api key in 'Authorization' header.  提示的问题。
```
WARN[0007] Please provide a valid access token or api key in 'Authorization' header.
[GIN] 2023/07/13 - 14:19:22 | 401 |     198.936µs |  103.197.70.115 | GET      "/api/models?history_and_training_disabled=false"
WARN[0007] Please provide a valid access token or api key in 'Authorization' header.
[GIN] 2023/07/13 - 14:19:22 | 401 |     123.334µs |  103.197.70.115 | GET      "/api/conversation_limit"
WARN[0007] Please provide a valid access token or api key in 'Authorization' header.
[GIN] 2023/07/13 - 14:19:22 | 401 |      40.176µs |  103.197.70.115 | GET      "/api/settings/beta_features"
WARN[0007] Please provide a valid access token or api key in 'Authorization' header.
[GIN] 2023/07/13 - 14:19:22 | 401 |      81.143µs |  103.197.70.115 | GET      "/api/conversations?offset=0&limit=28&order=updated"
WARN[0007] Please provide a valid access token or api key in 'Authorization' header.
[GIN] 2023/07/13 - 14:19:22 | 401 |      27.452µs |  103.197.70.115 | GET      "/api/aip/p?offset=0&limit=250&is_installed=true"
```

谢谢

**Comment by linweiyuan** [comment]
Cloud 模式？听说需要修改代码的请求头

潘多拉的控制台模式我之前测试挺正常的

**Comment by ludashi2020** [comment]
今天开始不行了，好像多一个这样的参数了preauth_cookie，目前潘多拉自己的api增加了一个刷新preauth_cookie的操作/auth/preauth   
 def __part_one(self) -> str:
        url = '{}/auth/preauth'.format(default_api_prefix())
        resp = self.session.get(url, allow_redirects=False, **self.req_kwargs)

        if resp.status_code == 200:
            json = resp.json()
            if 'preauth_cookie' not in json or not json['preauth_cookie']:
                raise Exception('Get preauth cookie failed.')

            return self.__part_two(json['preauth_cookie'])
        else:
            raise Exception('Error request preauth.')

**Comment by linweiyuan** [comment]
不关事，这个参数存在很久了

晚上我改下兼容潘多拉

**Comment by ludashi2020** [comment]
> 不关事，这个参数存在很久了
> 
> 晚上我改下兼容潘多拉

最新的authorize
`https://auth0.openai.com/authorize?ios_device_id=0E92DAF9-94F0-4F77-BDF4-53A60D19EC65&state=4DJBNv86mezKHDv-i2wMuDBea2-rHAo5nA_ZT4zJeak&ios_app_version=1744&client_id=pdlLIX2Y72MIl2rhLhTE9VV9bN905kBh&redirect_uri=com.openai.chat://auth0.openai.com/ios/com.openai.chat/callback&code_challenge={code_challenge}&scope=openid%20email%20profile%20offline_access%20model.request%20model.read%20organization.read%20organization.write&prompt=login&preauth_cookie=0E92DAF9-94F0-4F77-BDF4-53A60D19EC65:1689211716-%252BgvfVFx2FxYh4Ak%252BWJWraqixO9aIVLOtwkP8Y3cim2E%253D&audience=https://api.openai.com/v1&code_challenge_method=S256&response_type=code&auth0Client=eyJ2ZXJzaW9uIjoiMi4zLjIiLCJuYW1lIjoiQXV0aDAuc3dpZnQiLCJlbnYiOnsic3dpZnQiOiI1LngiLCJpT1MiOiIxNi4yIn19`  多了些参数

**Comment by linweiyuan** [comment]
走 iOS 登录，这些参数是一直走的

网页版登录没有

**Comment by ludashi2020** [comment]
我看上一版的潘多拉没有这个参数，现在多了这个路由/auth/preauth，刷新了preauth_cookie，然后就正常了

**Comment by linweiyuan** [comment]
你是说刷新了后，访问 go-chatgpt-api 正常，不会有 `Please provide xxx` ?

**Comment by ludashi2020** [comment]
> go-chatgpt-api

go-chatgpt-api 不支持刷新preauth_cookie吧，用潘多拉默认的api是可以的，换上go-chatgpt-api会提示Error request preauth.

**Comment by linweiyuan** [comment]
我其实是想问，你说的这个问题，和这个 issue 的标题描述的是不是不是一回事，有点乱

**Comment by gngpp** [comment]
那个潘多拉的是X-Authorization头放token，这边肯定检测不到，都不是一个标准

**Comment by gngpp** [comment]
> 那个潘多拉的是X-Authorization头放token，这边肯定检测不到，都不是一个标准

能用就有鬼了
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/51810656/59b70b3b-3204-46ae-b0ff-934efe9c16ab)

**Comment by linweiyuan** [comment]
@online2311 看看你的配置，我测试很正常

**Comment by linweiyuan** [comment]
控制台模式没有任何问题，Cloud 模式据我理解，只能用他的接口吧

![2023-07-14_10-09](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/36ebe67d-9317-45be-865e-0036189b06f1)

**Comment by ludashi2020** [comment]
> 

go-chatgpt-api可以用于潘多拉云平台，但是从昨天开始，chatgpt官方增加了preauth_cookie参数之后就不能用了。之前我一直都用go-chatgpt-api代替潘多拉默认api的

**Comment by linweiyuan** [comment]
想问下这里应该如何配置

![2023-07-14_11-13](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/ec090d63-3962-4d52-b9f4-763635d257ec)

**Comment by Ariesly** [comment]
pandora Cloud 模式 尝试修复失败. 等其他大佬提PR.

**Comment by linweiyuan** [comment]
所以没人回复我怎么设置 Cloud 模式指向自己？

**Comment by Ariesly** [comment]
> 所以没人回复我怎么设置 Cloud 模式指向自己？

我是用这个跑起来服务
```yaml
version: "3"
services:
  pandora:
    image: pengzhile/pandora
    ports:
      - "8081:8081"
    environment:
      - CHATGPT_API_PREFIX=http://localhost:8080 #根据真实情况再改?
      - PANDORA_CLOUD=cloud
      - PANDORA_SERVER=0.0.0.0:8081
    restart: unless-stopped
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - GO_CHATGPT_API_PANDORA=1
    restart: unless-stopped
```
然后贴 Access Token 的方式的.

仅供参考

**Comment by linweiyuan** [comment]
其实走登录还是去 fakeopen，但是用 token 就好了

那么问题又来了，这个 `X-Authorization` 和 `preauth_cookie` 有什么关系？

登录又不是走 go-chatgpt-api，接口又从来不支持 X-Authorization

**Comment by ludashi2020** [comment]
> 想问下这里应该如何配置
> 
> ![2023-07-14_11-13](https://user-images.githubusercontent.com/49076004/253460705-ec090d63-3962-4d52-b9f4-763635d257ec.png)

这个超级简单啊。在源码里修改啊。好像.env里也可以指定。

**Comment by ludashi2020** [comment]
> 

云平台可以修改源码里的api代理地址替换成go-chatgpt-api，X-Authorization其实就是Authorization，他换了个名字而已。go-chatgpt-api完全不需要去修改Authorization，直接nginx重写header就搞定了，超级简单，只是go-chatgpt-api没有/auth/preauth这个路由动态刷新preauth_cookie。是chatgpt官网强制要求加preauth_cookie，以前不加也能登录，现在都挂了。

**Comment by ludashi2020** [comment]
没有刷新，就是这样子，卡在登录页。api代理地址,用的是go-chatgpt-api![OzE7Jl.png](https://i.imgtg.com/2023/07/15/OzE7Jl.png)

**Comment by ludashi2020** [comment]
> 是chatgpt官网强制要求加preauth_cookie，以前不加也能登录，现在都挂了。



> 其实走登录还是去 fakeopen，但是用 token 就好了
> 
> 那么问题又来了，这个 `X-Authorization` 和 `preauth_cookie` 有什么关系？
> 
> 登录又不是走 go-chatgpt-api，接口又从来不支持 X-Authorization



> 想问下这里应该如何配置
> 
> ![2023-07-14_11-13](https://user-images.githubusercontent.com/49076004/253460705-ec090d63-3962-4d52-b9f4-763635d257ec.png)

你好像改错地方了,应该是pip安装源码包存放的地方。

**Comment by linweiyuan** [comment]
要不你去叫潘多拉改吧，他自己不按官网接口结构来，老是喜欢另外搞一套，别人想用第三方 api，就得适配他，我觉得目的就是不想让别人跳开 fakeopen，go-chatgpt-api 这边登录没有任何问题，不是走 iOS，这个问题别讨论了

综上：我这边的登录非常正常，不改，要改叫潘多拉改

![2023-07-15_09-35](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/88014199-4827-4190-9234-f102ac3eb121)

**Comment by ludashi2020** [comment]
> 

我就是用的原版go-chatgpt-api![OzGiaj.png](https://i.imgtg.com/2023/07/15/OzGiaj.png),他这个参数怎么获取的呢？![OzGnep.png](https://i.imgtg.com/2023/07/15/OzGnep.png)

**Comment by linweiyuan** [comment]
go-chatgpt-api 不需要这个参数

**Comment by ludashi2020** [comment]
> go-chatgpt-api 不需要这个参数

好的，感谢大佬。已经用go-chatgpt-api替换fakeopen 成功登录潘多拉云端模式。
