### ISSUE TITLE
程序运行一段时间后提示访问无效的内存地址或空指针

### ISSUE THREAD

**Issue by Haibersut** [linweiyuan/go-chatgpt-api#22]
没有使用docker

环境如下
Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-144-generic x86_64)

下面是报错日记
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x7af54b]

goroutine 10 [running]:
github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh.func1()
        /home/go-chatgpt-api/webdriver/refresh.go:13 +0x2b
created by github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh
        /home/go-chatgpt-api/webdriver/refresh.go:12 +0x6a
exit status 2
```

**Comment by linweiyuan** [comment]
不用 docker 的话，那个 chromedriver 也要一直在后台运行，关了或者挂了就会这个错

**Comment by Haibersut** [comment]
好的我知道了，谢谢你

**Comment by Haibersut** [comment]
我又发现个问题，是不是docker里面chromedriver偶尔会自己关掉然后导致的不稳定？

或者说只是我服务器内存太小爆炸了

![image](https://user-images.githubusercontent.com/117586514/232543741-e657d220-8bf3-4a87-8064-740fb6b3f464.png)

**Comment by linweiyuan** [comment]
1G 内存完全用不完，不适合多人公用，不保证能完美处理验证码，不保证稳定

`docker inspect --format='{{.State.StartedAt}}' container_id` 可查看容器启动时间
`docker inspect --format='{{.RestartCount}} conteiner_id` 可查看容器是否重启
