### ISSUE TITLE
能否支持stream:false的参数，不使用event-stream

### ISSUE THREAD

**Issue by rawchen** [linweiyuan/go-chatgpt-api#224]

**Comment by linweiyuan** [comment]
ChatGPT 模式不支持，因为官方就不支持

API 模式是支持的，一开始就支持了

**Comment by linweiyuan** [comment]
没毛病

![2023-07-19_22-27](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/13134538-d124-438b-a2b8-0b47ff6cb6f6)

![2023-07-19_22-28](https://github.com/linweiyuan/go-chatgpt-api/assets/49076004/588b1cc9-eb60-406a-896f-eb94360f6337)
