### ISSUE TITLE
能不能代理api？

### ISSUE THREAD

**Issue by superen7527** [linweiyuan/go-chatgpt-api#225]
有时候用key，需要反代api。虽然有很多一键但是想都整合一个 不想搞好多个反代，不然一个nginx也能实现。

想法是能直连的直接给出反代端口，不能直连用wrap反代。不过api好像没有web限制地区，好像只要能翻就能反代api？

**Comment by linweiyuan** [comment]
很早就支持了

/platform/v1/chat/completions

**Comment by superen7527** [comment]
ok，本来要讨论里面发，结果发不出去(现在想想应该是网络问题)。最开始是想看看有没有api，之前破坏性更新改路由的时候首页有一个放了本项目支持的所有api文档，现在找不到了，才发了issue，觉得可能没有支持。好久没来了，readme都不一样了。哈哈。
