### ISSUE TITLE
如何添加token    "errorMessage": "Please provide a valid access token or api key in 'Authorization' header."

### ISSUE THREAD

**Issue by walkchen9** [linweiyuan/go-chatgpt-api#228]
"errorMessage": "Please provide a valid access token or api key in 'Authorization' header."

docker 部署的

services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped
 
  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped

**Comment by linweiyuan** [comment]
看一眼这个项目的当前 readme 文档，根据这个来
