### ISSUE TITLE
可以为`getPostScriptForStartConversation`增加注释吗？

### ISSUE THREAD

**Issue by time-river** [linweiyuan/go-chatgpt-api#23]
[getPostScriptForStartConversation](https://github.com/linweiyuan/go-chatgpt-api/blob/main/api/chatgpt/chatgpt.go#L422)有关response的handle case，可以提供注释吗？

**Comment by time-river** [comment]
> 其实里面有注释，用了 //
> 
> 其他感觉顾名思义的，就没写，因为有些所谓注释就是把英文翻译成中文，好像没必要（没别的意思）
> 
> 流程就是根据 `AJAX` 请求的不同状态，然后再根据 `HTTP` 状态码来判断正常处理还是报错，应该挺清晰的
> 
> 你可以本地跑打个断点，或者输出下 `ChatGPT` 返回的数据，就一目了然了
> 
> 或者看重说说哪里不清楚的

我想重构下代码的，因为里面出现了很多魔鬼数字，以及api经过了转换并不一定与openai的相兼容，但POST request部分，那些处理非200的response分支我没有遇到过，着实下不去手。

**Comment by time-river** [comment]
是的。还有`dataArray.pop().substring(6)`的6，这
```
conversationResponseDataString[0:1] == strconv.Itoa(4) || conversationResponseDataString[0:1] == strconv.Itoa(5) {
				statusCode, _ := strconv.Atoi(conversationResponseDataString[0:3])
```

**Comment by linweiyuan** [comment]
4xx 5xx 其实是 HTTP 状态码，有报错就额外处理

substring(6) 就是把 "data: {ChatGPT 实际数据的}" 的"data: " 去掉，因为 API 返回 SSE 有额外的处理返回 "data: "

然后你引用那段就是取出 HTTP 状态码如果有错误（不是 200 就是错）就返回异常

这些是基础设施的代码，如果你重构这里提 PR 我是不合并的
