### ISSUE TITLE
能否配合 https://github.com/binary-husky/gpt_academic 使用？

### ISSUE THREAD

**Issue by hongyi-zhao** [linweiyuan/go-chatgpt-api#235]
能否配合 https://github.com/binary-husky/gpt_academic 使用？即基于本项目实现下面的反代：

https://github.com/binary-husky/gpt_academic/blob/37afcc709bfcd34e7ef9a25ab06347395c62a445/config.py#L35C1-L38C22

```python
# 重新URL重新定向，实现更换API_URL的作用（高危设置! 常规情况下不要修改! 通过修改此设置，您将把您的API-KEY和对话隐私完全暴露给您设定的中间人！）
# 格式: API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "在这里填写重定向的api.openai.com的URL"} 
# 举例: API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://reverse-proxy-url/v1/chat/completions"}
API_URL_REDIRECT = {}
```

**Comment by linweiyuan** [comment]
`API_URL_REDIRECT = {https://你的服务/platform/v1/chat/completions}`

https://github.com/linweiyuan/go-chatgpt-api/blob/main/example/vscode/platform.http#L18-L36

**Comment by hongyi-zhao** [comment]
See https://github.com/binary-husky/gpt_academic/issues/900#issuecomment-1658463065 for related discussions.

**Comment by hongyi-zhao** [comment]
运行成功：

```shell
$ go build
$ PORT=18080 TZ=Asia/Shanghai PROXY=socks5://127.0.0.1:18890 OPENAI_EMAIL="bgrandstaff9@ramons.site" OPENAI_PASSWORD="xxx" ./go-chatgpt-api 
INFO[0000] PROXY: socks5://127.0.0.1:18890   
INFO[0000] Service go-chatgpt-api is ready.  
```

但是仍有如下问题：
```shell
$ curl http://127.0.0.1:18080/platform/v1/chat/completions   -H "Authorization: sk-xxx"   -d '{"model": "gpt-3.5-turbo-16k", "messages": [{"role": "user", "content": "Say this is a test!"}], "stream": true}'
{

"error": {

"message": "You exceeded your current quota, please check your plan and billing details.",

"type": "insufficient_quota",

"param": null,

"code": "insufficient_quota"

}

}
```

**Comment by linweiyuan** [comment]
/imitate/v1/chat/completions

**Comment by M1saka10010** [comment]
在余额过期的账号中platform提示余额不足，imitate提示write: broken pipe，请问怎么解决？

**Comment by linweiyuan** [comment]
你知道 imitate 接口是用来做什么的吗

**Comment by M1saka10010** [comment]
> 你知道 imitate 接口是用来做什么的吗

不是用来chatgpt转api的吗？我自己post可用，但是不知道为啥填进gpt_academic里就broken pipe

**Comment by hongyi-zhao** [comment]
参考我下面的测试方法：

https://github.com/binary-husky/gpt_academic/pull/1014#issuecomment-1681495083

**Comment by M1saka10010** [comment]
> 参考我下面的测试方法：
> 
> [binary-husky/gpt_academic#1014 (comment)](https://github.com/binary-husky/gpt_academic/pull/1014#issuecomment-1681495083)

还是broken pipe，不知道什么东西

**Comment by hongyi-zhao** [comment]
设置下面的了吗？
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/11155854/770a71d0-db67-4486-997a-bcaf9882487e)

**Comment by M1saka10010** [comment]
> 设置下面的了吗？ ![image](https://user-images.githubusercontent.com/11155854/265184536-770a71d0-db67-4486-997a-bcaf9882487e.png)

可以了，好得也莫名其妙的

**Comment by hongyi-zhao** [comment]
https://github.com/binary-husky/gpt_academic/wiki/%E7%AC%AC%E4%B8%89%E6%96%B9API%E2%80%90KEY%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#%E7%89%B9%E4%BE%8B2-chatgpt-to-api

![image](https://github.com/linweiyuan/go-chatgpt-api/assets/11155854/1763d839-148c-4a3c-b8af-ff759aeac001)
