### ISSUE TITLE
各位登录有没有问题？

### ISSUE THREAD

**Issue by superen7527** [linweiyuan/go-chatgpt-api#237]
`curl https://chat.openai.com | grep '<p>' | awk '{$1=$1;print}'`
没问题 美国服务器 没warp直连

curl -X POST /chatgpt/login 却报错
`{"errorMessage":"We were unable to determine your country of origin to enforce geographical restrictions. Please use a different network, or contact us through
our help center at help.openai.com if the issue persists. (error=unknown_country)"}`

有人也是这样吗？

**Comment by superen7527** [comment]
弄了梯试了一下，vps确实不能访问。那个命令行测不出来。

**Comment by linweiyuan** [comment]
错误信息描述得很精确了

命令行是最后辅助的

**Comment by superen7527** [comment]
就是错误描述清楚才奇怪啊。命令行检测ip没问题访问却又有问题。这个命令行误导我了。而且还是美国vps。不知道ip到底有没有问题。我记得有一个检测gpt可用性的脚本。

**Comment by linweiyuan** [comment]
那个脚本就是个玩具
