### ISSUE TITLE
ERRO[0141] Failed to handle captcha: timeout after 1m0.085119078s  使用的时候报错

### ISSUE THREAD

**Issue by yayaQAQ** [linweiyuan/go-chatgpt-api#24]
ERRO[0141] Failed to handle captcha: timeout after 1m0.085119078s 

ERRO[0261] Failed to handle captcha: timeout after 1m0.013118863s 

这个是要去跳过验证码？怎么解决呢？

**Comment by linweiyuan** [comment]
参考：https://github.com/linweiyuan/go-chatgpt-api/issues/25#issuecomment-1510818536
