### ISSUE TITLE
418 Client challenge required

### ISSUE THREAD

**Issue by jsbxyyx** [linweiyuan/go-chatgpt-api#240]

**Comment by linweiyuan** [comment]
？

**Comment by jsbxyyx** [comment]
conversations 聊天接口返回http code 418

**Comment by linweiyuan** [comment]
报错时截个图，或者发下日志，没见过，问了其他人，说被 waf 拦了

需要更多信息排查

**Comment by resphinas** [comment]
> ？

你好请问你解决了吗 我也遇到了

**Comment by jsbxyyx** [comment]
> > ？
> 
> 你好请问你解决了吗 我也遇到了

没有解决。不知道怎么搞

**Comment by resphinas** [comment]
> > > ？
> > 
> > 
> > 你好请问你解决了吗 我也遇到了
> 
> 没有解决。不知道怎么搞

我解决了  IP问题 换了个个ip就可以了   你的也解决的话记得反馈下

**Comment by jsbxyyx** [comment]
> > > > ？
> > > 
> > > 
> > > 你好请问你解决了吗 我也遇到了
> > 
> > 
> > 没有解决。不知道怎么搞
> 
> 我解决了 IP问题 换了个个ip就可以了 你的也解决的话记得反馈下

你说的是proxy ip吗

**Comment by resphinas** [comment]
对



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 7, 2023 13:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [linweiyuan/go-chatgpt-api] 418 Client challenge required (Issue#240)




     
？
  
你好请问你解决了吗 我也遇到了
  
没有解决。不知道怎么搞
  
我解决了 IP问题 换了个个ip就可以了 你的也解决的话记得反馈下
  
你说的是proxy ip吗

**Comment by linweiyuan** [comment]
验证码出现程度和 IP 信誉度有关，这个只能治标，

但是怎样治本，不清楚

**Comment by resphinas** [comment]
干嘛要治本？既然知道是IP问题，换一个就能用了。



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 7, 2023 14:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [linweiyuan/go-chatgpt-api] 418 Client challenge required (Issue#240)




 
验证码出现程度和 IP 信誉度有关，这个只能治标，
 
但是怎样治本，不清楚

**Comment by linweiyuan** [comment]
当我没说
