### ISSUE TITLE
可以让imitate携带conversationId吗?

### ISSUE THREAD

**Issue by FishHawk** [linweiyuan/go-chatgpt-api#247]
ChatGPT3.5判断消息违规时不会返回内容，但仍然会记录在会话历史里面。通过请求会话历史可以突破ChatGPT的审查。

我希望使用imitate来减少带宽消耗，同时也需要请求会话历史突破审查。目前我只能请求整个会话列表，非常麻烦。

所以可以在imitate的回复里面添加conversationId吗？比方说，把目前回复里的随机的id替换成conversationId。

**Comment by FishHawk** [comment]
顺带一提，目前imitate出错的时候（比如触发每小时请求限制），返回的不是合法的json，长下面这样：
```
{
    "detail": "You've reached our limit of messages per hour. Please try again later."
}{
    "error": "error sending request"
}
```

**Comment by linweiyuan** [comment]
最近比较忙，可能要晚点时间看看

**Comment by CoolProgramme** [comment]
> 顺带一提，目前imitate出错的时候（比如触发每小时请求限制），返回的不是合法的json，长下面这样：
> 
> ```
> {
>     "detail": "You've reached our limit of messages per hour. Please try again later."
> }{
>     "error": "error sending request"
> }
> ```

问题已解决
