### ISSUE TITLE
启动容器后，看不到 8080 端口监听的进程

### ISSUE THREAD

**Issue by taylorwin** [linweiyuan/go-chatgpt-api#25]
/app # ls
go-chatgpt-api
/app # netstat -npt
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 172.17.0.6:42328        172.17.0.3:9515         ESTABLISHED 1/go-chatgpt-api

**Comment by linweiyuan** [comment]
`netstat -tnpl | grep 8080`

**Comment by taylorwin** [comment]
/app # netstat -npt
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 172.17.0.6:42328        172.17.0.3:9515         ESTABLISHED 1/go-chatgpt-api
/app # netstat -tnpl | grep 8080
/app #

**Comment by linweiyuan** [comment]
看下 `go-chatgpt-api` 的日志，你是用 docker 还是 compose 还是什么方式跑的？

**Comment by taylorwin** [comment]
docker  起的，

**Comment by linweiyuan** [comment]
warp 生效了，但是处理验证码失败了

验证码一般是偶尔弹，有时能处理有时就是这样报错，通常重启 API 就不弹验证码了

如果一直弹，可能是服务器 IP 被重点关注了

通常免费的节点会一直弹验证码，但是自己服务器就比较少见

我曾经用免费的节点测试过，会一直弹验证码，无论程序点还是人手点多少次

对于这种情况暂时我也无能为力

warp 会修改网络配置，不确定是否有关

https://user-images.githubusercontent.com/49076004/232409463-1990e8df-7c2e-4351-97b0-9d3805e5d9e8.mp4

**Comment by taylorwin** [comment]
应该是这个问题。看样，偶尔还要运气啊。

**Comment by taylorwin** [comment]
同一个 WARP，用 Chrome 手动打开游览器，验证都不弹。难道 CF又加强了验证？

**Comment by linweiyuan** [comment]
这个不是很清楚

**Comment by taylorwin** [comment]
代理要正常工作，需要三个容器 api   proxy  warp 这个有办法测试吗？ warp 正常与否可以用curl 代理。 
proxy 是我这里一直是  
sudo docker logs -f chatgpt-proxy-server
Starting ChromeDriver 111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Starting ChromeDriver 111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

API 是上面说的错误。

**Comment by linweiyuan** [comment]
至今没成功过吗？

哪个国家的服务器？

如果你晚上有空的话，可以提供服务器信息给我连下看看，不保证能解决

**Comment by taylorwin** [comment]
没有解决
1. warp 日志
/app # curl -sx "socks5://warp:1080" www.cloudflare.com/cdn-cgi/trace -k --connect-timeout 2
fl=523f61
h=www.cloudflare.com
ip=104.28.207.57
ts=1681888529.907
visit_scheme=http
uag=curl/8.0.1
colo=ICN
sliver=none
http=http/1.1
loc=KR
tls=off
sni=off
warp=on
gateway=off
rbi=off
kex=none
2. proxy 日志
sudo docker logs -f chatgpt-proxy-server
Starting ChromeDriver 111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Starting ChromeDriver 111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
3. api 日志
sudo docker logs -f go-chatgpt-api
今天拉了最新的颈项，一只是空。

由于服务器不是独立的不方便，谢谢。

**Comment by linweiyuan** [comment]
https://platform.openai.com/docs/supported-countries

韩国服务器似乎不在名单上，换一台试试
