### ISSUE TITLE
chatgpt接口的health_check失败，导致platform接口也不能用。

### ISSUE THREAD

**Issue by crazyqin** [linweiyuan/go-chatgpt-api#250]
这两个接口其实是独立的，chatgpt的health_check虽然失败，但是不影响platform的接口使用。
希望改一下。

**Comment by linweiyuan** [comment]
其实 platform 反而是附加的，因为完全可以直连官方

详细描述下你的使用场景，我看下是否合理，大概要怎么改

**Comment by crazyqin** [comment]
自己有4的api ，但是不能直连，所以需要这个接口部署到vps来中转… 试过几个中转的项目，只有这个能流式输出…

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月05日 22:52 |
| 收件人 | linweiyuan/go-chatgpt-api ***@***.***> |
| 抄送人 | crazyqin ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [linweiyuan/go-chatgpt-api] chatgpt接口的health_check失败，导致platform接口也不能用。 (Issue #250) |

其实 platform 反而是附加的，因为完全可以直连官方

详细描述下你的使用场景，我看下是否合理，大概要怎么改

**Comment by linweiyuan** [comment]
提示 Health check failed xxx？

**Comment by crazyqin** [comment]
Looks like you have bean blocked by OpenAI, please change to a new IP or have a try with WARP.

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月05日 23:03 |
| 收件人 | linweiyuan/go-chatgpt-api ***@***.***> |
| 抄送人 | crazyqin ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [linweiyuan/go-chatgpt-api] chatgpt接口的health_check失败，导致platform接口也不能用。 (Issue #250) |

提示 Health check failed xxx？

**Comment by linweiyuan** [comment]
有什么顾虑不用 warp 吗
