### ISSUE TITLE
可以在docker-compose里使用账号密码组来让他自动获取token吗？

### ISSUE THREAD

**Issue by Joackk** [linweiyuan/go-chatgpt-api#254]
想请问下大佬有这个功能吗？就是在docker的环境变量里写入账号密码（一个或多个），然后自动获取token，调用的时候就直接接口就行了

**Comment by linweiyuan** [comment]
不支持，完全可以用 cws 类似这种项目做到这个效果

**Comment by Joackk** [comment]
> 不支持，完全可以用 cws 类似这种项目做到这个效果

soga，感谢
