### ISSUE TITLE
没有提问几个问题就超限，是warp使用人数过多吗

### ISSUE THREAD

**Issue by chaoticjoy** [linweiyuan/go-chatgpt-api#26]
返回ChatGPT error 429: {"errorMessage":"Too many requests in 1 hour. Try again later."}错误

**Comment by linweiyuan** [comment]
这种情况，你试下登录网页版看是不是一样

如果你自己没提几个问题但是 429，要考虑下你的 accessToken 安全问题

**Comment by chaoticjoy** [comment]
@linweiyuan  经过几个账号的测试，发现是warp的对端ip问题，我重新建立一遍容器就可以了。顺便问一下，这里提供大的socks warp，是普通账号吗，是否可以切换team账号，对端ip是否可以像wireguard一样自己配置。

**Comment by chaoticjoy** [comment]
@linweiyuan 嗯，明白。仅仅用于chatgpt的话，普通账号够用了。后面你可以试试非官方的warp-go，配置会更灵活一些，但据说还是官方这个warp比较稳。

**Comment by linweiyuan** [comment]
好

**Comment by JamesFlare1212** [comment]
这不是问题，你可以本地跑一个warp-cli，加上WARP+的key，模式设置proxy，这样就是socks5了，直接用即可
