### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by Gavenvincent** [linweiyuan/go-chatgpt-api#260]
重新拉取最新镜像，但docker compose启动后，日志只有一句报错“failed to start ,please try again later”，重启还是同样的报错，大佬，这是怎么回事？

**Comment by linweiyuan** [comment]
如果报这个错，通常是官网不稳定，这个时候可以去官网看一眼，刷新几下看下是否正常

或者过段时间再试

**Comment by Gavenvincent** [comment]
好的👌🏻，感谢

**Comment by Gavenvincent** [comment]
1、研究了两天，VPS是美国的，测试连接openai网站正常，搭建VPN后还可以登录，但是发现登录后：历史无法显示，同时无法对话；
2、使用机场测试，同一个电脑和浏览器，倒是已经登录成功，不用再次登录，但这样可以进行正常对话，也没有一点问题，属实给我整懵了。
大佬，有什么建议吗？或者排查方向
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/49948282/33671582-99e2-483b-90f9-c672d836a224)


下面是正常的
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/49948282/b10d04e8-996f-4a75-b711-583671a57f29)

**Comment by linweiyuan** [comment]
F12

**Comment by linweiyuan** [comment]
这个像是前端项目的问题，这是哪个项目？

还有看下 Network 那里的报错

**Comment by Gavenvincent** [comment]
这是使用部署docker的VPS搭建的VPN访问https://chat.openai.com/，以前没有问题，但最近出现这个问题，然后就docker compose启动后，日志只有一句报错“failed to start ,please try again later”
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/49948282/dfa3831c-485b-4498-8130-9f4d5e08176b)

**Comment by Gavenvincent** [comment]
这是其中几个详情
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/49948282/93f9f9af-6c00-4634-b348-e1af9694477b)
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/49948282/b1b2cc3d-b050-4d90-ae1e-79af660b7a38)
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/49948282/47062cc3-2751-40d5-a757-9fa493efca73)

**Comment by linweiyuan** [comment]
不是很明白，但这个是不是不关 api 什么事，好像是梯子不行？

先不说那个 failed to start，那个启动成功与否取决于官网好不好使

**Comment by Gavenvincent** [comment]
嗯，是梯子的问题
