### ISSUE TITLE
refreshPuidErrorMessage

### ISSUE THREAD

**Issue by maxduke** [linweiyuan/go-chatgpt-api#261]
第一次运行时候可以正常获取到PUID。7天之后第二次跑在以下地方报错 (自己加了log)
https://github.com/maxduke/go-chatgpt-api/blob/f7e46aa457797af228fc0bee757d6c25903539db/api/chatgpt/api.go#L256

>go-chatgpt-api  | ERRO[604808] Failed to refresh PUID.: Failed to execute request: <nil>
>go-chatgpt-api  | ERRO[604808] Failed to refresh PUID.: Status code: 403

**Comment by linweiyuan** [comment]
有个简单粗暴的方法，每次刷新都新建一个 client，用完即弃，可以尝试下
