### ISSUE TITLE
更新了最新的镜像版本，还是报错nil和403

### ISSUE THREAD

**Issue by Alex-Joe-Lee** [linweiyuan/go-chatgpt-api#266]
INFO[0000] PROXY: socks5://chatgpt-proxy-server-warp:65535
set proxy to: socks5://chatgpt-proxy-server-warp:65535
<nil>
set proxy to: socks5://chatgpt-proxy-server-warp:65535
ERRO[0000] failed to start, please try again later: 403 Forbidden

**Comment by Nothingness-Void** [comment]
> 重试多少次都是一样吗

最新镜像access token能够使用 但是账号密码登录会报错

**Comment by Alex-Joe-Lee** [comment]
> 重试多少次都是一样吗

不好意思，应该是token填错了。。。

**Comment by zsanjin-p** [comment]
> 重试多少次都是一样吗

一键部署也报错了：Sep 28 01:35:42 AM  ==> It looks like we don't have access to your repo, but we'll try to clone it anyway.
Sep 28 01:35:42 AM  ==> Cloning from https://github.com/linweiyuan/go-chatgpt-api...
Sep 28 01:35:42 AM  ==> Checking out commit 47f92fd8fc2f2e8d9cdcf8dd5709b170cad1c326 in branch main
Sep 28 01:35:46 AM  ==> Using Node version 14.17.0 (default)
Sep 28 01:35:46 AM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Sep 28 01:35:46 AM  ==> Using Go version go version go1.20.5 linux/amd64
Sep 28 01:35:46 AM  ==> Running build command 'go build -ldflags="-w -s" -o go-chatgpt-api main.go'...
Sep 28 01:35:46 AM  go: errors parsing go.mod:
Sep 28 01:35:46 AM  /opt/render/project/go/src/github.com/linweiyuan/go-chatgpt-api/go.mod:3: invalid go version '1.21.1': must match format 1.23
Sep 28 01:35:46 AM  ==> Build failed 😞

**Comment by linweiyuan** [comment]
其实我还没用过这个一键部署

**Comment by zsanjin-p** [comment]
> 其实我还没用过这个一键部署

cb90b81这个版本部署没问题
