### ISSUE TITLE
登录获取access token似乎还是有问题

### ISSUE THREAD

**Issue by xbl916** [linweiyuan/go-chatgpt-api#267]
手动获取access token在第三方应用可以正常使用
通过账号密码获取access token似乎还是异常
[GIN] 2023/09/27 - 15:45:31 | 403 |  2.253964242s |      172.19.0.1 | POST     "/chatgpt/backend-api/login"
[GIN] 2023/09/27 - 15:46:35 | 403 |  2.276834088s |      172.19.0.1 | POST     "/chatgpt/backend-api/login"
WARN[52187] failed to get access token        
[GIN] 2023/09/27 - 15:47:39 | 403 |  2.195516713s |      172.19.0.1 | POST     "/chatgpt/backend-api/login"
WARN[52251] failed to get access token        
WARN[52315] failed to get access token        
[GIN] 2023/09/27 - 15:48:43 | 403 |  2.242533693s |      172.19.0.1 | POST     "/chatgpt/backend-api/login"
WARN[52379] failed to get access token

**Comment by linweiyuan** [comment]
是有问题啊，国庆修复

**Comment by linweiyuan** [comment]
已修复
