### ISSUE TITLE
不支持vercel吗

### ISSUE THREAD

**Issue by zg601x** [linweiyuan/go-chatgpt-api#270]
<html>
<body>

在美国华盛顿特区（东部）运行构建 – iad1 (Hive)
--
12:17:51.835 | 克隆 github.com/zg601x/go-chatgpt-api （分支：main，提交：54b43d9）
12:17:52.121 | 克隆完成：285.713ms
12:17:52.188 | 以前的构建缓存不可用
12:17:52.338 | 运行“vercel构建”
12:17:52.804 | Vercel CLI 32.3.1
12:17:53.032 | 警告：/vercel/path0/go.mod 中的未知 Go 版本
12:17:53.048 | 下载go：https://dl.google.com/go/go1.21.1.linux-amd64.tar.gz
12:18:07.249 | 在“api/chatgpt/api.go”中找不到导出函数
12:18:07.250 | 了解更多：https://vercel.com/docs/runtimes#official-runtimes/go
12:18:07.250 |  
12:18:08.398 | 错误：在“api/chatgpt/api.go”中找不到导出函数
12:18:08.398 | 了解更多：https://vercel.com/docs/runtimes#official-runtimes/go

</body>
</html>

**Comment by linweiyuan** [comment]
不支持，没用过
