### ISSUE TITLE
大神回复真快

### ISSUE THREAD

**Issue by zg601x** [linweiyuan/go-chatgpt-api#271]
但是怎么这么快就关了，我试了render一键部署也失败了，记得之前还可以

**Comment by linweiyuan** [comment]
#266

**Comment by zg601x** [comment]
render一键部署好像是只部署api服务器啊（我记得之前是这样的，访问主域名就是***is ready）,之前不用输入token就能部署

**Comment by linweiyuan** [comment]
看最后一个回复，用那个版本去部署

**Comment by zg601x** [comment]
Oct 3 12:57:53 PM  go: errors parsing go.mod:
Oct 3 12:57:53 PM  /opt/render/project/go/src/github.com/linweiyuan/go-chatgpt-api/go.mod:3: invalid go version '1.21.1': must match format 1.23
Oct 3 12:57:53 PM  ==> Build failed 😞
这个版本我研究下

**Comment by zg601x** [comment]
免费版本不支持手动shell

**Comment by linweiyuan** [comment]
没用过这个 render，但是看这个报错，可以改 go.mod 里的 1.21.1 为 1.21 试一下

**Comment by zg601x** [comment]
谢谢大佬，这就试试

**Comment by zg601x** [comment]
成功了，使用你的最新版本都行，只要改一下mod文件的1.21.1改为1.21

**Comment by linweiyuan** [comment]
提 pr 回来我合并

**Comment by zg601x** [comment]
是这样吗，我还没提交过
