### ISSUE TITLE
这个怎么使用，我点了render按钮。部署成功后返回service go-chatgpt-api is ready信息。

### ISSUE THREAD

**Issue by ingxhe** [linweiyuan/go-chatgpt-api#273]
草拟麻痹，写给你吗比看的吗

**Comment by ingxhe** [comment]
到底怎么用

**Comment by ingxhe** [comment]
就我是傻逼，不知道怎么用吗？

**Comment by ingxhe** [comment]
这个不是提供自己的账号密码，就可以使用api的吗？

我点了一键部署，没有让我输入账号密码。

**Comment by ingxhe** [comment]
有没有类似的产品，我受够你这几把了

**Comment by linweiyuan** [comment]
回去问你妈

**Comment by ingxhe** [comment]
> 回去问你妈

对不起。
如果我要集成到ChatGPT-Next-Web，把环境变量改成BASE_URL=http://go-chatgpt-api:8080/imitate。我在哪里输入openai的账号密码
