### ISSUE TITLE
最新版镜像报错422，"none is not an allowed value"

### ISSUE THREAD

**Issue by zeushera140** [linweiyuan/go-chatgpt-api#274]
MacOS, anaconda 虚拟环境，Python3.9，go version go1.21.1 darwin/amd64

试了render的版本，也一样

APIError: Invalid response object from API: '{"detail":[{"loc":["body","messages",0,"metadata"],"msg":"none is not an allowed value","type":"type_error.none.not_allowed"}]}' (HTTP response code was 422)

请输入： how to prompt Chatgpt for English Chinese translating
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/opt/anaconda3/envs/gpt/lib/python3.9/site-packages/openai/api_requestor.py:413, in APIRequestor.handle_error_response(self, rbody, rcode, resp, rheaders, stream_error)
    412 try:
--> 413     error_data = resp["error"]
    414 except (KeyError, TypeError):

KeyError: 'error'

During handling of the above exception, another exception occurred:

APIError                                  Traceback (most recent call last)
Cell In[76], line 8
      6 while True:
      7     text = input("请输入：")
----> 8     response = openai.ChatCompletion.create(
      9         model='gpt-3.5-turbo',
     10         messages=[
     11             {'role': 'user', 'content': text},
     12         ],
     13         stream=True
     14     )
     16     for chunk in response:
     17         print(chunk.choices[0].delta.get("content", ""), end="", flush=True)

File ~/opt/anaconda3/envs/gpt/lib/python3.9/site-packages/openai/api_resources/chat_completion.py:25, in ChatCompletion.create(cls, *args, **kwargs)
     23 while True:
     24     try:
---> 25         return super().create(*args, **kwargs)
     26     except TryAgain as e:
     27         if timeout is not None and time.time() > start + timeout:

File ~/opt/anaconda3/envs/gpt/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py:155, in EngineAPIResource.create(cls, api_key, api_base, api_type, request_id, api_version, organization, **params)
    129 @classmethod
    130 def create(
    131     cls,
   (...)
    138     **params,
    139 ):
    140     (
    141         deployment_id,
    142         engine,
   (...)
    152         api_key, api_base, api_type, api_version, organization, **params
    153     )
--> 155     response, _, api_key = requestor.request(
    156         "post",
    157         url,
    158         params=params,
    159         headers=headers,
    160         stream=stream,
    161         request_id=request_id,
    162         request_timeout=request_timeout,
    163     )
    165     if stream:
    166         # must be an iterator
    167         assert not isinstance(response, OpenAIResponse)

File ~/opt/anaconda3/envs/gpt/lib/python3.9/site-packages/openai/api_requestor.py:299, in APIRequestor.request(self, method, url, params, headers, files, stream, request_id, request_timeout)
    278 def request(
    279     self,
    280     method,
   (...)
    287     request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    288 ) -> Tuple[Union[OpenAIResponse, Iterator[OpenAIResponse]], bool, str]:
    289     result = self.request_raw(
    290         method.lower(),
    291         url,
   (...)
    297         request_timeout=request_timeout,
    298     )
--> 299     resp, got_stream = self._interpret_response(result, stream)
    300     return resp, got_stream, self.api_key

File ~/opt/anaconda3/envs/gpt/lib/python3.9/site-packages/openai/api_requestor.py:710, in APIRequestor._interpret_response(self, result, stream)
    702     return (
    703         self._interpret_response_line(
    704             line, result.status_code, result.headers, stream=True
    705         )
    706         for line in parse_stream(result.iter_lines())
    707     ), True
    708 else:
    709     return (
--> 710         self._interpret_response_line(
    711             result.content.decode("utf-8"),
    712             result.status_code,
    713             result.headers,
    714             stream=False,
    715         ),
    716         False,
    717     )

File ~/opt/anaconda3/envs/gpt/lib/python3.9/site-packages/openai/api_requestor.py:775, in APIRequestor._interpret_response_line(self, rbody, rcode, rheaders, stream)
    773 stream_error = stream and "error" in resp.data
    774 if stream_error or not 200 <= rcode < 300:
--> 775     raise self.handle_error_response(
    776         rbody, rcode, resp.data, rheaders, stream_error=stream_error
    777     )
    778 return resp

File ~/opt/anaconda3/envs/gpt/lib/python3.9/site-packages/openai/api_requestor.py:415, in APIRequestor.handle_error_response(self, rbody, rcode, resp, rheaders, stream_error)
    413     error_data = resp["error"]
    414 except (KeyError, TypeError):
--> 415     raise error.APIError(
    416         "Invalid response object from API: %r (HTTP response code "
    417         "was %d)" % (rbody, rcode),
    418         rbody,
    419         rcode,
    420         resp,
    421     )
    423 if "internal_message" in error_data:
    424     error_data["message"] += "\n\n" + error_data["internal_message"]

APIError: Invalid response object from API: '{"detail":[{"loc":["body","messages",0,"metadata"],"msg":"none is not an allowed value","type":"type_error.none.not_allowed"}]}' (HTTP response code was 422)

**Comment by linweiyuan** [comment]
更新看看
