### ISSUE TITLE
提问后拿不到结果

### ISSUE THREAD

**Issue by tts2** [linweiyuan/go-chatgpt-api#276]
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/11350647/5a920038-6e93-4738-9fe1-ce70270c5a36)

**Comment by linweiyuan** [comment]
发这个项目的完整配置看有没有问题

目前简单看到的问题就是 127.0.0.1 指向容器自己，至于怎么改，翻下汇总 issue

**Comment by tts2** [comment]
没有用docker呀
环境变量
PROXY=http://127.0.0.1:7890
PORT=8037
cmd 命令
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn,direct
go run main.go
大佬wx群联系不到您了

**Comment by linweiyuan** [comment]
这个报错是你的网络不行，这个我解决不了

**Comment by tts2** [comment]
果然是网络问题,谢谢大佬
