### ISSUE TITLE
chatgpt login err

### ISSUE THREAD

**Issue by dvc890** [linweiyuan/go-chatgpt-api#277]
```
Oct 8 03:32:43 PM  Error getting auth Arkose token
Oct 8 03:32:43 PM  WARN[0097] a valid HAR file required
Oct 8 03:32:43 PM  [GIN] 2023/10/08 - 07:32:43 | 200 |  1.030630639s |   112.96.55.120 | POST     "/chatgpt/backend-api/login"
Oct 8 03:33:10 PM  Error getting auth Arkose token
Oct 8 03:33:10 PM  WARN[0125] a valid HAR file required
Oct 8 03:33:10 PM  [GIN] 2023/10/08 - 07:33:10 | 200 |  886.984413ms |   112.96.55.120 | POST     "/chatgpt/backend-api/login"
```
使用最新代码也无法通过接口登陆chatgpt账号
请求：`curl -X POST -H "Content-Type: application/json" -d '{ "username": "xx@xx.com", "password": "password" }' https://go-chatgpt-api.com/chatgpt/backend-api/login`
结果：`{"errorMessage":"a valid HAR file required"}%  `

**Comment by linweiyuan** [comment]
不支持 render

**Comment by dvc890** [comment]
> 不支持 render

这是什么意思？

**Comment by linweiyuan** [comment]
现在的登录需要一个叫 har 的东西，部署在 render 的话，没有地方配置 har

**Comment by dvc890** [comment]
> 现在的登录需要一个叫 har 的东西，部署在 render 的话，没有地方配置 har

那有相关教程吗？我不太了解这个叫har的东西

**Comment by linweiyuan** [comment]
文档里的博客里有

**Comment by developer-vtnetzwelt** [comment]
@dvc890 I'm facing the same issue, were you to resolve the error?

**Comment by ludashi2020** [comment]
`curl -X POST -F "file=@chat.openai.com.har" -F "data={\"username\":\"xx@gmail.com\",\"password\":\"xxxx\"}" http://127.0.0.1:8080/chatgpt/login`
`{"errorMessage":"failed to parse user login info"}` 登录失败是什么原因？

**Comment by linweiyuan** [comment]
谁教你这样用登录接口的

不知道是不是别的项目要这样，这个项目的话，har 要手动挂载，程序启动时就解析了，不是登录的时候上传，详细可以参考博客视频

**Comment by ludashi2020** [comment]
pandora登录的时候可以返回access_token `curl -X POST https://ai.fakeopen.com/auth/login -F "username=xx@gmail.com" -F "password=xxxx" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
{"access_token":"xxx","refresh_token":"xxx","scope":"openid profile email model.read model.request organization.read offline_access","token_type":"Bearer"}`  现在这个http://127.0.0.1:8080/chatgpt/login接口登录不了

**Comment by linweiyuan** [comment]
实现不同，这个已经不维护了，可以继续用潘多拉
