### ISSUE TITLE
tcr9i.chat.openai.com  connect: connection timed out

### ISSUE THREAD

**Issue by littlepese** [linweiyuan/go-chatgpt-api#278]
GPT-3.5正常 能正常使用，GPT-4 一直都是超时
机器在国内，设置了代理

日志如下
go-chatgpt-api2  | success read chat arkose
go-chatgpt-api2  | success read chat arkose
go-chatgpt-api2  | success read chat arkose
go-chatgpt-api2  | INFO[0000] PROXY: socks5://172.17.0.1:1086
go-chatgpt-api2  | INFO[0000] service go-chatgpt-api is ready
go-chatgpt-api2  | [GIN] 2023/10/11 - 19:21:33 | 200 |  1.940335285s |   192.168.160.1 | GET      "/chatgpt/backend-api/conversation/ec3f9a84-83b0-419c-9ede-7ca6dc4a68b2"
go-chatgpt-api2  | [GIN] 2023/10/11 - 19:21:44 | 403 |          2m7s |   192.168.160.1 | POST     "/chatgpt/backend-api/conversation"
go-chatgpt-api2  | WARN[0144] Post "https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147": dial tcp 128.242.240.117:443: connect: connection timed out
go-chatgpt-api2  | [GIN] 2023/10/11 - 19:26:50 | 403 |          2m7s |   192.168.160.1 | POST     "/chatgpt/backend-api/conversation"
go-chatgpt-api2  | WARN[0451] Post "https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147": dial tcp 128.242.240.117:443: connect: connection timed out
go-chatgpt-api2  | WARN[1283] Post "https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147": dial tcp 199.59.148.229:443: connect: connection timed out
go-chatgpt-api2  | [GIN] 2023/10/11 - 19:40:42 | 403 |          2m7s |   192.168.160.1 | POST     "/chatgpt/backend-api/conversation"

**Comment by linweiyuan** [comment]
装个 curl 试试

**Comment by littlepese** [comment]
用 curl 直接访问是没问题的

# curl -X post -x socks5://127.0.0.1:1086 https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

**Comment by littlepese** [comment]
post 忘了大写了，重新贴一下，curl 访问不会出现超时
# curl -X POST -x socks5://127.0.0.1:1086 -I  https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147
HTTP/2 400
date: Thu, 12 Oct 2023 01:19:42 GMT
content-length: 0
cf-ray: 814b84223fa6c17d-ICN
cf-cache-status: DYNAMIC
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubDomains
content-security-policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' cdn.funcaptcha.com cdn.arkoselabs.com data:; media-src 'self' data:; connect-src 'self'
hackers: www.arkoselabs.com/whitehat/
referrer-policy: strict-origin-when-cross-origin
sregion: ap-southeast-1
version: 2.0
x-content-type-options: nosniff
x-envoy-upstream-service-time: 3
x-xss-protection: 1; mode=block
set-cookie: _cfuvid=pX4kXWsG6cjP9qNOBZH0sMks.HmMqw3CqWkwIytSlyM-1697073582526-0-604800000; path=/; domain=.tcr9i.chat.openai.com; HttpOnly; Secure; SameSite=None
server: cloudflare
alt-svc: h3=":443"; ma=86400

**Comment by linweiyuan** [comment]
有点奇怪，今晚看看

**Comment by linweiyuan** [comment]
无法复现

**Comment by littlepese** [comment]
发现问题了，PROXY这个变量不行，多加一个 http_proxy 的变量就行了

贴下配置
  go-chatgpt-api2:
    container_name: go-chatgpt-api2
    image: linweiyuan/go-chatgpt-api:latest
    ports:
      - 2489:8080
    environment:
      - TZ=Asia/Shanghai
      - PROXY=socks5://172.17.0.1:1086
      - GIN_MODE=release
      - http_proxy=socks5://172.17.0.1:1086
    volumes:
      - ./arkoselabs_token_api/chat.openai.com.har:/app/chat.openai.com.har
    restart: unless-stopped

**Comment by linweiyuan** [comment]
为何我试不出来

**Comment by littlepese** [comment]
我的是国内的机器，网络完全不能翻墙，代理是通过 clash 搭的。不知道什么情况。
