### ISSUE TITLE
大佬后续会支持gpt-4-dalle吗

### ISSUE THREAD

**Issue by yitd** [linweiyuan/go-chatgpt-api#284]
看到隔壁https://github.com/xqdoo00o/ChatGPT-to-API 已经支持了，gpt-4-browsing也完善了，但是没有这个程序好用，大佬后续还会更新吗

**Comment by linweiyuan** [comment]
现在我只有晚上十点后和周末才能碰自己的电脑，估计不会更了，除非我到新工作

**Comment by linweiyuan** [comment]
现在我只有晚上十点后和周末才能碰自己的电脑，估计不会更了，除非我换到新工作
