### ISSUE TITLE
您好，请问下这个可以做chatgpt Access Token 访问的代理么？有对应教程么？

### ISSUE THREAD

**Issue by weew2** [linweiyuan/go-chatgpt-api#29]
您好，请问下这个可以做chatgpt Access Token 访问的代理么？有对应教程么？

**Comment by linweiyuan** [comment]
支持的

使用方法和其他的代理没有什么大的差别，改下 URL 配置即可

**Comment by weew2** [comment]
> 

您好，我直接使用 go install github.com/linweiyuan/go-chatgpt-api@latest 这种方式在服务器生成可运行文件

然后通过  nohup ./go-chatgpt-api &  启动之后，出现了以下错误

[GIN-debug] Listening and serving HTTP on :8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x7a362b]

goroutine 8 [running]:
github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh.func1()
        /usr/local/go_project/pkg/mod/github.com/linweiyuan/go-chatgpt-api@v0.0.0-20230417010409-a49635aa00ff/webdriver/refresh.go:13 +0x2b
created by github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh
        /usr/local/go_project/pkg/mod/github.com/linweiyuan/go-chatgpt-api@v0.0.0-20230417010409-a49635aa00ff/webdriver/refresh.go:12 +0x6a

请问下，这种错误的原因是什么？

**Comment by weew2** [comment]
> 本地需要后台跑 `chromedriver`，如果不设置环境变量 `CHATGPT_PROXY_SERVER`，则默认使用 `apiKey` 模式
> 
> 其实你可以看下 `README` 或者里面博客的视频
> 
> 问个题外话，为何不用 `docker` 或 `compose`？

好的，谢谢了。    

不太喜欢用docker的方式，觉得比较废资源
