### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid

### ISSUE THREAD

**Issue by whiteple** [linweiyuan/go-chatgpt-api#30]
大佬请问一下，这个报错是为什么？
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'chatgpt-proxy-server'

**Comment by linweiyuan** [comment]
需要把配置文件内容贴出来才知道是什么错，删掉敏感信息

**Comment by time-river** [comment]
change docker-compose.yaml, from:
```
services:
```
to
```
version: '3'

services:
```

Notice `version: '3'`

**Comment by whiteple** [comment]
> change docker-compose.yaml, from:
> 
> ```
> services:
> ```
> 
> to
> 
> ```
> version: '3'
> 
> services:
> ```
> 
> Notice `version: '3'`

改了之后确实可以跑起来了，但是还有点问题，我先研究研究，谢谢两位大佬
