### ISSUE TITLE
pthread_create: Operation not permitted (1)

### ISSUE THREAD

**Issue by yg9538** [linweiyuan/go-chatgpt-api#31]
[1681713279.028][SEVERE]: pthread_create: Operation not permitted (1)
Starting ChromeDriver 111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1681719833.469][SEVERE]: pthread_create: Operation not permitted (1)
 docker 启动报的错误

**Comment by linweiyuan** [comment]
正常日志，并不是报错

**Comment by yg9538** [comment]
好的，谢谢

**Comment by time-river** [comment]
switch to `docker.io` instead of docker-ce in debian 11 or ubuntu 22.04.
It's okay.

**Comment by yg9538** [comment]
thx！

**Comment by Peterpig** [comment]
另一个解决方案：加一下 privileged: true
![image](https://github.com/linweiyuan/go-chatgpt-api/assets/7956973/54f1daef-4954-4304-a838-5d07a4b68bea)
