### ISSUE TITLE
Failed to handle captcha: timeout after 1m0.110652176s

### ISSUE THREAD

**Issue by WuYunfan** [linweiyuan/go-chatgpt-api#32]
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/31981885/232488624-b31ed430-b0fe-4a0e-b8d6-7743b36d78b0.png">
这里显示Failed to handle captcha然后就Access denied了，但是我用这个服务器上的v2ray代理直接访问chat.openai.com可以正常登录上去。
没有挂warp，使用的配置是：

`version: "3"

services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080 # 如果你需要暴露端口如一带多，可以取消注释
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      # - NETWORK_PROXY_SERVER=http://host:port
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped`

**Comment by WuYunfan** [comment]
找到原因了，因为我在服务器里搭了tunnelbroker的ipv6隧道，我把这个关掉之后，v2ray也访问不了。能有办法让go-chatgpt-api走这个tunnelbroker的ipv6吗

**Comment by linweiyuan** [comment]
这个我没玩过不太懂

**Comment by purepoorx** [comment]
我也是这个问题，warp的socks代理，我用自己电脑的v2rayn连，都能打开https://chat.openai.com，但在docker里，就是一直卡Failed to handle captcha

**Comment by WuYunfan** [comment]
version: "3"

services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://127.0.0.1:9515
      # - NETWORK_PROXY_SERVER=http://host:port
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped
    network_mode: host

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped
    network_mode: host

我通过这个配置解决了，在doker里直接用外部的ipv6访问openai。
