### ISSUE TITLE
selenium error: panic, need to create a new session and refresh

### ISSUE THREAD

**Issue by hncboy** [linweiyuan/go-chatgpt-api#33]
railway 部署
![image](https://user-images.githubusercontent.com/27755574/232559753-a9462b60-136a-49ca-96f4-73b28a4d195b.png)

**Comment by sam-hieken** [comment]
遇到同样的问题 I have the same problem

**Comment by linweiyuan** [comment]
`go-chatgpt-api` 和 `chatgpt-proxy-server` 缺一不可，两个都要部署并保证都在运行

先 `proxy` 再 `api`，有依赖

没用过 `railway`，可以把 `compose.yaml` 叫 `ChatGPT` 转成 `docker` 命令

---

不保证稳定运行，不行的话，重启 `api`

**Comment by chijiao** [comment]
同样的问题

**Comment by Haibersut** [comment]
看看issue #22

**Comment by HasakiZoro** [comment]
本地docker部署同样问题，proxy-server正常运行

**Comment by HasakiZoro** [comment]
> "selenium error: panic, need to create a new session and refresh"
> 
> 还有这个错误提示？需要拉下镜像

删除重拉了还是这个报错

**Comment by linweiyuan** [comment]
拉了个假镜像，我把这个日志都删除了

**Comment by linweiyuan** [comment]
看看你删除和拉新镜像的命令

**Comment by linweiyuan** [comment]
chatgpt-proxy-server 这个也可以拉下，我加了日志

**Comment by HasakiZoro** [comment]
> 

![err](https://user-images.githubusercontent.com/124870408/233307069-96f2759d-8d69-4467-922f-310fd2b7ef44.png)
我设备是NAS，在docker界面操作删除后，用dockerhub界面的命令重新拉的，现在还是这个报错

**Comment by linweiyuan** [comment]
chatgpt-proxy-server 和 go-chatgpt-api 如果是最新的话，看下 chatgpt-proxy-server 的日志

先启动 proxy，再启动 api

或者可以的话找个时间可以给我远程看下，比如 todesk，不会收费的

**Comment by HasakiZoro** [comment]
> 

chatgpt-proxy-server的日志是正常的
![proxy-server-log](https://user-images.githubusercontent.com/124870408/233319034-930ae399-eb32-493f-b6f2-31d5b4e85d73.png)

**Comment by linweiyuan** [comment]
确定是最新的镜像吗，chatgpt-proxy-server，昨晚我修改了下启动命令开启了啰嗦模式重新打了个包推了上去，启动应该有很多输出才对，不会这样一句话不说

第六感是打开方式不对
