### ISSUE TITLE
请问一下，这是什么报错

### ISSUE THREAD

**Issue by nikissXI** [linweiyuan/go-chatgpt-api#34]
请问一下，报404是啥情况
![image](https://user-images.githubusercontent.com/31379266/232560124-7730cce2-b2ad-4f9e-bd65-726c96d87125.png)

**Comment by dqzboy** [comment]
我目前也是这种情况，是不是镜像不能用了呢

**Comment by dqzboy** [comment]
> 我目前也是这种情况，是不是镜像不能用了呢

我的可以了，VPS节点IP要稳定，如果节点IP没有被ban则选择使用ChatGPT和API 模式

**Comment by linweiyuan** [comment]
@nikissXI 要看下你怎么配的 `URL` 才知道为什么 `404`

一般是配错了

`chatgpt-web` 项目要配置 `conversaion` 在后面，`http(s):/ip:host/conversation`

**Comment by nikissXI** [comment]
@linweiyuan 
配置是这样的
![image](https://user-images.githubusercontent.com/31379266/232664916-2f25862b-b8e7-4845-bf32-141b7d3d76e1.png)
chatgpt web的api地址
![image](https://user-images.githubusercontent.com/31379266/232665083-f2e071a0-1621-4dd5-a103-76aca1009069.png)

**Comment by nikissXI** [comment]
> > 我目前也是这种情况，是不是镜像不能用了呢
> 
> 我的可以了，VPS节点IP要稳定，如果节点IP没有被ban则选择使用ChatGPT和API 模式

用梯子行不行的（clash）

**Comment by linweiyuan** [comment]
@nikissXI 配置错了，正确的配置：`API_REVERSE_PROXY: http://127.0.0.1:12345/conversation`

**Comment by nikissXI** [comment]
> @nikissXI 配置错了，正确的配置：`API_REVERSE_PROXY: http://127.0.0.1:12345/conversation`

好的，刚改了
重新测试，还是不会回，我看clash的日志，走回去本地地址了？
![image](https://user-images.githubusercontent.com/31379266/232667385-a270ad78-3821-4db0-be53-c9bb12d2f768.png)

**Comment by nikissXI** [comment]
可以啦，谢谢谢谢！！！！！！！！！！！！

**Comment by guoguo163** [comment]
不能用，从老版升级来 ，确认网络环境可以直接访问
![165204](https://github.com/linweiyuan/go-chatgpt-api/assets/34234063/93215750-1158-4b54-8294-0d827ef0be59)

**Comment by guoguo163** [comment]
![170351](https://github.com/linweiyuan/go-chatgpt-api/assets/34234063/30a08538-5121-47eb-9dde-e75b18438118)
重新获取了token

**Comment by linweiyuan** [comment]
/chatgpt/conversation

**Comment by guoguo163** [comment]
额，可以了，之前看文档改成了/chatgpt/conversation，后面调试不知道什么时候又用回了之前的/conversation
