### ISSUE TITLE
基于大佬的项目，写的搭建教程供参考

### ISSUE THREAD

**Issue by dqzboy** [linweiyuan/go-chatgpt-api#35]
基于大佬的项目，写了一篇比较详细的搭建教程，供大家自行搭建参考[ChatGPT-Porxy](https://github.com/dqzboy/ChatGPT-Porxy)

**Comment by huangwb8** [comment]
@dqzboy 

感谢大佬！ 要是早2天出就不用那么折腾了 (ฅ´ω`ฅ) 

我昨天也总结了经验。 我还尝试了在本地nas/linux里使用该项目，可以很好地和原有的节点搭配。 具体见：  https://blognas.hwb0307.com/linux/docker/4201

**Comment by bigBoyooooooo** [comment]
感谢大佬
