### ISSUE TITLE
科学上网的那个ip和端口配置在哪个参数里 还是需要把科学上网设置成全局代理

### ISSUE THREAD

**Issue by lizhongyuan3** [linweiyuan/go-chatgpt-api#37]

**Comment by linweiyuan** [comment]
`NETWORK_PROXY_SERVER`

**Comment by linweiyuan** [comment]
谈到科学上网，应该是本地跑？

本地跑设置 `NETWORK_PROXY_SERVER` 为科学地址

本地跑设置 `warp` 没有效果，会报错

---

如果是在服务器上跑，那么默认已经带科学环境，这个参数则用来设置 `warp`，不冲突
