### ISSUE TITLE
timeout是因为什么情况

### ISSUE THREAD

**Issue by nikissXI** [linweiyuan/go-chatgpt-api#39]
![image](https://user-images.githubusercontent.com/31379266/232727925-18061ea9-6919-46d6-8cec-d20d0507375a.png)

**Comment by linweiyuan** [comment]
这个错误就是处理不了验证码

不保证完美处理，偶尔能处理，处理不了一般重启 `api` 恢复正常

再不行目前也没有好办法，这个项目只是凑合用，可能要学习更多知识来解决这个问题

**Comment by nikissXI** [comment]
好的，谢谢大佬

**Comment by nikissXI** [comment]
可以做一个异常返回吗，比如超时，错误啥的，告诉前端是不是出错了。现在出了异常不看日志都不知道发生什么事情

**Comment by linweiyuan** [comment]
正常请求 `api`，比如对话，会有异常提示

但是这个是后台定时自动刷新 `cookie`，如果这一次执行有错误，那么怎么通知到前端呢？

如果刷新的时候，前端没开呢？也收不到

**Comment by nikissXI** [comment]
> 正常请求 `api`，比如对话，会有异常提示
> 
> 但是这个是后台定时自动刷新 `cookie`，如果这一次执行有错误，那么怎么通知到前端呢？
> 
> 如果刷新的时候，前端没开呢？也收不到

如果是我的话，会新建一个bool值变量叫error默认False，如果出现报错，则把该值改为True，并用一个字符串变量保存错误信息，前端请求就返回该错误信息

**Comment by linweiyuan** [comment]
那不还是请求才返回吗

但是请求如果有错本来就会返回

**Comment by nikissXI** [comment]
> 那不还是请求才返回吗
> 
> 但是请求如果有错本来就会返回

昨天那个情况是，如果access denied或验证码拉取超时，没有返回任何信息，我看docker日志才知道发生了什么

**Comment by linweiyuan** [comment]
我把处理验证码超时日志去掉了，本来是方便开发调试，但是现在好像造成了误导

Access denied 这个错误启动的时候就会输出了，如果正常使用，中途变了这个，属于特殊情况

目前不太好改

**Comment by nikissXI** [comment]
> 我把处理验证码超时日志去掉了，本来是方便开发调试，但是现在好像造成了误导
> 
> Access denied 这个错误启动的时候就会输出了，如果正常使用，中途变了这个，属于特殊情况
> 
> 目前不太好改

哦哦。。。
