### ISSUE TITLE
响应不及时

### ISSUE THREAD

**Issue by superen7527** [linweiyuan/go-chatgpt-api#4]
一般来说 回答的时候会显示 Stop Responding 按钮，但是结束以后会自动消失

但是反代用该项目的接口 会延迟十秒钟左右才消失，并且偶尔会有光标不跟着文字动一直停在最后右下角闪烁的情况(比较少)。

用社区两个接口就没有该问题，所以提到这里，看能不能复现，没有测试java版

**Comment by linweiyuan** [comment]
我没有开 plus，如果你认识谁有 plus 账号，可以借来玩玩，造福广大群众

**Comment by superen7527** [comment]
https://github.com/Chanzhaoyu/chatgpt-web/issues/1010
接口返回的json里面有个finish_reason字段，"finish_reason":""的时候是还在生成，"finish_reason":"stop"是最后一个包。


能不能根据这个停止响应

**Comment by linweiyuan** [comment]
token 和 api 都可以设置一次返回所有还是一个个返回

如果 token 设置一次返回所有，那么就不会延迟，延迟你也不知道，但是没有打字效果

api 因为可以直连没有 cf 验证，所以就算一个个返回，也不会出现延迟，因为是直线救国

---

为什么不能整合，在那个 web 项目里回复了

其实你可以自己整一个，把 Go 程序复制到 proxy 里面去，调整下启动命令，理论上可以跑

**Comment by superen7527** [comment]
好的 昨天邮件太多了 你是引用回复我看混了 以为那是旧的通知没注意到


> token 和 api 都可以设置一次返回所有还是一个个返回
> 
> 如果 token 设置一次返回所有，那么就不会延迟，延迟你也不知道，但是没有打字效果
> 
> api 因为可以直连没有 cf 验证，所以就算一个个返回，也不会出现延迟，因为是直线救国
> 
> 为什么不能整合，在那个 web 项目里回复了
> 
> 其实你可以自己整一个，把 Go 程序复制到 proxy 里面去，调整下启动命令，理论上可以跑

**Comment by linweiyuan** [comment]
响应不及时的问题修复了，但是没有适配其他项目，适配了我自己的那两个客户端

**Comment by superen7527** [comment]
> 响应不及时的问题修复了，但是没有适配其他项目，适配了我自己的那两个客户端

重新部署了go和主程序，发现还是有延迟呀。。

**Comment by linweiyuan** [comment]
没有看他是怎么判断的，我这边是模仿官网的结构，可能会有点出入

**Comment by superen7527** [comment]
奇怪咯，社区第二个也是官网结构，应该一样才对。

**Comment by linweiyuan** [comment]
晚点再看看，还不太懂 JS

**Comment by linweiyuan** [comment]
这回确实修复了，之前我自作多情加多了个判断，导致前面翻了车

刚试过正常

**Comment by superen7527** [comment]
不知道是不是有缓存还是怎么回事，重新搭建docker还是延迟好久..

**Comment by linweiyuan** [comment]
我这边目前为止测试都正常，很及时

**Comment by superen7527** [comment]
ok 有点事 没上网 后来确实正常了，不过可惜 我这边用不了你的容器了。换了几个vps，java go版本都试过 以及docker-compose方式和命令行方式 有没有网络链，单纯使用映射端口等等我都试过 ，docker内部提示success welcome 但是服务 504

**Comment by superen7527** [comment]
ok 有点事 没上网 后来确实正常了，不过可惜 我这边用不了你的容器了。换了几个vps，java go版本都试过 以及docker-compose方式和命令行方式 有没有网络链，单纯使用映射端口等等我都试过 ，docker内部提示success welcome 但是服务 504
