### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by itcuihao** [linweiyuan/go-chatgpt-api#42]
```
Client error '429 Too Many Requests' for url 'http://go-chatgpt-api:8080/conversation'
For more information check: https://httpstatuses.com/429
```
这是什么缘故呢？

**Comment by linweiyuan** [comment]
字面意思，太多请求了，登录网页版看下是不是这样

**Comment by itcuihao** [comment]
> 字面意思，太多请求了，登录网页版看下是不是这样

验证过网页版正常，挺奇怪的

**Comment by linweiyuan** [comment]
要确保两个地方用的 token 一样

**Comment by iknow2333** [comment]
ChatGPT error 429: {"errorMessage":"Too many requests in 1 hour. Try again later."}
我在3个vps上都配置了go-chatgpt-api并且分别给了不同的程序用，但是都会同时出现这个问题。
而使用公共代理https://ai.fakeopen.com/api/conversation则仍然可以继续使用

**Comment by linweiyuan** [comment]
单纯就这个 api 来说，是没有限制的，429 是官方的限制，这个 `errorMessage` 也是原汁原味返回错误信息

可以试一下发生 429 的时候，登录 ChatGPT 官网看是否 429

闭源代理我没用过不好说

**Comment by iknow2333** [comment]
> 单纯就这个 api 来说，是没有限制的，429 是官方的限制，这个 `errorMessage` 也是原汁原味返回错误信息
> 
> 可以试一下发生 429 的时候，登录 ChatGPT 官网看是否 429
> 
> 闭源代理我没用过不好说

感谢您的回复，同一个号有可能有多个token吗

**Comment by linweiyuan** [comment]
同一个号，每次登录网页获取的 token 都是不同的

**Comment by iknow2333** [comment]
> 同一个号，每次登录网页获取的 token 都是不同的

嗯，我不太专业，如果您说的是accesstoken的话，我是从这里获取accesstoken的
https://chat.openai.com/api/auth/session
如果不清cookie应该是不会不同的吧，我没有清理cookie进入网页版得到的还是一样的token
但是我在不同的设备上得到了不一样的token，等下次出现429时我再尝试看看不同的token能否避免这个错误

**Comment by linweiyuan** [comment]
下回 429，把可以在闭源代理上正常用的 token 放到这个 api 试下

**Comment by iknow2333** [comment]
> 下回 429，把可以在闭源代理上正常用的 token 放到这个 api 试下

实际上我都用的是同样的token，复制在了四个程序上😥但是当api报429时闭源代理还能用

**Comment by seckingyo** [comment]
same error

**Comment by runnysky** [comment]
我也遇到了，plus用户，网页端用3.5的conversation都正常，但通过代理请求就是429，发不出对话了

**Comment by linweiyuan** [comment]
建议下载源码打断点

或分享 token

或录视频

**Comment by iknow2333** [comment]
> 我也遇到了，plus用户，网页端用3.5的conversation都正常，但通过代理请求就是429，发不出对话了


似乎单纯就是用warp的人太多了，如果你搭个套了warp的梯子在高峰期访问官网就会429，如果可能，改成warp+或者warp team会好很多

**Comment by linweiyuan** [comment]
这个 chatgpt-proxy-server-warp 镜像支持 Team：https://github.com/linweiyuan/go-chatgpt-api/issues/128
