### ISSUE TITLE
遇到问题可以前往 `Discussions` 讨论了

### ISSUE THREAD

**Issue by linweiyuan** [linweiyuan/go-chatgpt-api#44]
刚整了个 `Discussions` 在 `Issues` 和 `Pull requests` 的右边

大家有问题可以去那里讨论，好像比较方便

我也第一次玩，好像挺好玩的

**Comment by joe12801** [comment]
hi,i am coming

**Comment by aloasut** [comment]
我一直用大佬的chrome driver proxy做gpt4的proxy用，比官网的界面快。最近遇到的问题是有时候发送了信息以后毫无反应，log也看不出什么问题，重启docker以后解决。请问  go-chatgpt-api-->chatgpt-proxy-server 这一层是否可以加多点故障判断？例如提示超时、被ban等。

**Comment by nikissXI** [comment]
大佬，discussions发帖你那有没有提示的呀

**Comment by linweiyuan** [comment]
> 大佬，discussions发帖你那有没有提示的呀

issue 有邮件，这个 discussion 仿佛没有，我是打开 github 客户端看到的

**Comment by nikissXI** [comment]
@linweiyuan 那感觉问题还是issues比较好吧？大佬不用上班吗，这么高强度回issues

**Comment by linweiyuan** [comment]
我也不清楚哪个好，第一次用

目前的公司可以在家办公，不过马上要换新工作了，到时就没有这么活跃了

**Comment by nikissXI** [comment]
@linweiyuan 原来如此
