### ISSUE TITLE
这报错是怎么回事

### ISSUE THREAD

**Issue by lsw1589034474** [linweiyuan/go-chatgpt-api#45]
![image](https://user-images.githubusercontent.com/54879658/232847825-2889a5df-6f8e-4baa-9714-5968015bcf44.png)

**Comment by linweiyuan** [comment]
更新最新镜像可解决

**Comment by lsw1589034474** [comment]
![image](https://user-images.githubusercontent.com/54879658/232939341-f99ed555-6559-4910-919b-7aeb2c795a80.png)
使用得latest版本，不是最新得吗

**Comment by lsw1589034474** [comment]
![image](https://user-images.githubusercontent.com/54879658/232948188-34839cce-0f24-4cca-94d9-6ef4727bb814.png)
重新pull报错这个

**Comment by lsw1589034474** [comment]
![image](https://user-images.githubusercontent.com/54879658/232948267-f72e3300-b214-49ae-b618-f7be911cbaeb.png)
代理服务正常

**Comment by linweiyuan** [comment]
只是 pull 了，其他配置没改过报了这个错？

不应该，试下连 proxy 也重启一下，先 proxy 再 api

**Comment by lsw1589034474** [comment]
![image](https://user-images.githubusercontent.com/54879658/232949783-c9ec5ed1-52ea-4670-a612-9fe1f5753690.png)
现在报这个错

**Comment by linweiyuan** [comment]
参考下 #27

**Comment by lsw1589034474** [comment]
按照#27还是不行

**Comment by linweiyuan** [comment]
那要换 IP 了

**Comment by lsw1589034474** [comment]
换服务器得ip吗？换台主机？

**Comment by linweiyuan** [comment]
对

那么你参考那个 issue 访问 ipinfo.io 会返回什么

**Comment by lsw1589034474** [comment]
![image](https://user-images.githubusercontent.com/54879658/232958053-5d388a27-cfda-4ea9-9963-30c5d21e2065.png)
刚才重启了下，现在api没有日志了

**Comment by lsw1589034474** [comment]
![image](https://user-images.githubusercontent.com/54879658/232959206-00b14f3d-d1b0-4bc7-91f5-9ce47c4c91e5.png)
api没有日志和这个报错有关系吗？

**Comment by linweiyuan** [comment]
API 长期不出现 Welcome 可以重启一下

这个错误是连不上 Cloudflare，国外服务器？

本地部署也会这个错

**Comment by lsw1589034474** [comment]
API不出现Welcome 重启试过了，还是没有日志

**Comment by linweiyuan** [comment]
你在这台服务器上开个代理，然后用自己电脑连到这个代理，接着访问 ChatGPT 官网，看正不正常

**Comment by lsw1589034474** [comment]
访问不了

**Comment by linweiyuan** [comment]
国外服务器？哪个国家的

恐怕要换一台，因为连不上 ChatGPT 了

**Comment by linweiyuan** [comment]
proxy 其实不用看，没有日志的

warp 看上去是连不上，要确保能连上外网，看看是否出站有限制

或者你试下别人说的在服务器上直接跑 warp 而不是容器

**Comment by lsw1589034474** [comment]
![image](https://user-images.githubusercontent.com/54879658/233020819-985acd01-a664-4b52-ba9a-529d8acc6c18.png)
容器内是通外网的，是不是服务端的原因？

**Comment by linweiyuan** [comment]
别 ping 百度，试下 ping google.com

或者 curl -v https://chat.openai.com，如果卡住，那么就是网络不通，然后通过 warp 代理再 curl 一遍，这个测试最靠谱

**Comment by lsw1589034474** [comment]
![image](https://user-images.githubusercontent.com/54879658/233028267-962d4971-12ee-4430-907f-058c554de5f5.png)
ping google不通，curl 网络不可达，这个需要配置什么

**Comment by linweiyuan** [comment]
看下 #25

服务器在不在支持名单

其实你翻看记录会发现我问了你两遍哪个国家的服务器，你都没正面回答，国内肯定是不行的

**Comment by lsw1589034474** [comment]
用的国内服务器

**Comment by linweiyuan** [comment]
> 国内服务做梯子可以吗？
> 

可以

**Comment by lsw1589034474** [comment]
行  你发我个连接

**Comment by linweiyuan** [comment]
晚一点回家用电脑看看，不知道这个链接有没有更新

**Comment by linweiyuan** [comment]
https://www.vultr.com/?ref=7372562

他的条例是这样的，如果到时我收到了 $10，可以给你转 $5

Refer Vultr.com and earn $10 per paid signup!
1. $10 earned for every new unique paid user you refer.
2. Referred users must be active for 30+ days and use at least $10 in payments to be counted as verified sales.
3. Payouts are finalized and issued on the business day following the 1st and 15th of each month.
4. Your referral link below uniquely identifies your account. Use this code when linking to Vultr.com and start earning today!

**Comment by linweiyuan** [comment]
参考：https://github.com/linweiyuan/go-chatgpt-api/discussions/54#discussioncomment-5660950

**Comment by lsw1589034474** [comment]
![image](https://user-images.githubusercontent.com/54879658/233112781-9aa16b6c-16b1-4724-8bfc-909a66420baa.png)
请求报错

**Comment by lsw1589034474** [comment]
![image](https://user-images.githubusercontent.com/54879658/233244969-41abf9df-195a-4972-9869-5fa01c0b6001.png)
![image](https://user-images.githubusercontent.com/54879658/233245066-90b6ea24-e50f-4d3b-b5a1-d53e76fa8aea.png)
容器内都通外网，怎么还会连不上？

**Comment by linweiyuan** [comment]
NETWORK_PROXY_SERVER 填 http://123.127.221.23:7890（换掉 warp 配置）

看看会发生什么

**Comment by lsw1589034474** [comment]
可以了，原来的地址什么原因连不上的？

**Comment by linweiyuan** [comment]
不确定你的网络环境，下面是我猜的

看到日志 curl 的时候其实设置了代理，但是直接启动 warp 容器，容器不认识这个代理，没有通过代理出去，所以网络不通

然后因为通过这个 7890 可以连通外网，所以就换成这个

至于 warp，是 Access denied 才要用的，前提是网络要通，现在能直连，那就不用，最好了

**Comment by lsw1589034474** [comment]
7890是做了代理得端口，容器使用了宿主机得全局代理，容器得请求都会通过7890端口去代理，curl是可以用，代理日志也可以warp请求已经代理到了，全局代理是http和https，warp会不会通过四层得方式去连接，没有被代理到？

**Comment by linweiyuan** [comment]
不清楚，还不是很懂这个 warp
