### ISSUE TITLE
go-chatgpt-api 一直没反应，没有 Welcome 的提示

### ISSUE THREAD

**Issue by dcynsd** [linweiyuan/go-chatgpt-api#47]
<img width="710" alt="image" src="https://user-images.githubusercontent.com/46182156/232942632-356467db-07b4-4e52-b53a-f02d80ef7b34.png">

**Comment by dcynsd** [comment]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/46182156/232942790-50d5861e-b42e-49c5-a44c-69fa5f605f59.png">

**Comment by linweiyuan** [comment]
重启下 API，处理验证码失败了

如果还不行，看下其他服务的日志

**Comment by dcynsd** [comment]
<img width="2552" alt="image" src="https://user-images.githubusercontent.com/46182156/233228394-877d06c7-8ab1-425f-9443-337bdf6c69fe.png">

**Comment by dcynsd** [comment]
<img width="2044" alt="image" src="https://user-images.githubusercontent.com/46182156/233228456-0e4e176d-bcf2-4246-80ed-c0618e1d65be.png">

**Comment by linweiyuan** [comment]
参考 #45

九成是国内服务器
