### ISSUE TITLE
IP blocked，部署warp也无法使用

### ISSUE THREAD

**Issue by VisualSinger** [linweiyuan/go-chatgpt-api#48]

**Comment by VisualSinger** [comment]
version: "3"

services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 6060:8080 # 如果你需要暴露端口如一带多，可以取消注释
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped
    
    
   
![image](https://user-images.githubusercontent.com/24698959/232943096-73af6064-2b2c-420c-aca0-3e4e7eb27fb4.png)

**Comment by linweiyuan** [comment]
这个错误不管它

那么 API 有出现 Access denied 吗？

如果你进去容器然后用代理 curl -x socks5://代理 ipinfo.io 会返回什么

**Comment by linweiyuan** [comment]
参考 #27

**Comment by VisualSinger** [comment]
好的，https://github.com/linweiyuan/go-chatgpt-api/issues/27 可以用，我修改了一下
