### ISSUE TITLE
貌似需要排队处理？

### ISSUE THREAD

**Issue by GNAYUOHZ** [linweiyuan/go-chatgpt-api#49]
同时两个session提问，第二个需要等待第一个回答完才开始

**Comment by linweiyuan** [comment]
你看我 README 上的第二条博客

**Comment by GNAYUOHZ** [comment]
并且程序里加了锁只能一个接一个对话
这个可以改进吗？

**Comment by linweiyuan** [comment]
API 模式是没锁的

ChatGPT 模式目前如果不加锁，那么如果你我用同一个代理，你提问了，我会看到你的回答

这个之前没找到好的办法，未来可能会改也可能改不了

**Comment by linweiyuan** [comment]
属于套个浏览器的局限性

**Comment by liuyongcchungithub** [comment]
> 属于套浏览器的局限性

有没有可能同一个token 加锁 不同的token不加锁

**Comment by linweiyuan** [comment]
不知道可不可以，需要找个时间再测试下

**Comment by GNAYUOHZ** [comment]
是否可以按conversationid加锁呢？这样就和官方使用方式对齐了

**Comment by linweiyuan** [comment]
没这么简单的

依靠浏览器定时刷新获取新 cookie

如果对话过程中刷新，对话中断

如果不刷新，对话 403

如果按人锁，在多人一直用的情况下，浏览器得不到刷新，到时 cookie 一过期，雪崩

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/issues/58#issuecomment-1518996696
