### ISSUE TITLE
问题包含回车的话就报400

### ISSUE THREAD

**Issue by nephen** [linweiyuan/go-chatgpt-api#51]
```go
ERRO[364699] selenium error: panic, need to create a new session and refresh
[GIN] 2023/04/19 - 06:48:26 | 400 |   61.951324ms |       127.0.0.1 | POST     "/conversation"
```

**Comment by nephen** [comment]
```
你好

```
这样的就不行，我手动把消息里面的回车\n去掉就可以了

**Comment by linweiyuan** [comment]
还是没测出来，前端项目用的哪一个？

我这样测试会 200，可以看到请求数据吗？

![2023-04-20_22-45](https://user-images.githubusercontent.com/49076004/233402684-cae349b2-6eea-4f62-bbce-5d9252ed92f4.png)

**Comment by nephen** [comment]
服务器上不知道咋打开google-chrome的窗口，日志里面打印出来是这样

**Comment by linweiyuan** [comment]
用的是哪一款客户端？看起来是传的 JSON 数据本身不合法

api 加判断的话，也只能返回多一个错误信息数据不合法之类的，应该还是要改客户端修改传值处理

**Comment by linweiyuan** [comment]
因为 api 反序列化 json 已经失败了，所以不能后续去掉回车，要客户端改完再提交合法 json

**Comment by nephen** [comment]
嗯，我在客户端加了`strings.ReplaceAll(conversation.Content, "\n", "\\n")`后再请求是没有问题的
