### ISSUE TITLE
可以支持不同accessToken的同一时间请求吗？目前要等另一个结束才能回答

### ISSUE THREAD

**Issue by yifangyujason** [linweiyuan/go-chatgpt-api#58]
用不同的accessToken发起提问，必须要等待其中一个回答结束，另一个才开始回答，能优化下吗？感谢

**Comment by linweiyuan** [comment]
参考 #49

**Comment by linweiyuan** [comment]
不确定

**Comment by JasonYFY** [comment]
我这边启动了两个go-chatgpt-api，但都是对应同一个chatgpt-proxy-server，用不同的accessToken同时发起提问是能够成功的，请问这是什么原因，有没有更好的实现方式
（我的chatgpt-web服务改造了下，根据ip调用不同的go-chatgpt-api服务且使用不同的accessToken）

**Comment by linweiyuan** [comment]
正常行为

api 加锁，proxy 并不加

如果 api_1 中聊天数据正在返回，此时 api_2 刚好触发浏览器（proxy）刷新，那么 api_1 就会莫名断开回复

**Comment by JasonYFY** [comment]
api_1和api_2对于proxy中的浏览器而言是浏览器中不同的页签吗？可以设置为只刷新对应的页签吗？这样就不会受影响了吧？

**Comment by linweiyuan** [comment]
好像你对，我搞混了，两个 api 互不影响

但是，这样做又能用来干什么呢？

我不是杠，是疑问

**Comment by linweiyuan** [comment]
目前为止没有找到好办法，一一绑定是迫于无奈，这个不知何年何月能解决

**Comment by JasonYFY** [comment]
那这个问题好解决吗？

> 正常行为
> 
> api 加锁，proxy 并不加
> 
> 如果 api_1 中聊天数据正在返回，此时 api_2 刚好触发浏览器（proxy）刷新，那么 api_1 就会莫名断开回复

**Comment by linweiyuan** [comment]
> 目前为止没有找到好办法，一一绑定是迫于无奈，这个不知何年何月能解决

**Comment by linweiyuan** [comment]
目前简单测试过支持了，可以试一下有无其他 bug

**Comment by JasonYFY** [comment]
感谢大佬，我马上试。顺便问问，我还需要启动了两个go-chatgpt-api吗？

**Comment by linweiyuan** [comment]
一个即可，什么配置都不变

**Comment by JasonYFY** [comment]
很棒，目前没有什么问题

**Comment by JasonYFY** [comment]
chatgpt-proxy-server一夜之间产生大量的日志，塞满了空间，不知道什么原因
![image](https://user-images.githubusercontent.com/31659735/234149450-a9cb96ec-c670-4da7-b5e7-1a0f4561f664.png)
![image](https://user-images.githubusercontent.com/31659735/234149784-811d30d6-6c10-4113-8f62-d7bcdc665f05.png)
![image](https://user-images.githubusercontent.com/31659735/234149982-0e3439c8-c590-4033-8ca5-f88337566d93.png)

**Comment by linweiyuan** [comment]
加个环境变量 `LOG_LEVEL=OFF` 在 `chatgpt-proxy-server` 上重启

其实挺矛盾的，日志少了不好排查，多了占空间

**Comment by JasonYFY** [comment]
嗯嗯，我这样加也可以吧？
![image](https://user-images.githubusercontent.com/31659735/234152622-43ef4ae1-5965-46aa-a059-6e6fb936eac8.png)

**Comment by linweiyuan** [comment]
这个 `logging` 参数我还从来没用过，不确定可不可以，可以试一下

**Comment by JasonYFY** [comment]
> 这个 `logging` 参数我还从来没用过，不确定可不可以，可以试一下

有效的，到500m后会清空日志重新记录
