### ISSUE TITLE
会话上下文丢失

### ISSUE THREAD

**Issue by xiaoguaishou92** [linweiyuan/go-chatgpt-api#61]
![image](https://user-images.githubusercontent.com/20310407/233357942-8639ee4c-0054-4ceb-85a7-c93de5ec31ba.png)
正确错误分割线------------------------------------------------------------------------------------------------------
下面是chatgpt-web上同一个会话的截图----------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/20310407/233358482-101f9e08-60da-47bc-af6a-2049a562d624.png)
下面是对应的官网截图-------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/20310407/233358678-c4616716-349e-423e-9506-624d53884f45.png)
问了一个我想学外语的问题，通过其他的代理访问第一显示不全，可以让他继续能在一个对话框输出。
但是使用go-chatgpt-api自建的代理不会继续回答，从官网看是变成了两个对话。

**Comment by xiaoguaishou92** [comment]
> 是左边两个对话，还是同一个对话里的？

更新了一下问题。
第一张图是用chatgpt-web项目走https://ai.fakeopen.com/api/conversation 代理问的，能联系上下文。
第二张图是用chatgpt-web项目走自建代理问的，丢失上下文。
第三张图是在官网截图的拆分的会话的回答

**Comment by linweiyuan** [comment]
看看官网左边是否有两个新对话

如果还是同一个对话，但是上下文丢了，这个就无法修复

**Comment by xiaoguaishou92** [comment]
> 看看官网左边是否有两个新对话
> 
> 如果还是同一个对话，但是上下文丢了，这个就无法修复

官网这边儿您提供的这个是两个了。

**Comment by linweiyuan** [comment]
好像有点阴阳怪气

可以复现吗，待会我去试试，不知道是不是官方改了接口

**Comment by xiaoguaishou92** [comment]
> 好像有点阴阳怪气
> 
> 可以复现吗，待会我去试试，不知道是不是官方改了接口

没有没有，没有对大佬不敬的意思。。。是为了表达清楚问题。。。 这种长对话是100复现。

**Comment by xiaoguaishou92** [comment]
我刚刚开隐私窗口试了一下，然后又清除浏览器缓存试了一下。发现这个问题可能是浏览器缓存问题。具体原因没有定位到。。。

麻烦大佬了，我自行关闭
