### ISSUE TITLE
How do I turn off extensive debug logging?

### ISSUE THREAD

**Issue by acheong08** [linweiyuan/go-chatgpt-api#64]
![image](https://user-images.githubusercontent.com/36258159/233393372-9150d6b4-9b84-4227-8b7a-008e5a9317d0.png)

This is a bit much

**Comment by linweiyuan** [comment]
Can't find a way to turn off these logs, looks like there's no parameter to use with `warp-svc`: https://community.cloudflare.com/t/disable-warp-svc-debug-logs/382246

I simply use a hard "grep" to filter them, pull new image and set env var `LOG_LEVEL` to `DEBUG`, `INFO`, `WARN` or `ERROR`, default `INFO`.
