### ISSUE TITLE
Question/Suggestion: cf_clearance refresh & downtime

### ISSUE THREAD

**Issue by acheong08** [linweiyuan/go-chatgpt-api#65]
From what I understand, the tab refreshes every minute and solves the captcha if necessary. This could cause some very small downtime.

My current solution requires 2 instances (modified):

## Instance 1:
This was tweaked to clear all cookies every 10 minutes and refresh, forcing it to fetch a new cf_clearance. It exposes an endpoint to get the cookies.

## Instance 2:
This was tweaked to fetch a new cf_clearance from instance 1 every 10 minutes. This ensures it never has to refresh and will not have any downtime.

## Question/suggestion

Is there any way to do this via an incognito tab and the normal tab running within the same instance? I don't have much experience with browser automation so I apologize for my ignorance.

**Comment by linweiyuan** [comment]
How to come up with the 10-minute time limit? Sometimes when I test for 3 or even 2 minutes, will get a 403.

**Comment by acheong08** [comment]
The standard expiry is 30 minutes

**Comment by linweiyuan** [comment]
Only 2 minutes, should I keep calling API to extend to 30 minutes?

https://user-images.githubusercontent.com/49076004/233533755-29d5dc49-cf8f-46b1-b369-9c25a63a985d.mp4

**Comment by acheong08** [comment]
Is this not planned anymore?

**Comment by linweiyuan** [comment]
I test with a new endpoint to return all cookies, and then copy them to replace cookies in another browser, still get a 403.

**Comment by acheong08** [comment]
browser must be identical in version/user-agent/etc

**Comment by linweiyuan** [comment]
Oh, need to retry later.

**Comment by linweiyuan** [comment]
I have tested running two instants/sessions and both of them were sharing same headers, cookies, URLs etc, not work.

However, if I running one browser with two tabs, one tab for refreshing cookies, one for API communication, it works. And the API tab will not be interrupted by the refreshing tab, now it supports multiple conversations in the same time.

I still need to refresh every minute or 403 will be returned. (maybe my account is a normal account?)

Thanks for you idea.
