### ISSUE TITLE
如何在不使用 Docker 情況下部屬專案?

### ISSUE THREAD

**Issue by Neillife** [linweiyuan/go-chatgpt-api#66]
Hi~ 感謝你講解原理並提供的儲存庫

想詢問有沒有不使用 Docker 在本地部屬的操作?
因為我的電腦作業系統為 Windows 10 無法安裝 Docker
原因是 Virtualization 不支援
在瀏覽專案的文件時並沒有找到相關的資訊
想請問是否有相關的資源或是文件可以參考呢?

謝謝你寶貴時間的撥空回覆

**Comment by linweiyuan** [comment]
Hello，我手上只有 `Linux` 版本的 `undetected_chromedriver`，如果需要其他版本，可以依照以下步驟：

1. 克隆 https://github.com/ultrafunkamsterdam/undetected-chromedriver 庫
2. 執行 `example/example.py` 範例程式，檔案会生成於以下路徑：https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/bf7dcf8b5713020de7454844fb80036b8c456503/undetected_chromedriver/patcher.py#L39-L48
3. 可以前往这个連結下載 `warp` 客戶端：https://developers.cloudflare.com/warp-client/get-started/
4. 然后用以下命令开启服务：https://github.com/linweiyuan/docker-services/blob/main/linweiyuan/chatgpt-proxy-server-warp/run.sh#L7-L12

要打包出 `go-chatgpt-api`，請使用以下命令：`go build -ldflags="-w -s" -o go-chatgpt-api main.go`

希望對你有所幫助

**Comment by Neillife** [comment]
Hi~ @linweiyuan 我根據提供的步驟經過一些坑之後，成功在 ```Win10``` 作業系統不使用 ```Docker``` 方式下成功部屬囉！
以下提供 ```Win10``` 不使用 ```Docker``` 的部屬步驟：

1. 安裝 undetected-chromedriver
    可使用 ```pip install undetected-chromedriver``` 進行安裝
2. Build 出 ```undetected_chromedriver``` EXE
    成功安裝後需要拿出 ```undetected_chromedriver``` 的 chromedriver 執行檔 (EXE)
    有兩種方式可以 Build 出 EXE
    1. 執行 [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) 庫中的 ```example/example.py``` 範例程式
    2. 使用以下提供的 Python code 存檔後運行
    ```python
    import undetected_chromedriver as uc
    
    driver = uc.Chrome()
    open = True
    while True:
        if open:
            driver.get("https://www.google.com/")
            open = False
    ```
    在終端執行 ```python <存檔的 py 名稱>.py```
    執行後會開啟 ```chromedriver``` 並跳轉至 google 首頁停留
    ### 這時候不要關閉 ```chromedriver```
3. 步驟 2 執行其中一項，檔案會生成於以下路徑 詳見 [LINK](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/bf7dcf8b5713020de7454844fb80036b8c456503/undetected_chromedriver/patcher.py#L39-L48)。
    如果使用的是 2-2 Build EXE 需要先把檔案複製一份 EXE ，再關閉 py 執行開啟的 ```chromedriver```。
    ### 因為直接關掉檔案會被移除
    使用 2-1 執行完 ```example/example.py``` 範例程式可直接到生成路徑下拿出 EXE
    **建議把 Build 出的 EXE 放到 clone [go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api) 專案路徑下**
4. 啟動專案
    ### 先運行 ```undetected_chromedriver``` 後運行 [go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)
    在終端運行以下指令 (EXE 路徑可自行更改或是 cd 到 EXE 路徑下運行指令)
    ```bash
    .\undetected_chromedriver.exe --allowed-ips= --allowed-origins=*
    ```
    因為原專案 code 使用的是 ```Docker``` 部屬，```Proxy``` 代理位址是使用```環境變數```設定在 ```Docker compose``` 中，
    所以沒有使用 ```Docker``` 部屬，需要自行設定```環境變數```或是直接更改 code 裡的變數。
    ```Windows``` 設定```環境變數```比較麻煩，也是怕把環境用髒得關係，這裡就不教了。 (有興趣可以自己搜尋教學)
    更改 code 變數開啟  ```webdriver.go``` ，檔案路徑如下:
    ```
    go-chatgpt-api\webdriver\webdriver.go
    ```
    開啟後找到以下 code 並更改
    ```go
    // 原本的程式碼
    chatgptProxyServer := os.Getenv("CHATGPT_PROXY_SERVER")
    // 修改成你自己的代理 IP 記得要帶上 port 號，9515 是與 chromedriver 通訊。
    chatgptProxyServer := "http://yourIP:9515"
    // 如果是本地部屬的話 IP 直接設定 127.0.0.1 即可，以下就可以略過。
    
    // 有需要代理轉發可以再設定 warp IP
    // 原本的程式碼
    networkProxyServer := os.Getenv("NETWORK_PROXY_SERVER")
    // 修改成你自己的代理轉發 IP 記得要帶上 port 號，65535 是動態或私有端口，用於代理應用程式轉發上。
    // port 被占用可以設定在 49152到65535 之間
    networkProxyServer := "yourIP:65535"
    ```
    設定好後運行 [go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api) 專案
    終端運行以下指令 (記得路徑要對 ```.``` 代表目前路徑此專案是運行 ```main.go``` 請在 ```main.go``` 路徑下執行指令)
    ```bash
    go run .
    ```

----

以上步驟沒有任何狀況，運行時 [go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api) ```Log``` 會顯示 ```Welcome to ChatGPT```。
![image](https://user-images.githubusercontent.com/76508017/233841930-65609854-c6d3-48f5-bc77-9af9b8b36968.png)


undetected_chromedriver 因為步驟中指令不是使用後台運行，所以終端會顯示 DevTools listening on ws://yourIP..... 。
![image](https://user-images.githubusercontent.com/76508017/233841853-8681e3ae-25b3-4c7d-a9eb-e1a4c80dde73.png)


我使用的是 [acheong08](https://github.com/acheong08) 大老提供的 [ChatGPT](https://github.com/acheong08/ChatGPT) 庫
自架本專案代理後串接自己的 Discord BOT
![image](https://user-images.githubusercontent.com/76508017/233842234-6a142b52-48e9-422b-9276-57847331dfcc.png)


----

後記:
講一下 ```Win10``` 不使用 ```Docker``` 的部屬可能遇到的問題。
首先是 port 被占用的問題
[go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api) 預設執行後會使用 port 8080
所以如果有執行不起來的狀況可以檢查一下 port 8080 是否被占用
可以自行更改預設使用 port 在 ```main.go``` 中
```go
// 找到此段後可以自行更改預設使用 port
err := router.Run(":8080")
```

Build undetected_chromedriver EXE 問題
我自己不是使用 ```example.py``` 範例程式 Build 的，因為不管怎麼 run 都出錯。
查了很多資料遇到很多人狀況都跟我一樣而且還找到更多安裝和使用坑...，看看 [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) 庫裡的 ```Issues``` 也是一堆狀況。
文檔也沒有寫相關問題...
後來發現直接寫 code 跑跑看 ```undetected_chromedriver``` 庫是沒問題的。
既然直接寫 code run ```undetected_chromedriver``` 沒問題所以就依照這思路，想到沒問題的話就是會有可執行檔。
就去生成路徑下看執行檔是否存在，結果發現真的有 Build 出。
但關閉 code 執行時開啟的 ```chromedriver``` ，生成路徑下 Build 出的檔案會消失...
於是就直接 ```while True``` 複製出 ```chromedriver``` 了。

Build EXE 問題還有很多就再講一個比較常見的，如果使用步驟 2-2 提供的 Python code 執行時報錯。
可能原因是因為 ```undetected_chromedriver``` 是基於 ```chromedriver``` 上的庫
運行時會自動下載新版本的 ```chromedriver```，會報錯的原因可能是跟自己使用的 Chrome 本版號不相符
可以檢查一下自己使用的 Chrome 版本號。
檢查方式可以開啟 Chrome > 左上角三個點的 ```Icon``` > 設定 > 關於 Chrome
裡面可以看到版本號 (目前時間下 ```2023/04/23``` 最新版本為 ```112```)
如果自己的本版不是 ```112``` 的話可以在 Python code 中設定 ```chromedriver``` 執行版本
如下所示:
```python
import undetected_chromedriver as uc

# 在 version_main 指定你自己的 Chrome 版本號
driver = uc.Chrome(version_main=111)
open = True
while True:
    if open:
        driver.get("https://www.google.com/")
        open = False
```
設定好後再運行 Python code 拿出自己的 EXE 吧。
剩下其他的 undetected_chromedriver 坑我就沒有研究了，有遇到的話請自行研究。


以上是自己在 ```Windows10``` 不使用 ```Docker``` 情況下部屬 [go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api) 專案的紀錄與操作。


### 最後再次感謝
[linweiyuan](https://github.com/linweiyuan)
[acheong08](https://github.com/acheong08)
兩位大老提供的 反代 ([go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)) 和 API 交互 ([ChatGPT](https://github.com/acheong08/ChatGPT))  庫！
