### ISSUE TITLE
Please make sure chatgpt proxy service is running

### ISSUE THREAD

**Issue by kkjkl** [linweiyuan/go-chatgpt-api#68]
chatgpt proxy service 已经正常启动，运行go-chatpt-api后日志显示Please make sure chatgpt proxy service is running

**Comment by linweiyuan** [comment]
确保两个服务在同一个网络，或者配置正确端口映射，先启动 proxy 再 api

**Comment by kkjkl** [comment]
![image](https://user-images.githubusercontent.com/102566990/233569141-ab3c28d2-6ba4-41ce-9a0b-d1c9bde4c191.png)

**Comment by linweiyuan** [comment]
看看配置有无可疑
