### ISSUE TITLE
vps挂着自建代理，没有使用的时候为什么会提示missing token

### ISSUE THREAD

**Issue by 1205129045x** [linweiyuan/go-chatgpt-api#71]
我在海外服务器上用作者的项目自建代理了，为什么我没用代理的时候有时候也会返回日志？
就像下面这个图一样。
<img width="753" alt="截屏2023-04-22 09 55 35 1" src="https://user-images.githubusercontent.com/50540240/233755765-26548827-694a-4e22-8d91-9fe0e881193c.png">
并且经常问问题会返回`Request failed with status code 502 `，有时候半天也不跳出来答案。

**Comment by linweiyuan** [comment]
公网时刻都有人在扫描

是直连吗，还是经过比如 `Nginx` 这种，502 大多是它们出的

**Comment by linweiyuan** [comment]
算直连

但是没有被用到，不管这个日志就好了

如果别人要用的话，用的也是他的 token 才可以用

**Comment by linweiyuan** [comment]
可以试下相同问题，去官网问看回复及不及时

一般来说是回复慢，代理才慢
