### ISSUE TITLE
自建代理接口响应速度很慢

### ISSUE THREAD

**Issue by brickmove** [linweiyuan/go-chatgpt-api#78]
怎么提高接口的响应速度呢，感觉用自建的代理比社区共享的代理速度还慢，每次要等1-3秒才会有流式输出。看其他第三方接入的工具都是响应很快，和chatgpt原始网页差不多。只是和代理有关系吗？
![image](https://user-images.githubusercontent.com/39848781/233965330-17ed2d63-c10e-4cc4-a514-dc192379520e.png)
![image](https://user-images.githubusercontent.com/39848781/233965839-5a40858d-21e3-4d79-aca5-37c5f623b80a.png)

**Comment by linweiyuan** [comment]
我对外从来都说这个程序不保证稳定，只是勉强能用，当社区的公共代理挂了后可以暂时用一下

如果别的程序更快，并且不考虑 token 安全，那完全可以用其他的

我本意不是和别人比，只是当做自己练手的一个项目（我是 Go 新手），当然，如果发现有提速的好方法试验过没问题，欢迎提 PR

（我不是杠，如果觉得有冒犯提前和你说声抱歉）

**Comment by gygy** [comment]
使用三天，目前非常稳定了，也非常快了。自建代理比之前用的公共代理还快。主要还是网络要保证。

**Comment by brickmove** [comment]
> 使用三天，目前非常稳定了，也非常快了。自建代理比之前用的公共代理还快。主要还是网络要保证。

请问你是怎么弄的？我是用的海外的服务器部署的自建代理项目，感觉速度不太行。

**Comment by brickmove** [comment]
> 我对外从来都说这个程序不保证稳定，只是勉强能用，当社区的公共代理挂了后可以暂时用一下
> 
> 如果别的程序更快，并且不考虑 token 安全，那完全可以用其他的
> 
> 我本意不是和别人比，只是当做自己练手的一个项目（我是 Go 新手），当然，如果发现有提速的好方法试验过没问题，欢迎提 PR
> 
> （我不是杠，如果觉得有冒犯提前和你说声抱歉）

没有怪程序的意思，因为目前没啥思路，只是想问下大伙在用代理的情况下怎么优化接口的响应时间。

**Comment by brickmove** [comment]
> > > 使用三天，目前非常稳定了，也非常快了。自建代理比之前用的公共代理还快。主要还是网络要保证。
> > 
> > 
> > 请问你是怎么弄的？我是用的海外的服务器部署的自建代理项目，感觉速度不太行。
> 
> 没有任何优化。用的是国内服务器，就是国内服务器fq。基本能秒回。感觉还是fq网络稳定就行。

你用的是哪个项目做的api接口呢？
