### ISSUE TITLE
稳定了三天，突然提示这个错误

### ISSUE THREAD

**Issue by gygy** [linweiyuan/go-chatgpt-api#79]
panic: runtime error: index out of range [1] with length 0

Error grabbing logs: invalid character 'l' after object key:value pair

**Comment by linweiyuan** [comment]
有说报错在哪一行吗

**Comment by gygy** [comment]
> 有说报错在哪一行吗

哪一行没留意。看起来是什么超出了边界。
刚才远程恢复了虚拟机，现在又正常了。过段时间再看看。

**Comment by linweiyuan** [comment]
已修复，但是这个错为何出来，服务器配置是多大的

**Comment by gygy** [comment]
> 已修复，但是这个错为何出来，服务器配置是多大的

虚拟机:分配18G内存，8核，交换内存8G

**Comment by linweiyuan** [comment]
...

我以为内存小另一个 tab 被自动关掉了，但目前看起来不是

**Comment by gygy** [comment]
> ...
> 
> 我以为内存小另一个 tab 被自动关掉了，但目前看起来不是

下次在观察下。早上也是恢复快照解决。

**Comment by gygy** [comment]
连续运行一段时间后，出现下面错误

},

"default_content_setting_values": {

"geolocation": 1

},

"default_content_settings": {

"geolocation": 1,

"mouselock": 1,

"notifications": 1,

"popups": 1,

"ppapi-broker": 1

},

"password_manager_enabled": false

},

"safebrowsing": {

"enabled": false

},

"search": {

"suggest_enabled": false

},

"translate": {

"enabled": false

}

}

[1682576047.853][INFO]: Populating Local State file: {

"background_mode": {

"enabled": false

},

"ssl": {

"rev_checking": {

"enabled": false

}

}

}

[1682576047.853][INFO]: Launching chrome: /opt/google/chrome/google-chrome --allow-pre-commit-input --disable-background-networking --disable-blink-features=AutomationControlled --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-gpu --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-blink-features=ShadowDOMV0 --enable-logging --headless=new --incognito --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.com.google.Chrome.u7C0ty data:,

[1682576048.063][INFO]: [8bd488ec6754b024a0d5ce2241054d4b] RESPONSE InitSession ERROR unknown error: Chrome failed to start: crashed.

(unknown error: DevToolsActivePort file doesn't exist)

**Comment by linweiyuan** [comment]
上网查了这个错误，提供的解决方法加那几个参数目前都是有加的

API 的错误好处理，但是浏览器的错误目前不是很懂怎么修复

不能用时只能先重启应付一下了

**Comment by linweiyuan** [comment]
如果看日志报错了，但是不影响 API 使用，那么可以不管它

**Comment by gygy** [comment]
> 上网查了这个错误，提供的解决方法加那几个参数目前都是有加的
> 
> API 的错误好处理，但是浏览器的错误目前不是很懂怎么修复
> 
> 不能用时只能先重启应付一下了

重启好了。下午出现了两次这个问题。

**Comment by gygy** [comment]
继续出现
INFO[0005] Welcome to ChatGPT 

[GIN] 2023/04/27 - 06:39:30 | 200 | 2.18608104s | 192.168.80.1 | POST "/conversation"

panic: runtime error: index out of range [0] with length 0

goroutine 41 [running]:

github.com/linweiyuan/go-chatgpt-api/webdriver.OpenNewTabAndChangeBackToOldTab()

	/app/webdriver/webdriver.go:101 +0xd1

github.com/linweiyuan/go-chatgpt-api/api/chatgpt.tryToRefreshPage()

	/app/api/chatgpt/chatgpt.go:50 +0x3a

github.com/linweiyuan/go-chatgpt-api/api/chatgpt.init.0.func1()

	/app/api/chatgpt/chatgpt.go:40 +0x3c

**Comment by linweiyuan** [comment]
发下 `go-chatgpt-api` 和 `chatgpt-proxy-server` 配置

**Comment by gygy** [comment]
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      #- NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    networks:      ####使用已创建的网络bridge_internet，并指定IP
      vlan2l:
        ipv4_address: 192.168.80.133
    depends_on:
      - chatgpt-proxy-server
      #- chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    environment:
      - LOG_LEVEL=INFO
    networks:      ####使用已创建的网络bridge_internet，并指定IP
      vlan2l:
        ipv4_address: 192.168.80.134
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=INFO
    networks:      ####使用已创建的网络bridge_internet，并指定IP
      macvlanpasswall:
        ipv4_address: 192.168.80.135
    restart: unless-stopped

networks:         ###此处要先声明已有的网络bridge_internet
 vlan2l:
    external: true

**Comment by gygy** [comment]
> 把配置降成1核1G内存试试

我试试

**Comment by gygy** [comment]
> panic: runtime error: index out of range [0] with length 0

https://www.cnblogs.com/jinziguang/p/13496096.html   错误和这个有关吗

**Comment by linweiyuan** [comment]
目前的报错好比，打开浏览器前脚打开了个标签页面，后脚这个标签页不见了

有多少人用你这个服务，平均一天有多少对话

**Comment by gygy** [comment]
> 目前的报错好比，打开浏览器前脚打开了个标签页面，后脚这个标签页不见了
> 
> 有多少人用你这个服务，平均一天有多少对话

几个人而已

**Comment by linweiyuan** [comment]
好像只有你遇到这些问题，还是其他人遇到但没有提出来呢？

想会不会和虚拟机有关，是什么虚拟机，不能直接物理机跑 docker 吗？

会不会什么资源监控策略，导致一些服务重启了还是啥

**Comment by gygy** [comment]
运行正常了.

**Comment by linweiyuan** [comment]
不用，昨晚已经彻底重构，现在不用套浏览器了，所以不会再有这个问题

**Comment by gygy** [comment]
> 不用，昨晚已经彻底重构，现在不用套浏览器了，所以不会再有这个问题

昨晚到现在, api 日志没有出现一个错误. 以前日志经常出现missing xx...(也是正常的)

**Comment by linweiyuan** [comment]
这个输出被我删了，其实还是有人在扫描，但是没有日志

**Comment by byxinyu** [comment]
[GIN] 2023/06/14 - 19:00:35 |[97;41m 500 [0m|     221.047µs |      172.19.0.3 |[97;46m POST    [0m "/chatgpt/conversation"
[GIN] 2023/06/14 - 19:01:30 |[97;42m 200 [0m| 21.520915345s |      172.19.0.3 |[97;46m POST    [0m "/chatgpt/conversation"
[GIN] 2023/06/14 - 19:01:30 |[97;41m 500 [0m|      213.15µs |      172.19.0.3 |[97;46m POST    [0m "/chatgpt/conversation"


[31m2023/06/14 19:01:30 [Recovery] 2023/06/14 - 19:01:30 panic recovered:
runtime error: index out of range [0] with length 0
/usr/local/go/src/runtime/panic.go:113 (0x432b3e)
/app/api/chatgpt/api.go:40 (0x8f625e)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8fe02a)
/app/middleware/check_header.go:20 (0x8fe011)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x8fddf8)
/app/middleware/cors.go:20 (0x8fdde4)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7bfe21)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x7bfe0c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7bef46)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x7bef29)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x7bdfaa)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x7bdc31)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x7bd8dc)
/usr/local/go/src/net/http/server.go:2936 (0x63e375)
/usr/local/go/src/net/http/server.go:1995 (0x63ac91)
/usr/local/go/src/runtime/asm_amd64.s:1598 (0x466c60)
[0m

同样稳定了几天，出现问题，生成突然中断，用的最新版镜像

**Comment by linweiyuan** [comment]
挖坟而不是提重复 issue 好评

从错误信息来看是前端传少了参数
