### ISSUE TITLE
长回复最后丢字是怎么回事？

### ISSUE THREAD

**Issue by hondaya06** [linweiyuan/go-chatgpt-api#8]
长回复到最后总会丢一两个字。使用默认反代没这个问题。

**Comment by hondaya06** [comment]
<img width="560" alt="iShot_2023-04-08_14 08 15" src="https://user-images.githubusercontent.com/80587577/230706511-f79183bd-02a1-4cff-a385-d0627a3b3e15.png">
<img width="795" alt="iShot_2023-04-08_14 08 33" src="https://user-images.githubusercontent.com/80587577/230706518-376a2e08-f4c1-4621-9b0c-d4e88404809f.png">

**Comment by linweiyuan** [comment]
在你发这个 issue 前半个小时，我其实修复了这个问题，需要更新镜像

然后刚才加了个新功能，到达字数限制后，后台自动发送新请求来继续对话，简单测试了下，是可以的，不知有无 bug

当 ChatGPT 返回所有数据才结束当前对话，响应可以很长

![long_conversation](https://user-images.githubusercontent.com/49076004/230713554-bdc987df-bdb0-471e-b2f4-b64ddf071c79.png)

**Comment by hondaya06** [comment]
谢谢，测试好用了！

**Comment by hondaya06** [comment]
是不是又开始丢字了。。。

**Comment by linweiyuan** [comment]
确实，我看看为何

**Comment by hondaya06** [comment]
好了，非常感谢！
