### ISSUE TITLE
Request failed with status code 504，这是什么原因？

### ISSUE THREAD

**Issue by JasonYFY** [linweiyuan/go-chatgpt-api#82]
![image](https://user-images.githubusercontent.com/31659735/234542579-08566973-3e7b-4fcf-af2f-de602e2da9be.png)
![image](https://user-images.githubusercontent.com/31659735/234542125-1c02d8f3-bfbd-4d20-98b3-3cbbb24cf6a2.png)

**Comment by linweiyuan** [comment]
如果不是直接 IP 端口直连而是通过比如 Nginx 这种程序，尝试重启一下它

504 在 go-chatgpt-api 里面没有特别处理，我怀疑是刷新网页一直卡住，可以先观察一下看还有无出现

**Comment by JasonYFY** [comment]
我是ip端口直连的，现在一直卡着，我重启试试？

**Comment by linweiyuan** [comment]
突发就正常，一直卡就奇怪了

重启一般会恢复正常
