### ISSUE TITLE
启动go-chatgpt-api报错了，

### ISSUE THREAD

**Issue by kwingart** [linweiyuan/go-chatgpt-api#84]
我是用的国内vps，搭建了clash代理，
我用curl -x http://127.0.0.1:7890/ https://chat.openai.com/ 测试了，我的机场是可以访问openai网页的

[root@VM-20-12-centos clash]# curl -x http://127.0.0.1:7890/ https://chat.openai.com/

<style global>body{font-family:Arial,Helvetica,sans-serif}.container{align-items:center;display:flex;flex-direction:column;gap:2rem;height:100%;justify-content:center;width:100%}https://github.com/Keyframes enlarge-appear{0%{opacity:0;transform:scale(75%) rotate(-90deg)}to{opacity:1;transform:scale(100%) rotate(0deg)}}.logo{color:#8e8ea0}.scale-appear{animation:enlarge-appear .4s ease-out}https://github.com/media (min-width:768px){.scale-appear{height:48px;width:48px}}.data:empty{display:none}.data{border-radius:5px;color:#8e8ea0;text-align:center}https://github.com/media (prefers-color-scheme:dark){body{background-color:#343541}.logo{color:#acacbe}}</style>
Please stand by, while we are checking your browser...

go-chatgpt-api自建反向代理，则报错。
compose文件如下：
version: "3"
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8082:8080 # 宿主机8080端口可按需改为其它端口
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://127.0.0.1:7890
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

启动后，报错如下： 不断重复
[1682525324.534][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525324.534][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525324.636][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525324.675][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525324.710][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525324.736][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525324.765][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525324.792][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525324.792][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE Navigate ERROR unknown error: net::ERR_PROXY_CONNECTION_FAILED
chatgpt-proxy-server | (Session info: chrome=112.0.5615.121)
chatgpt-proxy-server | [1682525324.793][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525324.793][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525324.794][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525324.796][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525324.796][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525324.796][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525325.799][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525325.799][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525325.799][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525325.802][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525325.803][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525325.803][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525326.805][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525326.805][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525326.806][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525326.807][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525326.808][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525326.808][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525327.809][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525327.809][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525327.810][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525327.812][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525327.812][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525327.812][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525328.813][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525328.813][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525328.814][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525328.816][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525328.816][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525328.816][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525329.817][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525329.817][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525329.818][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525329.819][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525329.820][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525329.820][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525330.821][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525330.821][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525330.822][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525330.823][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525330.824][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525330.824][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525331.825][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525331.825][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525331.826][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525331.827][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525331.828][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525331.828][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525332.829][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525332.829][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525332.830][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525332.832][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525332.832][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525332.832][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525333.833][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525333.833][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525333.834][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525333.835][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525333.836][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525333.836][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525334.837][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525334.837][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525334.838][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525334.839][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525334.840][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525334.840][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525335.841][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525335.841][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525335.842][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525335.843][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525335.844][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525335.844][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525336.846][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525336.846][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525336.847][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525336.848][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525336.849][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525336.849][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525337.849][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525337.850][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525337.850][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525337.852][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525337.852][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525337.852][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525338.853][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525338.853][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525338.854][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525338.855][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525338.856][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525338.856][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525339.857][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND GetTitle {
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525339.857][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525339.858][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525339.860][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525339.861][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525339.861][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server | [1682525339.861][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND FindElement {
chatgpt-proxy-server | "using": "class name",
chatgpt-proxy-server | "value": "cf-error-details"
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525339.862][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525339.862][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525339.873][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525339.874][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525339.874][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"class name","selector":"cf-error-details"}
chatgpt-proxy-server | (Session info: chrome=112.0.5615.121)
chatgpt-proxy-server | [1682525340.875][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND FindElement {
chatgpt-proxy-server | "using": "class name",
chatgpt-proxy-server | "value": "cf-error-details"
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525340.875][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525340.876][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525340.883][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525340.884][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525340.884][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"class name","selector":"cf-error-details"}
chatgpt-proxy-server | (Session info: chrome=112.0.5615.121)
chatgpt-proxy-server | [1682525341.885][INFO]: [463da82c8c78c41279b5f326136e9467] COMMAND FindElement {
chatgpt-proxy-server | "using": "class name",
chatgpt-proxy-server | "value": "cf-error-details"
chatgpt-proxy-server | }
chatgpt-proxy-server | [1682525341.885][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525341.886][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525341.893][INFO]: Waiting for pending navigations...
chatgpt-proxy-server | [1682525341.894][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server | [1682525341.894][INFO]: [463da82c8c78c41279b5f326136e9467] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"class name","selector":"cf-error-details"}
chatgpt-proxy-server | (Session info: chrome=112.0.5615.121)
^CGracefully stopping... (press Ctrl+C again to force)

大佬们，能帮忙看看嘛？谢谢 @linweiyuan

**Comment by kwingart** [comment]
后面还有这种报错，意思是，我的proxy不行？但是我上面明明curl测试是OK的
 [1682525673.983][INFO]: Waiting for pending navigations...
chatgpt-proxy-server    | [1682525673.984][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server    | [1682525673.995][INFO]: Waiting for pending navigations...
chatgpt-proxy-server    | [1682525673.996][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server    | [1682525673.996][INFO]: **[813e88ed0ee2b2b0b9de8efbfab744a5] RESPONSE GetElementText "No internet\nThere is something wrong with the proxy server, or the address is incorrect.\nTry:\nContacting the system admin\nChecking the proxy address\nERR_PROXY_CONNECTION_FAILED\nDetails"**
chatgpt-proxy-server    | [1682525674.097][INFO]: [813e88ed0ee2b2b0b9de8efbfab744a5] COMMAND GetTitle {
chatgpt-proxy-server    | }
chatgpt-proxy-server    | [1682525674.097][INFO]: Waiting for pending navigations...
chatgpt-proxy-server    | [1682525674.098][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server    | [1682525674.099][INFO]: Waiting for pending navigations...
chatgpt-proxy-server    | [1682525674.100][INFO]: Done waiting for pending navigations. Status: ok
chatgpt-proxy-server    | [1682525674.100][INFO]: [813e88ed0ee2b2b0b9de8efbfab744a5] RESPONSE GetTitle "chat.openai.com"
chatgpt-proxy-server    | [1682525674.100][INFO]: [813e88ed0ee2b2b0b9de8efbfab744a5] COMMAND GetActiveElement {

**Comment by linweiyuan** [comment]
配置写错了，`socks5://127.0.0.1:7890` 改为 `socks5://172.17.0.1:7890` 试下，或者你自己电脑在路由器的 IP

**Comment by kwingart** [comment]
高手还是高手，果然是这问题。解决了。

**Comment by brickmove** [comment]
同样的问题解决了
