### ISSUE TITLE
被Cloudflare WARP拒绝。。。

### ISSUE THREAD

**Issue by kwingart** [linweiyuan/go-chatgpt-api#87]
配置如下（就是照抄）：
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    environment:
      - LOG_LEVEL=OFF
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    environment:
      - LOG_LEVEL=OFF
    restart: unless-stopped

warp连不上，前面几次成功，后面都被拒绝，有类似这样的情况吗？
[root@VM-20-12-centos go-chatgpt-api-wrap]# docker-compose up
Creating network "go-chatgpt-api-wrap_default" with the default driver
Creating chatgpt-proxy-server      ... done
Creating chatgpt-proxy-server-warp ... done
Creating go-chatgpt-api            ... done
Attaching to chatgpt-proxy-server-warp, chatgpt-proxy-server, go-chatgpt-api
chatgpt-proxy-server         | ChromeDriver was started successfully.
go-chatgpt-api               | INFO[0000] CHATGPT_PROXY_SERVER is: http://chatgpt-proxy-server:9515
go-chatgpt-api               | INFO[0000] NETWORK_PROXY_SERVER is: socks5://chatgpt-proxy-server-warp:65535
chatgpt-proxy-server-warp    | Success
chatgpt-proxy-server-warp    | Success
chatgpt-proxy-server-warp    | Success
chatgpt-proxy-server-warp    | Success
chatgpt-proxy-server-warp    | 2023/04/27 13:56:30 socat[33] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:56:31 socat[34] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:56:31 socat[35] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:56:36 socat[36] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:56:36 socat[37] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:56:36 socat[38] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:56:37 socat[39] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:57:02 socat[41] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:57:07 socat[42] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:57:24 socat[43] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:57:24 socat[44] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:58:07 socat[45] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:58:16 socat[46] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:58:45 socat[47] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused
chatgpt-proxy-server-warp    | 2023/04/27 13:58:45 socat[48] E connect(5, AF=2 127.0.0.1:40000, 16): Connection refused

**Comment by linweiyuan** [comment]
国内的还是国外服务器

**Comment by kwingart** [comment]
国内。。。

**Comment by linweiyuan** [comment]
国内不行：https://github.com/linweiyuan/go-chatgpt-api/issues/74

**Comment by linweiyuan** [comment]
需要自己配置魔法让这三个容器走梯子

**Comment by kwingart** [comment]
梯子有了，用这下面这个配置，可以得到INFO[0042] Welcome to ChatGPT
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
#      - NETWORK_PROXY_SERVER=http://host:port
#      - NETWORK_PROXY_SERVER=socks5://host:port
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

走wrap怎么配置梯子？

**Comment by linweiyuan** [comment]
我没用过国内的没什么经验，据说要配合 v2ray 配置那些分流啥的，你可以去搜搜相关博客

**Comment by linweiyuan** [comment]
国内服务器多少钱一个月

**Comment by linweiyuan** [comment]
或者你可以找那些一键安装 warp 脚本试一下，我也没试过

**Comment by kwingart** [comment]
好便宜的，我去年促销买的企鹅 轻量应用机   3年150人民币左右 2u 4G

**Comment by linweiyuan** [comment]
国内机搞查水表风险自负

**Comment by kwingart** [comment]
> 或者你可以找那些一键安装 warp 脚本试一下，我也没试过

其实，我用那个非wrap方案，已经得到welcome 了。这个我只是试试。
我的问题，还是卡在chatgpt-web那边，web页面卡半天，然后报超时
![image](https://user-images.githubusercontent.com/20697608/234894474-b13d7c87-7f8b-4a83-bc47-37ced19faa2c.png)

[root@VM-20-12-centos chatgpt-web]# docker-compose  up
Creating network "chatgpt-web_default" with the default driver
Creating chatgpt-web_app_1 ... done
Attaching to chatgpt-web_app_1
app_1  |
app_1  | > chatgpt-web-service@1.0.0 prod /app
app_1  | > node ./build/index.mjs
app_1  |
app_1  | Server is running on port 3002
app_1  | sendMessage (32 tokens) {
app_1  |   max_tokens: 1000,
app_1  |   model: 'gpt-3.5-turbo',
app_1  |   temperature: 0.8,
app_1  |   top_p: 1,
app_1  |   presence_penalty: 1,
app_1  |   messages: [
app_1  |     {
app_1  |       role: 'system',
app_1  |       content: "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."
app_1  |     },
app_1  |     { role: 'user', content: '是否ok', name: undefined }
app_1  |   ],
app_1  |   stream: true
app_1  | }
app_1  | TimeoutError: OpenAI timed out waiting for response
app_1  |     at file:///app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:70:24
app_1  |     at new Promise (<anonymous>)
app_1  |     at pTimeout (file:///app/node_modules/.pnpm/p-timeout@6.1.1/node_modules/p-timeout/index.js:48:28)
app_1  |     at ChatGPTAPI.sendMessage (file:///app/node_modules/.pnpm/chatgpt@5.1.2/node_modules/chatgpt/build/index.js:319:14)
app_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
app_1  |     at async chatReplyProcess (file:///app/build/index.mjs:100:22)
app_1  |     at async file:///app/build/index.mjs:237:5

**Comment by kwingart** [comment]
> 国内机搞查水表风险自负

那肯定是。。。我就是一介草民，不盈利，不影响他人，就是好奇玩玩，估计党&*国不会认为我是个事。

**Comment by linweiyuan** [comment]
对哦，已经 `Welcome` 了根本不用搞这个 `warp`

不介意的话，发你微信到我邮箱，我加你，然后发你服务器账号密码给我登录上去看看，事后我也不会再登，你也可以改密码

**Comment by kwingart** [comment]
这个可以关了，我现在的主要问题是accesstoken过期了。。。拿不到新的了。大佬有没有办法？

**Comment by linweiyuan** [comment]
拿不到新的是什么意思

封号了？

https://chat.openai.com/api/auth/session

**Comment by kwingart** [comment]
能正常登陆openai.com,不算封号吧！只是拿到的accesstoken我没法用，放在chatgpt-web里面，会报错ChatGPT error 401: {"errorMessage":"Access token has expired."}

**Comment by linweiyuan** [comment]
发 token 来看看，反正过期了

**Comment by kwingart** [comment]
发你邮箱了

**Comment by linweiyuan** [comment]
并没有收到

**Comment by kwingart** [comment]
![image](https://user-images.githubusercontent.com/20697608/235366507-170a73ed-7a14-405b-a7fe-3ba7983de77e.png)
又发了一个，之前发的估计邮箱地址不对

**Comment by kwingart** [comment]
又发了一个，收件箱是go-chatgpt-api@github.com，应该能收到吧，之前那个发错了

**Comment by linweiyuan** [comment]
收不到，其实邮箱是 `root@linweiyuan.com`

**Comment by linweiyuan** [comment]
收到了，但是这个 token，显示4月27号过期了

**Comment by linweiyuan** [comment]
可以重新登录，然后访问这个链接拿新 token：https://chat.openai.com/api/auth/session

`go-chatgpt-api` 最近也加了登录接口，可以尝试一下，README 有写

**Comment by kwingart** [comment]
是的，过期了。
有办法获取新的token么？教教我。谢谢

linweiyuan ***@***.***> 于2023年5月1日周一 01:14写道：

**Comment by kwingart** [comment]
![image](https://user-images.githubusercontent.com/20697608/235367024-c6ba9a25-e9e7-4fd9-af08-4baa2c065527.png)
试过了，重新登录，然后贴url  https://chat.openai.com/api/auth/session 出现上图

**Comment by linweiyuan** [comment]
是不是 http 429？

如果你信得过我，可以发账号密码给我，我拿了 token 发回给你，后续我不会再用你的账号或者 token

但是，账号如果在某一天有问题或者封号啥的，就不是我的锅

**Comment by kwingart** [comment]
哪里看是不是429？
我是信你，但是这不是我的账号，万一被封，。。。到时出问题，我又要跟人解释。。。。麻烦。。我还是先自己摸索下
多谢多谢！

**Comment by linweiyuan** [comment]
打开 F12 刷新页面可以看

或者退出无痕模式试一下

**Comment by kwingart** [comment]
有tg么，加我，在那里聊方便。我账号 
![image](https://user-images.githubusercontent.com/20697608/235367706-14b1fa90-c21d-46c8-8182-a08c79478375.png)

**Comment by linweiyuan** [comment]
木有 tg

**Comment by kwingart** [comment]
![image](https://user-images.githubusercontent.com/20697608/235367935-ba692678-8d27-4e7b-8d0d-eafedd72953e.png)

终于注意到提示，不知什么原因，不给我刷新token

**Comment by kwingart** [comment]
![image](https://user-images.githubusercontent.com/20697608/235368016-2af9d07c-8711-4bd5-b50c-bdbf3be58f6c.png)

**Comment by linweiyuan** [comment]
第一次见
