### ISSUE TITLE
[Feature request]: provide endpoint for https://chat.openai.com/api/auth/callback/auth0

### ISSUE THREAD

**Issue by acheong08** [linweiyuan/go-chatgpt-api#89]
Required for fixing https://github.com/acheong08/OpenAIAuth

**Comment by linweiyuan** [comment]
Still looking for a way to support, finally get 403 at this moment.

**Comment by linweiyuan** [comment]
Looks like this lib can bypass backend-api 403, if then, the browser is no more needed.

**Comment by linweiyuan** [comment]
Rewrite APIs with tls_client, looks fine.

**Comment by acheong08** [comment]
Very interesting
