### ISSUE TITLE
新版本的代理参数？

### ISSUE THREAD

**Issue by JamesFlare1212** [linweiyuan/go-chatgpt-api#92]
先前通过 `NETWORK_PROXY_SERVER` 这个变量传递代理，那么现在有代理的功能吗？还是有了新的变量名。

**Comment by linweiyuan** [comment]
这个还没改完，打算叫 `PROXY` 算了

**Comment by JamesFlare1212** [comment]
Get it. 我看代码里似乎是增加了登入获取AccessToken的功能？这一方面的README.md是还没写出来？还是API方面什么的还没写好，只是代码有了，暂不支持？

**Comment by zhaojie199512** [comment]
试了下，现在只用go-chatgpt-api就可以实现反代了，作者大大加油，来个readme文档吧

**Comment by linweiyuan** [comment]
@JamesFlare1212 已经支持了，不过目前只支持账号密码（谷歌和微软账号不支持），我看下文档怎么写合适

**Comment by JamesFlare1212** [comment]
好的

**Comment by linweiyuan** [comment]
改成了这个变量： `GO_CHATGPT_API_PROXY`

里面的值不变

**Comment by nephen** [comment]
> 

不支持accessToken吗

**Comment by linweiyuan** [comment]
> > 
> 
> 不支持accessToken吗

支持，不影响
