### ISSUE TITLE
回复的字数少了很多

### ISSUE THREAD

**Issue by muxw** [linweiyuan/go-chatgpt-api#94]
同样的一个问题，官网会完整的回答~~~

**Comment by linweiyuan** [comment]
可以撤回老版本先苟着

镜像标签加个 legacy

晚点再看看怎么修复，新版本这么多问题有点出乎意料

因为我自己用得不多（我一天问不到10条），所以当时没有测试出来

**Comment by aldington-david** [comment]
有复现例子吗

**Comment by linweiyuan** [comment]
已修复

**Comment by aldington-david** [comment]
刚刚试了好像还是会比官网少几个字
测试范例：阅读下面的材料，根据要求写作。
  《红楼梦》写到“大观园试才题对额”时有一个情节，为元妃(贾元春)省亲修建的大观园竣工后，众人给园中桥上亭子的匾额题名。有人主张从欧阳修《醉翁亭记》“有亭翼然”一句中，取“翼然”二字；贾政认为“此亭压水而成”，题名“还须偏于水”，主张从“泻出于两峰之间”中拈出一个“泻”字，有人即附和题为“泻玉”；贾宝玉则觉得用“沁芳”更为新雅，贾政点头默许。“沁芳”二字，点出了花木映水的佳境，不落俗套；也契合元妃省亲之事，蕴藉含蓄，思虑周全。
  以上材料中，众人给匾额题名，或直接移用，或借鉴化用，或根据情境独创，产生了不同的艺术效果。这个现象也能在更广泛的领域给人以启示，引发深入思考。请你结合自己的学习和生活经验，写一篇文章。
  要求：选准角度，确定立意，明确文体，自拟标题；不要套作，不得抄袭；不得泄露个人信息；不少于800字。

**Comment by linweiyuan** [comment]
用的是 `chatgpt-web` 这个前端项目？

**Comment by aldington-david** [comment]
> 用的是 `chatgpt-web` 这个前端项目？

是https://github.com/moeakwak/chatgpt-web-share

**Comment by aldington-david** [comment]
刚刚又试了一下，好像是那个项目的问题，pc端少字换手机端重新加载页面就好了

**Comment by linweiyuan** [comment]
不对，是我这边的问题，修复版本已经在打包了，待会再试试

**Comment by qfdk** [comment]
@aldington-david 那个的前端问题多多....  iOS上基本 很头疼

**Comment by aldington-david** [comment]
实测了新版本已完全修复，gpt4回复量显著回升。

**Comment by aldington-david** [comment]
> @aldington-david 那个的前端问题多多.... iOS上基本 很头疼

我用ipad觉得还好，可能没有深度体验

**Comment by qfdk** [comment]
@aldington-david 我指的是 iOS下的Safari, 我iPhone 12 基本惨不忍睹. 虽然有修复一部分,但是 还是不如ChatGPT-web的项目对移动端友好. 比如回复的时候,iOS不会显示 停止的图标,因为那个需要一个 宽度 等等..
