### ISSUE TITLE
如果单独指向自己本机的socks5代理 会报500

### ISSUE THREAD

**Issue by AKGO47** [linweiyuan/go-chatgpt-api#95]
我本机在40000端口上已经建立了warp的socks5
现在配置这样写 会报500
请大哥debug一下

  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - GO_CHATGPT_API_PROXY=socks5://127.0.0.1:40000
    restart: unless-stopped

**Comment by linweiyuan** [comment]
首先是 127.0.0.1，参考 #74 #84，为什么不能在容器里写 127.0.0.1

如果坚持本地裸跑 warp 而不是跑 warp 容器，需要部署二进制 go-chatgpt-api，然后才能写 127.0.0.1

或者将 40000 端口暴露出去给容器远程连

**Comment by fsyllkn** [comment]
在同样可以访问openai的vps上安装新版镜像，不加warp，一台机器成功（偶尔提示403和429），一台报500，无法访问

**Comment by dqzboy** [comment]
如果要使用宿主机代理的话，容器可以使用主机网络模式

**Comment by fsyllkn** [comment]
我在可以访问openai的vps上直接用更新后的docker容器（注意更新镜像pull一下），成功生成反代服务。
version: "3"
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 38080:8080
    environment:
      - GIN_MODE=release
      - GO_CHATGPT_API_PROXY=
    restart: unless-stopped

**Comment by linweiyuan** [comment]
@fsyllkn 之前不是不行吗，做了什么才可以
