### ISSUE TITLE
如何在window上进行部署？

### ISSUE THREAD

**Issue by wzfyyds123** [linweiyuan/go-chatgpt-api#96]
我不会docker，但是我的windows上有docker环境，如何部署你这个项目？

**Comment by linweiyuan** [comment]
供参考：#35 #66

**Comment by Neillife** [comment]
現在不需要使用 ```undetected_chromedriver``` 囉
只需要 pull 或 clone 專案後在終端運行以下指令
(記得路徑要對 ```.``` 代表目前路徑此專案是運行 ```main.go``` 請在 ```main.go``` 路徑下執行指令)
```bash
go run .
```
如果有運行不起來的情況，可以參考 #66 後記寫的內容。

**Comment by mygit-2023** [comment]
我在 windows 上面一把过， 作者大佬强
