### ISSUE TITLE
official error message is sometimes useful

### ISSUE THREAD

**Issue by xixixi2000** [linweiyuan/go-chatgpt-api#97]
diff api.go api.go.orig
61,77d60
<
<       if resp.StatusCode != 200 {
<                 // Try read response body as JSON
<                 var error_response map[string]interface{}
<                 err = json.NewDecoder(resp.Body).Decode(&error_response)
<                 if err != nil {
<                       c.AbortWithStatusJSON(resp.StatusCode, err)
<                         return
<                 }
<               c.AbortWithStatusJSON(resp.StatusCode, gin.H{
<                         "error": error_response,
<                 })
<
<                 return
<         }
<
<       /*
103d85
<       */

**Comment by xixixi2000** [comment]
`
diff api.go api.go.orig
61,77d60
<
<       if resp.StatusCode != http.StatusOK {
<                 // Try read response body as JSON
<                 var error_response map[string]interface{}
<                 err = json.NewDecoder(resp.Body).Decode(&error_response)
<                 if err != nil {
<                       c.AbortWithStatusJSON(resp.StatusCode, err)
<                         return
<                 }
<               c.AbortWithStatusJSON(resp.StatusCode, gin.H{
<                         "error": error_response,
<                 })
<
<                 return
<         }
<
<       /*
103d85
<       */
`

**Comment by linweiyuan** [comment]
不明白你意思

**Comment by xixixi2000** [comment]
sometimes we not only know the statuscode, but also the real reason, it's sit in the offical error message

**Comment by linweiyuan** [comment]
https://github.com/linweiyuan/go-chatgpt-api/blob/main/api/chatgpt/constant.go#L31-L37

**Comment by xixixi2000** [comment]
for example 429 stands for at least 3 reasons , not only too many requests

**Comment by linweiyuan** [comment]
除了要刷新当前对话和限流，还有哪种情况？

旧版本是有处理的，新版本被我去掉了：https://github.com/linweiyuan/go-chatgpt-api/blob/legacy/api/chatgpt/js.go#L69-L97

官网不同状态码的返回结构都不一样，我统一返回 `errorMessage`，除了 429 其他不适配了

**Comment by xixixi2000** [comment]
ok, if using gpt-4, needs change model, if sending message together needs wait, if conversation_id error, needs refresh

**Comment by xixixi2000** [comment]
just get the string , the struct is not important :)

**Comment by linweiyuan** [comment]
试一下会不会返回对应错误信息？我这边没 GPT-4 测试，试过需要刷新的情况是正常的

**Comment by xixixi2000** [comment]
{"details":{"errorMessage":""},"error":"error sending request"}

**Comment by xixixi2000** [comment]
this code works fine

        if resp.StatusCode != 200 {
                // Try read response body as JSON
                var error_response map[string]interface{}
                err = json.NewDecoder(resp.Body).Decode(&error_response)
                if err != nil {
                        c.AbortWithStatusJSON(resp.StatusCode, err)
                        return
                }
                c.AbortWithStatusJSON(resp.StatusCode, gin.H{
                        "error": error_response,
                })

                return
        }

it returns:
{"details":{"error":{"detail":{"clears_in":5052,"code":"model_cap_exceeded","message":"You have sent too many messages to the model. Please try again later."}}},"error":"error sending request"}

**Comment by xixixi2000** [comment]
And I tried to modified 200 to http.StatusOK before, but it doesn't works :(

**Comment by linweiyuan** [comment]
所以我就说它好多错误的结构都不一样，比如普通 429，它返回的就是：
```json
{
  "detail": "Too many request. （类似）"
}
```
这个 GPT-4 的 429，返回的就是：
```json
{
  "details": {
    "error": {
      "detail": {
        "clears_in": 5052,
        "code": "model_cap_exceeded",
        "message": "You have sent too many messages to the model. Please try again later."
      }
    }
  },
  "error": "error sending request"
}
```

---

你发的代码是要把错误信息原封不动返回给前端，然后每个前端项目都要适配一遍，目前我做的是统一返回 `errorMessage`，那么前端项目只需取即值即可

我改成你那种吧，错误信息会比较准确和及时

**Comment by xixixi2000** [comment]
yes, so I use a string to find the keyword :(

**Comment by linweiyuan** [comment]
更新了，但是没有额外加 `error` 作为 key

**Comment by xixixi2000** [comment]
ok, but key is useless :)
